#!/usr/bin/env python3
"""
Generate a single-file amalgamation of the Bovnar library into dist/:

    dist/bovnar.h   -- the complete public API (all include/*.h, deduped)
    dist/bovnar.c   -- the complete implementation (all src/**/*.{c,h} except
                       the CLI src/bovnar.c), which #include "bovnar.h"

A consumer then needs only those two files:

    cc -c bovnar.c -o bovnar.o          # build the library object
    #include "bovnar.h"                  # use the API

Project `#include "..."` directives are resolved and each project header is
inlined exactly once; system `#include <...>` directives are hoisted and
deduplicated. The build under build/ remains the authoritative one; this is a
convenience distribution form. Run tests/amalgam_smoke.c (CTest target
`bvnr_amalgam`) to verify the generated files compile and work.
"""
import os, re, sys

ROOT = os.path.dirname(os.path.abspath(__file__))

# Directories searched to resolve a project `#include "name"`.
SEARCH_DIRS = [
    "include",
    "src", "src/dom", "src/io", "src/lexer",
    "src/stream", "src/utils", "src/validator", "src/writer",
]

# Public headers, in dependency order (recursion handles transitive includes).
PUBLIC_HEADERS = [
    "bvn_int.h", "bvn_float.h", "bovnar.h",
    "bovnar_si_units.h", "bovnar_currency.h", "bovnar_dom.h",
    "bovnar_stream.h",
]

# Implementation translation units (the CLI src/bovnar.c is intentionally
# excluded: it carries main() and is an application, not part of libbovnar).
IMPL_SOURCES = [
    "src/utils/bvn_int.c",
    "src/utils/bvn_float.c",
    "src/utils/bovnar_si_units.c",
    "src/utils/bovnar_currency.c",
    "src/utils/bovnar_utils.c",
    "src/io/bovnar_io.c",
    "src/lexer/bovnar_state_table.c",
    "src/lexer/bovnar_lexer.c",
    "src/validator/bovnar_validator.c",
    "src/writer/bovnar_writer.c",
    "src/writer/bovnar_write_utils.c",
    "src/writer/bovnar_canon_observer.c",
    "src/dom/bovnar_dom.c",
    "src/dom/bovnar_dom_builder.c",
    "src/stream/bovnar_stream.c",
]

# Capture any trailing content after the directive (e.g. a comment that opens a
# multi-line block) so dropping the include never orphans a "/*".
INC_SYS = re.compile(r'^\s*#\s*include\s*<([^>]+)>(.*)$')
INC_PRJ = re.compile(r'^\s*#\s*include\s*"([^"]+)"(.*)$')


def resolve(name):
    base = os.path.basename(name)
    for d in SEARCH_DIRS:
        p = os.path.join(ROOT, d, base)
        if os.path.isfile(p):
            return p
    return None


def expand(path, inlined, sys_inc, out):
    """Append `path`'s content to out, inlining project headers once and
    collecting system includes into sys_inc (ordered, deduped)."""
    rel = os.path.relpath(path, ROOT)
    out.append(f"\n/* ==================== {rel} ==================== */\n")
    with open(path, encoding="utf-8") as f:
        for line in f:
            ms, mp = INC_SYS.match(line), INC_PRJ.match(line)
            if ms or mp:
                m = ms or mp
                name, trailing = m.group(1), m.group(2)
                # An include that resolves to a project file (quote form, or the
                # <...> form bvn_float.c uses for <bvn_float.h>) is inlined once;
                # a genuine <system> header is hoisted; an unresolved quote
                # include is dropped. Any trailing content (e.g. a comment that
                # opens a multi-line block) is always preserved.
                tgt = resolve(name)
                if tgt:
                    if tgt not in inlined:
                        inlined.add(tgt)
                        expand(tgt, inlined, sys_inc, out)
                elif ms:
                    if name not in sys_inc:
                        sys_inc.append(name)
                if trailing.strip():
                    out.append(trailing + "\n")
                continue
            out.append(line)


def emit_sys_block(sys_inc):
    return "".join(f"#include <{h}>\n" for h in sys_inc)


def build_header():
    inlined, sys_inc, body = set(), [], []
    for h in PUBLIC_HEADERS:
        p = resolve(h)
        if p and p not in inlined:
            inlined.add(p)
            expand(p, inlined, sys_inc, body)
    text = (
        "/* Bovnar — single-file public API (generated by amalgamate.py;\n"
        " * do not edit. Source of truth: include/ and src/). */\n"
        "#ifndef BOVNAR_AMALGAMATION_H\n#define BOVNAR_AMALGAMATION_H\n\n"
        + emit_sys_block(sys_inc) + "\n"
        + "".join(body)
        + "\n#endif /* BOVNAR_AMALGAMATION_H */\n"
    )
    return text, inlined


def build_impl(header_inlined):
    # The public headers already live in bovnar.h; do not re-inline them.
    inlined = set(header_inlined)
    sys_inc, body = [], []
    for c in IMPL_SOURCES:
        p = os.path.join(ROOT, c)
        if not os.path.isfile(p):
            sys.exit(f"missing source: {c}")
        expand(p, inlined, sys_inc, body)
    text = (
        '/* Bovnar — single-file implementation (generated by amalgamate.py;\n'
        ' * do not edit. Source of truth: include/ and src/). */\n'
        '#include "bovnar.h"\n\n'
        + emit_sys_block(sys_inc) + "\n"
        + "".join(body)
    )
    return text


USAGE = (
    "usage: amalgamate.py [OUT_DIR]\n"
    "\n"
    "Generate the single-file amalgamation (bovnar.h + bovnar.c).\n"
    "OUT_DIR defaults to the repository's dist/ directory.\n"
)


def main():
    args = sys.argv[1:]
    if args and args[0] in ("-h", "--help"):
        sys.stdout.write(USAGE)
        return
    if len(args) > 1:
        sys.stderr.write("error: too many arguments\n\n" + USAGE)
        sys.exit(2)
    out_dir = args[0] if args else os.path.join(ROOT, "dist")
    os.makedirs(out_dir, exist_ok=True)
    hdr, header_inlined = build_header()
    impl = build_impl(header_inlined)
    with open(os.path.join(out_dir, "bovnar.h"), "w", encoding="utf-8") as f:
        f.write(hdr)
    with open(os.path.join(out_dir, "bovnar.c"), "w", encoding="utf-8") as f:
        f.write(impl)
    print("wrote %s/bovnar.h (%d bytes) and %s/bovnar.c (%d bytes)"
          % (out_dir, len(hdr), out_dir, len(impl)))


if __name__ == "__main__":
    main()
