#!/usr/bin/env python3
"""
gen_prefixes.py — generate the C SI/IEC prefix tables from prefixes.bvnr.

Emits eight fragments — two enums, two scale tables, two symbol maps, two parse
tables — all from one record per prefix:

    include/bovnar_si_prefix.gen.h     si_prefix_id_e body (si_quecto..si_quetta)
    include/bovnar_iec_prefix.gen.h    iec_prefix_id_e body (iec_kibi..iec_quebi)
    build/generated/bovnar_si_pfx_table.gen.inc   bvni_si_pfx_table rows {factor, exp}
    build/generated/bovnar_iec_pfx_table.gen.inc  bvni_iec_pfx_table rows
    build/generated/bovnar_si_prefix_str.gen.inc  si_prefix_str() cases
    build/generated/bovnar_iec_prefix_str.gen.inc iec_prefix_str() cases
    build/generated/bovnar_si_table.gen.inc       si_table parse rows
    build/generated/bovnar_iec_table.gen.inc      iec_table parse rows

The identity prefixes si_none/iec_none, the lookup helpers, and the table
typedefs stay hand-written. Prefix parse is an exact (length, bytes) match
(base is '~'-separated), so the parse tables need no ordering or length index.
"""
import os

REPO = os.path.dirname(os.path.abspath(__file__))
GENDATA = os.path.join(REPO, "src", "gendata")
import bvnr_data  # noqa: E402
from gen_units import c_string_literal  # noqa: E402

BANNER = ("/* GENERATED by gen_prefixes.py from "
          "src/gendata/prefixes.bvnr — DO NOT EDIT. */\n")
INC = os.path.join(REPO, "include")
UTL = os.environ.get("BVNR_GENERATED_DIR",
                    os.path.join(REPO, "build", "generated"))


def load(path):
    with open(path, "rb") as f:
        return bvnr_data.load(f.read())


def check(prefixes, sysname):
    ids = [p["id"] for p in prefixes]
    if ids != list(range(1, len(prefixes) + 1)):
        raise SystemExit("%s prefix ids must be contiguous from 1" % sysname)
    # Everything below was unchecked, and each omission has a silent failure
    # mode. A duplicate alias makes the linear parse scan pick whichever row
    # comes first while the OTHER prefix still formats to that spelling -- give
    # mega the symbol "m" and a value round-trips off by 10^9 with no diagnostic.
    # A symbol missing from its own alias list emits output the parser cannot
    # read back. A duplicated or mis-typed exponent silently rescales.
    seen_alias = {}
    seen_exp = {}
    for p in prefixes:
        if not p["aliases"]:
            raise SystemExit("%s_%s has no parse spelling" % (sysname, p["name"]))
        if p["symbol"] not in p["aliases"]:
            raise SystemExit(
                "%s_%s formats as %r, which is not one of its own parse "
                "spellings %r -- it would not read back"
                % (sysname, p["name"], p["symbol"], p["aliases"]))
        for a in p["aliases"]:
            if a in seen_alias:
                raise SystemExit("%s: alias %r claimed by both %s and %s"
                                 % (sysname, a, seen_alias[a], p["name"]))
            seen_alias[a] = p["name"]
        e = p["exp"]
        if e in seen_exp:
            raise SystemExit("%s: exponent %d used by both %s and %s"
                             % (sysname, e, seen_exp[e], p["name"]))
        seen_exp[e] = p["name"]


def enumerator(sysname, p):
    return "%s_%s" % (sysname, p["name"])


def gen_enum(prefixes, sysname):
    out = [BANNER]
    for p in prefixes:
        out.append("\t%-12s = %2d,\n" % (enumerator(sysname, p), p["id"]))
    return "".join(out)


def gen_pfx_table(prefixes, sysname, base):
    out = [BANNER]
    for p in prefixes:
        if base == 10:
            factor = "1e%d" % p["exp"]
        else:
            factor = repr(float(base ** p["exp"]))   # exact: power of two
        out.append("\t[%-11s] = {%-12s %4d},\n"
                   % (enumerator(sysname, p), factor + ",", p["exp"]))
    return "".join(out)


def gen_prefix_str(prefixes, sysname):
    out = [BANNER]
    for p in prefixes:
        out.append("\tcase %-12s return %s;\n"
                   % (enumerator(sysname, p) + ":", c_string_literal(p["symbol"])))
    return "".join(out)


def gen_parse_table(prefixes, sysname):
    out = [BANNER]
    for p in prefixes:
        enum = enumerator(sysname, p)
        for sp in p["aliases"]:
            lit = c_string_literal(sp)
            out.append("\t{ %-12s %d, %s },\n"
                       % (lit + ",", len(sp.encode("utf-8")), enum))
    return "".join(out)


def main():
    path = os.path.join(GENDATA, "prefixes.bvnr")
    doc = load(path)
    si = doc["si_prefixes"]
    iec = doc["iec_prefixes"]
    check(si, "si")
    check(iec, "iec")

    artifacts = {
        os.path.join(INC, "bovnar_si_prefix.gen.h"):  gen_enum(si, "si"),
        os.path.join(INC, "bovnar_iec_prefix.gen.h"): gen_enum(iec, "iec"),
        os.path.join(UTL, "bovnar_si_pfx_table.gen.inc"):  gen_pfx_table(si, "si", 10),
        os.path.join(UTL, "bovnar_iec_pfx_table.gen.inc"): gen_pfx_table(iec, "iec", 2),
        os.path.join(UTL, "bovnar_si_prefix_str.gen.inc"):  gen_prefix_str(si, "si"),
        os.path.join(UTL, "bovnar_iec_prefix_str.gen.inc"): gen_prefix_str(iec, "iec"),
        os.path.join(UTL, "bovnar_si_table.gen.inc"):  gen_parse_table(si, "si"),
        os.path.join(UTL, "bovnar_iec_table.gen.inc"): gen_parse_table(iec, "iec"),
    }
    os.makedirs(UTL, exist_ok=True)
    for dest, text in artifacts.items():
        with open(dest, "w", encoding="utf-8") as f:
            f.write(text)
    print("generated %d SI + %d IEC prefixes -> 8 fragments" % (len(si), len(iec)))


if __name__ == "__main__":
    main()
