#!/usr/bin/env python3
"""
gen_currencies.py — generate the C currency catalogue from currencies.bvnr.

Reads the data document with the built-in bvnr_data reader and emits:

    include/bovnar_currency.gen.h                  the block's range macros
    build/generated/bovnar_currency_table.gen.inc  the g_currency_table[] rows

The lookup/index/parse functions in bovnar_currency.c stay hand-written — only
the catalogue rows and the bounds they must agree with are generated. The bounds
used to be hand-written in bovnar_currency.h with nothing connecting them to the
table, which is how a range could be widened without a row behind it; now one
run of this generator produces both.

Records are emitted in ascending .id order, which is the positional order the
O(1) index relies on, and the ids must be contiguous from CURRENCY_FIRST: the
whole catalogue is ONE run, and which entries are crypto is a column of the
table rather than a sub-range of the ids, so a currency of either kind appends
at the end without renumbering anything.

Like the other generators, it reads the document with the built-in bvnr_data
reader, so it needs only Python — no bovnar library.
"""
import os

REPO = os.path.dirname(os.path.abspath(__file__))
GENDATA = os.path.join(REPO, "src", "gendata")
import bvnr_data  # noqa: E402  -- standalone reader; no libbvnr dependency

# Currencies are the "90" block of the base-unit id space. See the layout note
# in include/bovnar.h; the native units are the "10" block and each unit profile
# gets one of the blocks between.
CURRENCY_FIRST = 900000
BLOCK_SIZE = 10000

BANNER = ("/* GENERATED by gen_currencies.py from "
          "src/gendata/currencies.bvnr — DO NOT EDIT. */\n")


def bvnr_c_string(s):
    """Currency codes/names are ASCII; emit a plain C literal, escaping only the
    characters C requires. (No UTF-8 in the catalogue, so no \\xNN splitting.)"""
    if not s.isascii():
        raise SystemExit("non-ASCII in currency field %r — extend the emitter"
                         % s)
    return '"' + s.replace("\\", "\\\\").replace('"', '\\"') + '"'


def load(path):
    with open(path, "rb") as f:
        return bvnr_data.load(f.read())["currencies"]


def validate(curr):
    """Enforce the positional ABI contract and field bounds."""
    ids = [c["id"] for c in curr]
    want = list(range(CURRENCY_FIRST, CURRENCY_FIRST + len(curr)))
    if ids != want:
        bad = next((n for n, (a, b) in enumerate(zip(ids, want)) if a != b),
                   len(want))
        raise SystemExit(
            "currency ids must be contiguous and ascending from %d: record %d "
            "(%s) has id %d, expected %d"
            % (CURRENCY_FIRST, bad, curr[bad]["code"], ids[bad], want[bad]))
    if len(curr) > BLOCK_SIZE:
        raise SystemExit("the currency block holds %d ids; this file has %d"
                         % (BLOCK_SIZE, len(curr)))
    fiat = [c for c in curr if not c["is_crypto"]]
    crypto = [c for c in curr if c["is_crypto"]]
    seen = set()
    for c in curr:
        code = c["code"]
        if not (3 <= len(code) <= 4 and code.isupper() and code.isalpha()):
            raise SystemExit("bad currency code %r" % code)
        if code in seen:
            raise SystemExit("duplicate currency code %r" % code)
        seen.add(code)
        if len(code.encode()) >= 5:
            raise SystemExit("code %r overflows char[5]" % code)
        if len(c["name"].encode()) >= 48:
            raise SystemExit("name %r overflows char[48]" % c["name"])
        # The numeric fields were unchecked, so a typo in the .bvnr shipped
        # silently as wrong money data: .numeric_code = 8000 for UGX generated a
        # table with 8000 in it and the whole build stayed green, and a value
        # above 65535 truncates into the uint16_t field with nothing but a
        # -Woverflow (off unless BVNR_WERROR). Bound them here, where the input
        # is still readable, rather than hoping a warning is noticed.
        num = c["numeric_code"]
        if not (0 <= num <= 65535):
            raise SystemExit("%s: numeric_code %d does not fit uint16_t"
                             % (code, num))
        if not c["is_crypto"] and num == 0:
            raise SystemExit("%s: fiat currencies need an ISO 4217 numeric code"
                             % code)
        if c["is_crypto"] and num != 0:
            raise SystemExit("%s: crypto assets carry no ISO numeric code, got %d"
                             % (code, num))
        minor = c["minor_unit"]
        # The field is a uint8_t. ISO 4217 tops out at 4 (CLF); crypto goes much
        # further -- 18 for ether-style tokens and 24 for NEAR, whose smallest
        # unit is the yoctoNEAR. 38 leaves room for a wider token without
        # admitting a digit-slip like 250.
        if not (0 <= minor <= 38):
            raise SystemExit("%s: minor_unit %d out of range 0..38"
                             % (code, minor))
        if not c["is_crypto"] and minor > 4:
            raise SystemExit("%s: ISO 4217 minor units go up to 4, got %d"
                             % (code, minor))
    # A numeric code identifies a currency, so a repeat is either a typo or a
    # deliberate succession (XCG inherits ANG's 532). Allow at most one pair.
    numbers = {}
    for c in curr:
        if c["numeric_code"] == 0:
            continue
        numbers.setdefault(c["numeric_code"], []).append(c["code"])
    shared = {n: v for n, v in numbers.items() if len(v) > 1}
    if len(shared) > 1 or any(len(v) > 2 for v in shared.values()):
        raise SystemExit("unexpected duplicate ISO numeric codes: %r" % shared)
    return fiat, crypto


def gen_header(curr):
    """The block's bounds, as a committed header.

    These were hand-written in bovnar_currency.h with nothing connecting them to
    the catalogue, so a range could be widened without a row behind it and the
    extra slot read back as a currency with an empty code. One generator now
    emits both, and the row count below is what bovnar_currency.c static-asserts
    the table length against."""
    return "".join([
        BANNER,
        "\n/* The currency block of the base-unit id space: one contiguous run,\n"
        " * ascending, from BVN_CURRENCY_FIRST. A currency's catalogue index is\n"
        " * its id minus BVN_CURRENCY_FIRST — see bvn_currency_index(). Whether\n"
        " * a currency is crypto is a COLUMN of the catalogue, not a sub-range\n"
        " * of the ids, so appending one of either kind renumbers nothing. */\n",
        "#define BVN_CURRENCY_FIRST      %d\n" % CURRENCY_FIRST,
        "#define BVN_CURRENCY_LAST       %d\n" % (CURRENCY_FIRST + len(curr) - 1),
        "#define BVN_CURRENCY_COUNT      %d\n" % len(curr),
        "#define BVNR_CURRENCY_ROWS      %d\n" % len(curr),
    ])


def gen_table(curr):
    out = [BANNER]
    for c in curr:
        out.append("  { %-7s %4d, %2d, %-7s %s },\n" % (
            bvnr_c_string(c["code"]) + ",",
            c["numeric_code"],
            c["minor_unit"],
            ("true," if c["is_crypto"] else "false,"),
            bvnr_c_string(c["name"]),
        ))
    return "".join(out)


def main():
    path = os.path.join(GENDATA, "currencies.bvnr")
    curr = load(path)
    fiat, crypto = validate(curr)
    gendir = os.environ.get("BVNR_GENERATED_DIR",
                            os.path.join(REPO, "build", "generated"))
    os.makedirs(gendir, exist_ok=True)
    dest = os.path.join(gendir, "bovnar_currency_table.gen.inc")
    bvnr_data.write_if_changed(dest, gen_table(curr))
    bvnr_data.write_if_changed(
        os.path.join(REPO, "include", "bovnar_currency.gen.h"),
        gen_header(curr))
    print("generated %d currencies (%d fiat, %d crypto), ids %d..%d -> %s"
          % (len(curr), len(fiat), len(crypto), CURRENCY_FIRST,
             CURRENCY_FIRST + len(curr) - 1, dest))


if __name__ == "__main__":
    main()
