#!/usr/bin/env python3
"""
gen_profiles.py — generate the C unit-profile tables from src/gendata/*.bvnr.

A "unit profile" is an alternative SPELLING for the unit slot, written
"namespace:code". Each profile has one data file in src/gendata/, and this
generator turns the whole set into the tables src/utils/bovnar_profiles.c reads.
See doc/11_bovnar_unit_profiles.md.

Reads each document with the built-in bvnr_data reader (no libbvnr) and emits:

    include/bovnar_profiles.gen.h              enum body: bu_<name> = <id>, for
                                               every OPAQUE unit of every
                                               profile, plus the per-profile and
                                               whole-block bracketing macros
    <gendir>/bovnar_profile_<ns>_prefix.gen.inc      prefix spelling -> decade
    <gendir>/bovnar_profile_<ns>_atom.gen.inc        atom -> native target / opaque id
    <gendir>/bovnar_profile_<ns>_unsupported.gen.inc codes known but refused
    <gendir>/bovnar_profile_<ns>_reverse.gen.inc     base unit -> code to write it as
    <gendir>/bovnar_profiles_conv.gen.inc       si_conv_table rows, all profiles
    <gendir>/bovnar_profiles_policy.gen.inc     prefix policy rows, all profiles
    <gendir>/bovnar_profiles_str.gen.inc        base_unit_str cases, all profiles

The native target of a mapped atom is stored as the SOURCE TEXT of a native unit
expression, not as a pre-baked value_unit_t: the C side parses it once, lazily,
with the same bvn_parse_unit every document goes through. That keeps this
generator from needing a second, divergent implementation of the unit grammar in
Python -- which is exactly how a generated table starts disagreeing with the
parser it feeds.

The atom tables are ordered by DESCENDING code byte length, so the C matcher can
take the longest atom that is a suffix of what it is looking at, the same rule
the native bu_table uses. A flat profile is matched whole rather than by suffix,
but the ordering costs nothing and keeps one emitter for both.

OPAQUE IDS ARE ASSIGNED HERE, NOT IN THE DATA FILES. Each profile owns a BLOCK
of the base-unit id space -- 10000 ids whose leading two digits identify the
vocabulary -- and its opaque units are numbered from the bottom of that block in
declaration order. So a profile that grows a row shifts only its own ids, and a
data file that hand-numbered its rows would be duplicating a number the block
already determines. The assignment lands in include/bovnar_profiles.gen.h, which
is committed, so any shift shows up as a reviewable diff.

Usage:
    [BVNR_GENERATED_DIR=dir] python3 gen_profiles.py [gendata-dir]
"""
import os
import re
import sys

REPO = os.path.dirname(os.path.abspath(__file__))
GENDATA = os.path.join(REPO, "src", "gendata")
GENDIR = os.environ.get("BVNR_GENERATED_DIR",
                        os.path.join(REPO, "build", "generated"))
import bvnr_data  # noqa: E402

BANNER = ("/* GENERATED by gen_profiles.py from src/gendata/%s — "
          "DO NOT EDIT. */\n")


class Profile:
    """One registered namespace.

    ns          the text before the ':' in a unit slot
    data        the data file under src/gendata/
    grammar     "expr" -- the code is an expression over prefixed atoms
                          (UCUM, UDUNITS): operators, exponents, grouping
                "flat" -- the code is one whole token looked up entire
                          (QUDT, UNECE): no operators, no prefixes
    enum_prefix the bu_<prefix>_* namespace for this profile's opaque units
    block       the two-digit block tag of this profile's id range: its opaque
                units are numbered from block * BLOCK_SIZE. Frozen per profile
                (it is the ABI), so it is written here rather than derived from
                the list order -- reordering the registry must not move ids.
    """

    def __init__(self, ns, data, grammar, enum_prefix, block):
        self.ns = ns
        self.data = data
        self.grammar = grammar
        self.enum_prefix = enum_prefix
        self.block = block
        self.doc = None
        self.opaque_first = block * BLOCK_SIZE
        self.opaque_last = block * BLOCK_SIZE - 1
        self.slot_base = 0

    @property
    def cname(self):
        """The C identifier fragment for this profile's table names."""
        return self.ns.replace("-", "_")

    def list(self, name):
        return self.doc.get(name, []) if self.doc else []


# The id-space blocks. 10 is the native units (units.bvnr) and 90 the
# currencies (currencies.bvnr); a unit profile takes one of the tags between,
# which leaves room for seven. See the layout note in include/bovnar.h.
BLOCK_SIZE = 10000
BLOCK_NATIVE = 10
BLOCK_CURRENCY = 90
# Slot 0 of every dense table is bu_none, so the native rows start at 1 and the
# opaque rows after them. Kept in step with gen_units.py by the static assert in
# src/utils/bvn_internal_dims.h, which recomputes the total from both halves.
SLOT_NATIVE_BASE = 1

# The registry. Each profile's BLOCK TAG is what fixes its ids, so this list can
# be reordered or have a profile inserted without renumbering anything: only the
# tag is ABI. A new profile takes the next free tag between 10 and 90.
PROFILES = [
    Profile("ucum",    "ucum.bvnr",    "expr", "ucum",    20),
    Profile("unece",   "unece.bvnr",   "flat", "unece",   30),
    Profile("qudt",    "qudt.bvnr",    "flat", "qudt",    40),
    Profile("qudt-qk", "qudt-qk.bvnr", "flat", "qudt_qk", 50),
    Profile("udunits", "udunits.bvnr", "expr", "udunits", 60),
]

# The decades that have an SI prefix. The fold in bovnar_profiles.c can only
# discharge a residual scale into one of these, so a mapping whose target would
# need any other decade is a build error rather than a runtime surprise.
SI_DECADES = {0, 1, 2, 3, 6, 9, 12, 15, 18, 21, 24, 27, 30,
              -1, -2, -3, -6, -9, -12, -15, -18, -21, -24, -27, -30}


def c_string_literal(s):
    """Encode a Python str as one or more adjacent C string literals.

    Byte-for-byte the same rule as gen_units.py: every non-printable/non-ASCII
    byte becomes a \\xNN escape, and a run of escapes is closed before the next
    plain byte so a following hex digit is never absorbed into the escape."""
    chunks = []
    buf = ""
    buf_esc = None
    for b in s.encode("utf-8"):
        printable = 0x20 <= b < 0x7f and b not in (0x22, 0x5c)
        esc = not printable
        if buf and buf_esc != esc:
            chunks.append((buf_esc, buf))
            buf = ""
        buf += ("\\x%02x" % b) if esc else chr(b)
        buf_esc = esc
    if buf:
        chunks.append((buf_esc, buf))
    if not chunks:
        return '""'
    return " ".join('"%s"' % text for _, text in chunks)


def byte_len(s):
    return len(s.encode("utf-8"))


def load(path):
    with open(path, "rb") as f:
        return bvnr_data.load(f.read())


def die(p, msg):
    raise SystemExit("gen_profiles: %s: %s" % (p.ns, msg))


# ── validation ──────────────────────────────────────────────────────────────

def check_codes(p):
    """One namespace, no duplicates. A code that appears in two of the three
    lists would resolve by whichever table the C side happens to search first,
    which is not a decision this data should be making implicitly."""
    seen = {}
    for listname in ("mapped", "opaque", "unsupported"):
        for rec in p.list(listname):
            code = rec["code"]
            if code in seen:
                die(p, "code %r appears in both .%s and .%s — a code has "
                       "exactly one outcome" % (code, seen[code], listname))
            seen[code] = listname
    if not seen:
        die(p, "no codes at all — check the input document")
    return seen


def check_prefixes(p):
    prefixes = p.list("prefixes")
    if prefixes and p.grammar == "flat":
        die(p, "a flat profile has no prefix mechanism, but .prefixes has %d "
               "rows — they could never be applied" % len(prefixes))
    seen = set()
    for pf in prefixes:
        code = pf["code"]
        if code in seen:
            die(p, "duplicate prefix %r" % code)
        seen.add(code)
        if int(pf["decade"]) not in SI_DECADES:
            die(p, "prefix %r declares decade %d, which has no SI prefix — the "
                   "fold could never discharge it" % (code, int(pf["decade"])))


def native_registry():
    """(alias -> unit enum name, si prefix -> decade, every prefix spelling).

    TWO prefix sets, because the two callers want different things. The reverse
    table needs a DECADE, so it may only ever see the SI prefixes -- a binary
    prefix is a power of two and has no decade to fold into. Target VALIDATION
    has no such restriction: "Ki~B" is a perfectly good native unit expression
    and the C side parses it with the ordinary parser, so refusing it here would
    reject a target the parser accepts, which is the one thing this check must
    not do.
    """
    units = {}
    with open(os.path.join(GENDATA, "units.bvnr"), "rb") as f:
        for u in bvnr_data.load(f.read())["units"]:
            for a in list(u["aliases"]) + [u["symbol"]]:
                units.setdefault(a, u["name"])
    pfx, allpfx, iec = {}, set(), {}
    with open(os.path.join(GENDATA, "prefixes.bvnr"), "rb") as f:
        pdoc = bvnr_data.load(f.read())
        for pf in pdoc["si_prefixes"]:
            for a in list(pf["aliases"]) + [pf["symbol"]]:
                pfx.setdefault(a, int(pf["exp"]))
                allpfx.add(a)
        for pf in pdoc["iec_prefixes"]:
            for a in list(pf["aliases"]) + [pf["symbol"]]:
                allpfx.add(a)
                iec.setdefault(a, "iec_" + pf["name"])
    return units, pfx, allpfx, iec


def check_targets_parse(p, aliases, pfx):
    """Every .bovnar target must be a unit string the native grammar accepts.

    This is checked here, at build time, rather than at first use: a typo in a
    target would otherwise surface as error_unit_illegal on a profile code that
    is perfectly valid, which is the most confusing failure this table can
    produce. The check is textual (the real parse happens in C) but catches the
    whole class of mistakes a hand-edited table makes -- empty targets, stray
    commas, a native alias that does not exist in this build's registry."""
    bad = []
    for m in p.list("mapped"):
        target = m["bovnar"]
        if not target:
            bad.append("  %-14s empty target" % m["code"])
            continue
        # Split the expression into components the way the native parser does,
        # then check each component's head against the registry.
        for comp in re.split(r"[*/·()]", target):
            comp = comp.strip()
            if not comp:
                continue
            # strip an exponent suffix: "^-1", "^2", or a unicode superscript
            comp = re.sub(r"\^[-+]?\d$", "", comp)
            comp = re.sub(r"[¹²³⁴-⁹⁺⁻]+$", "", comp)
            if "~" in comp:
                head, _, tail = comp.partition("~")
                if head not in pfx:
                    bad.append("  %-14s %r: %r is not a prefix"
                               % (m["code"], target, head))
                comp = tail
            if comp and comp not in aliases:
                bad.append("  %-14s %r: %r is not a unit in this registry"
                           % (m["code"], target, comp))
    if bad:
        die(p, "these .bovnar targets do not name anything the native registry "
               "has:\n%s" % "\n".join(bad))


def check_profile_string_bound(p):
    """Refuse to generate a table whose longest PROFILE spelling outgrows
    BVNR_UNIT_STRING_MAX.

    gen_units.py makes exactly this check for the native symbols, and for the
    same reason: bvn_unit_to_string returns -1 without writing a NUL when the
    text does not fit, so a caller that ignores the return and formats the
    buffer with "%s" reads past it. A profile has its own worst case -- the
    "<ns>:" prefix, and codes far longer than any native symbol ("[Amb'a'1'U]"
    is 11 bytes against the longest native 8).

    The bound mirrors the writers in bovnar_profiles.c: "<ns>:", then per
    component a prefix, the code and a signed one-digit exponent, joined by a
    one-byte separator. A flat profile emits one whole code and no separator.
    """
    hdr = os.path.join(REPO, "include", "bovnar.h")
    with open(hdr, encoding="utf-8") as f:
        text = f.read()
    m = re.search(r"#define\s+BVNR_UNIT_STRING_MAX\s+(\d+)", text)
    if not m:
        die(p, "BVNR_UNIT_STRING_MAX is not defined in include/bovnar.h — "
               "nothing to check the bound against")
    declared = int(m.group(1))
    mc = re.search(r"#define\s+BVNR_MAX_UNIT_COMPONENTS\s+(\d+)", text)
    ncomp = int(mc.group(1)) if mc else 8
    pfx_max = max((byte_len(x["code"]) for x in p.list("prefixes")), default=0)
    # An atom only takes a prefix if the profile marks it metric, so the worst
    # case is the longest metric code plus a prefix, against the longest overall.
    codes = [(byte_len(r["code"]), bool(r.get("metric", False)))
             for r in list(p.list("mapped")) + list(p.list("opaque"))]
    code_max = max(
        (n + (pfx_max if metric else 0) for n, metric in codes), default=0)
    ns = len(p.ns) + 1                   # "ucum:"
    if p.grammar == "flat":
        worst = ns + code_max + 1
    else:
        EXP_MAX = 4                      # "-100"
        SEP = 1                          # "."
        worst = ns + ncomp * (code_max + EXP_MAX) + (ncomp - 1) * SEP + 1
    if worst > declared:
        die(p, "the longest profile unit this table can emit needs %d bytes, "
               "but BVNR_UNIT_STRING_MAX in include/bovnar.h is %d. Raise it "
               "(and check every buffer sized from it), or shorten the code "
               "that grew." % (worst, declared))
    return worst, declared


def native_unit_count():
    """How many rows units.bvnr has. Needed only to place the opaque units'
    DENSE TABLE SLOTS after the native ones — their ids come from their own
    block and do not depend on it. gen_units.py owns the same number; the static
    assert in src/utils/bvn_internal_dims.h checks the two agree."""
    with open(os.path.join(GENDATA, "units.bvnr"), "rb") as f:
        return len(bvnr_data.load(f.read())["units"])


def assign_opaque_ids(profiles):
    """Number each profile's opaque units inside ITS OWN block, and lay their
    dense table slots out after the native units.

    Two separate numberings, and keeping them separate is the point. The ID is
    block * BLOCK_SIZE + position, so ids are sparse, self-identifying (the
    leading digits name the vocabulary) and independent -- a profile that grows
    a row shifts nothing outside itself. The SLOT is the row index in the tables
    the library indexes by base unit, which stay dense: one row per defined
    unit, assigned here in registry order.

    A slot is therefore not stable across a profile growing, which is fine: no
    slot is ever serialised or exposed. Only ids are."""
    slot = SLOT_NATIVE_BASE + native_unit_count()
    names, blocks = {}, {}
    for p in profiles:
        if p.block in (BLOCK_NATIVE, BLOCK_CURRENCY) or not (0 < p.block < 100):
            die(p, "block tag %d is not free: 10 is the native units, 90 the "
                   "currencies, and a tag must be two digits" % p.block)
        if p.block in blocks:
            die(p, "block tag %d already belongs to the %r profile"
                   % (p.block, blocks[p.block]))
        blocks[p.block] = p.ns
        rows = p.list("opaque")
        if len(rows) > BLOCK_SIZE:
            die(p, "block %d holds %d ids; this profile has %d opaque units"
                   % (p.block, BLOCK_SIZE, len(rows)))
        p.opaque_first = p.block * BLOCK_SIZE
        p.slot_base = slot
        for n, a in enumerate(rows):
            name = a["name"]
            if name in names:
                die(p, "opaque name %r already used by the %r profile"
                       % (name, names[name]))
            names[name] = p.ns
            if not name.startswith(p.enum_prefix + "_"):
                die(p, "opaque name %r must start with %r so the enum stays "
                       "namespaced" % (name, p.enum_prefix + "_"))
            a["id"] = p.opaque_first + n
            slot += 1
        p.opaque_last = p.opaque_first + len(rows) - 1   # < first when none
    return slot


# ── emitters ────────────────────────────────────────────────────────────────

def rows_by_length(recs, key="code"):
    """Longest first, then by code, so the C suffix matcher is deterministic."""
    return sorted(recs, key=lambda r: (-byte_len(r[key]), r[key]))


def gen_prefix_table(p):
    out = [BANNER % p.data]
    for pf in rows_by_length(p.list("prefixes")):
        out.append("\t{ %-8s %d, %4d },\n"
                   % (c_string_literal(pf["code"]) + ",",
                      byte_len(pf["code"]), int(pf["decade"])))
    return "".join(out)


def gen_atom_table(p):
    """One table for both kinds. A mapped code carries its native target text
    and bu_none; an opaque code carries a NULL target and its own base id.
    Keeping them in one length-sorted table is what makes the longest-suffix
    match correct across both -- two tables would need the matcher to try each
    and compare lengths, which is the same thing done worse."""
    rows = []
    for m in p.list("mapped"):
        rows.append((m["code"], c_string_literal(m["bovnar"]), "bu_none",
                     "true" if m.get("metric", False) else "false"))
    for a in p.list("opaque"):
        rows.append((a["code"], "NULL", "bu_" + a["name"],
                     "true" if a.get("metric", False) else "false"))
    rows.sort(key=lambda r: (-byte_len(r[0]), r[0]))
    out = [BANNER % p.data]
    for code, target, base, metric in rows:
        out.append("\t{ %-16s %2d, %-14s %-18s %s },\n"
                   % (c_string_literal(code) + ",", byte_len(code),
                      target + ",", base + ",", metric))
    return "".join(out)


def gen_unsupported_table(p):
    out = [BANNER % p.data]
    for u in rows_by_length(p.list("unsupported")):
        out.append("\t{ %-24s %2d },  /* %s */\n"
                   % (c_string_literal(u["code"]) + ",",
                      byte_len(u["code"]), u["why"]))
    return "".join(out)


# A target that is a single unmodified atom, optionally prefixed. Anything with
# an operator, a group or an exponent describes a compound and has no single
# code to be written back as.
_COMPOUND = re.compile(r"[*/·()^¹²³⁴⁵⁶⁷⁸⁹⁺⁻]")


def decompose_target(target, units, pfx, iec=None):
    """(unit enum name, prefix decade, iec prefix enum or None), else None.

    `iec` maps a binary prefix spelling to its enumerator name. Pass it for a
    FLAT profile, where a binary-prefixed unit has its own whole code
    ("MebiBYTE") and the reverse row has to be able to name it. An expr profile
    passes None: it reaches a decade by emitting a PREFIX, and there is no
    decimal prefix that means 2^20, so a binary-prefixed unit simply has no
    expr-profile spelling.
    """
    if not target or _COMPOUND.search(target):
        return None
    if "~" in target:
        head, _, tail = target.partition("~")
        if tail not in units:
            return None
        if head in pfx:
            return units[tail], pfx[head], None
        if iec and head in iec:
            return units[tail], 0, iec[head]
        return None
    if target not in units:
        return None
    return units[target], 0, None


def gen_reverse_table(p, units, pfx, iec):
    """base unit -> the code to write it as, and that code's own decade.

    The writer needs the inverse of the transliteration, and computing it by
    re-parsing every target at run time was both slow and wrong: it picked
    whichever row the length-sorted parse table happened to reach first, so
    siemens came out as "mho" rather than "S" and the calorie as "cal_th".

    WHICH CODE WINS DEPENDS ON WHAT THE COMPETING ROWS ARE, and the two grammars
    are not alike here.

    An EXPR profile's competitors are SPELLINGS OF ONE ATOM -- "S" and "mho",
    "cal" and "cal_th", "mo" and "mo_j", "L" and "l" -- and the vocabulary's own
    abbreviation is the short one, so the SHORTEST wins, ties broken
    alphabetically.

    A FLAT profile's competitors are DIFFERENT CODES for one unit, and there
    "shortest" carries no information: every Rec 20 code is two or three bytes,
    so the rule collapses into "alphabetically first" and picks the filler code
    over the mnemonic one. It wrote a joule back as "J55" (Rec 20's WATT SECOND)
    rather than "JOU", a pascal as "C55" (newton per square metre) rather than
    "PAL", a mole as "C34" rather than "MOL", and a short ton as QUDT's bare
    "TON" rather than "TON_SHORT" -- every one of them a code that means the
    right thing and is not the code a reader of that vocabulary expects. So a
    flat profile takes the FIRST row that names the slot: the data files list the
    canonical code first and its aliases after it ("the same unit", "second
    code"), which is an editorial decision already recorded there rather than one
    this function has to reconstruct from the spelling.

    `.reverse = false` on a row overrides both rules by removing it from the
    running altogether. It is for the case neither ordering can see: a code whose
    VALUE is right and whose MEANING is a different quantity, so that writing a
    unit back as it would change what the document says. UCUM's "eq" is worth a
    mole and means an equivalent; its "[oz_ap]" is worth a troy ounce and means
    the apothecary one. Both are correct to accept and wrong to emit. A slot
    whose every row is flagged is a build error -- a unit this profile can read
    and cannot write is a hole, not a preference.

    The decade is what lets a base whose code is itself prefixed be written at
    all. UCUM's "m[Hg]" is a METRE of mercury, i.e. bovnar's mmHg times 10^3, so
    the row carries +3 and the writer emits the prefix for
    (wanted decade - 3): plain mmHg comes out as "mm[Hg]".  Without this those
    bases had no UCUM form at all, and neither did the hectare, whose atom is
    "ar".

    THE KEY DIFFERS BY GRAMMAR, and getting this wrong is how the gram loses
    fifteen of its spellings. An expr profile emits a PREFIX, so one row per base
    plus the prefix mechanism reaches every decade: "g" alone spells the
    microgram as "ug". A flat profile has no prefix to emit -- each decade is a
    SEPARATE CODE, GRM and KGM and MGM and MC all naming the gram -- so there the
    key is (base, decade) and a base contributes as many rows as it has codes.
    Keying a flat profile by base alone leaves whichever code happens to be
    shortest, and every other decade becomes unwritable.
    """
    flat = (p.grammar == "flat")
    best = {}
    seen = set()
    for order_index, m in enumerate(p.list("mapped")):
        d = decompose_target(m["bovnar"], units, pfx, iec if flat else None)
        if d is None:
            continue
        name, decade, iecp = d
        code = m["code"]
        slot = (name, decade, iecp) if flat else name
        seen.add(slot)
        if not m.get("reverse", True):
            continue
        # Flat: declaration order, so the first eligible row keeps the slot.
        # Expr: shortest, then alphabetical.
        key = (order_index,) if flat else (byte_len(code), code)
        if slot not in best or key < best[slot][0]:
            best[slot] = (key, code, decade, bool(m.get("metric", False)), iecp)
    silenced = sorted(str(s) for s in seen - set(best))
    if silenced:
        die(p, "every row naming these units carries `.reverse = false`, so "
               "each is a unit this profile can read and cannot write:\n  %s"
               % "\n  ".join(silenced))
    out = [BANNER % p.data]
    order = sorted(best, key=lambda k: (k[0], k[1], k[2] or "")
                   if flat else (k, 0, ""))
    for slot in order:
        _key, code, decade, metric, iecp = best[slot]
        name = slot[0] if flat else slot
        out.append("\t{ bu_%-18s %-16s %2d, %4d, %-5s %s },\n"
                   % (name + ",", c_string_literal(code) + ",",
                      byte_len(code), decade, ("true" if metric else "false")
                      + ",", iecp or "iec_none"))
    return "".join(out), len(best)


def gen_conv_rows(profiles):
    """si_conv_table rows for the whole opaque block.

    They exist so the table stays well-formed -- bvn_verify_conv_table asserts
    that every non-currency slot's .base equals its index, and a zeroed slot
    fails that. The VALUES are never used: bvn_unit_to_si_factor and
    bvn_unit_dimension_vector refuse an opaque component outright, which is what
    makes these units incommensurable. Filling in 1.0 and a zero dimension
    vector without that refusal would be the bug -- it would say [IU] is a
    dimensionless quantity worth one, i.e. a plain count."""
    out = [BANNER % "the profile data files"]
    for p in profiles:
        for a in p.list("opaque"):
            nm = "bu_" + a["name"]
            out.append("\t[BVN_SLOT_%s(%-18s] = { %-18s 1.0, "
                       "{0, 0, 0, 0, 0, 0, 0}, false, "
                       "0.0, \"1\", \"1\", \"0\", \"1\", true },\n"
                       % (p.cname.upper(), nm + ")", nm + ","))
    return "".join(out)


def gen_policy_rows(profiles):
    """Prefix policy for the opaque block, straight from the profile's metric
    flag.

    Without these the slots keep the array's zero default, which is
    BVN_PFX_DEFAULT -- "any SI prefix" -- and k[arb'U] would parse although UCUM
    forbids a prefix on a non-metric atom."""
    out = [BANNER % "the profile data files"]
    for p in profiles:
        for a in p.list("opaque"):
            out.append("\t[BVN_SLOT_%s(bu_%-18s = %s,\n"
                       % (p.cname.upper(), a["name"] + ")]",
                          "BVN_PFX_DEFAULT" if a.get("metric", False)
                          else "BVN_PFX_NONE"))
    return "".join(out)


def gen_str_rows(profiles):
    """base_unit_str cases. An opaque unit's canonical spelling IS its profile
    code -- it has no native one -- so the symbol here is what the profile
    writer emits after the "<ns>:" prefix."""
    out = [BANNER % "the profile data files"]
    for p in profiles:
        for a in p.list("opaque"):
            out.append("\tcase bu_%-18s return %s;\n"
                       % (a["name"] + ":", c_string_literal(a["code"])))
    return "".join(out)


def gen_enum(profiles, slot_count):
    out = [BANNER % "the profile data files"]
    for p in profiles:
        rows = p.list("opaque")
        if not rows:
            continue
        out.append("\t/* %s */\n" % p.ns)
        for a in rows:
            out.append("\tbu_%-16s = %6d,\n" % (a["name"], int(a["id"])))
    out.append("""
/* The opaque units: profile-only base units with no native spelling and no
 * dimension, so they are commensurable with nothing -- not even with each
 * other. Each profile's live in its own block, one contiguous run from
 * <block>_OPAQUE_FIRST; FIRST > LAST means the profile contributes none.
 *
 * Three things are derived from the runs below and must stay in step, which is
 * why they are emitted together:
 *
 *   _OPAQUE_FIRST/_LAST   the membership test, per profile: two comparisons,
 *                         and the pair also tells the writer which namespace
 *                         owns an opaque unit it has to spell.
 *   BVN_SLOT_<NS>         the row index of an opaque unit in the dense tables
 *                         the library indexes by base unit. Written as
 *                         arithmetic on the enumerator so it can be a
 *                         designated-initialiser index in the generated rows.
 *   BVN_UNIT_SLOT_COUNT   how many rows those tables have in total: bu_none,
 *                         then the native units, then these. */
""")
    for p in profiles:
        u = p.cname.upper()
        out.append("#define BVN_PROFILE_%s_OPAQUE_FIRST %d\n"
                   % (u, p.opaque_first))
        out.append("#define BVN_PROFILE_%s_OPAQUE_LAST  %d\n"
                   % (u, p.opaque_last))
        out.append("#define BVN_PROFILE_%s_OPAQUE_COUNT %d\n"
                   % (u, p.opaque_last - p.opaque_first + 1))
        out.append("#define BVN_PROFILE_%s_SLOT_BASE    %d\n" % (u, p.slot_base))
        out.append("#define BVN_SLOT_%s(b) (BVN_PROFILE_%s_SLOT_BASE + \\\n"
                   "\t((int)(b) - BVN_PROFILE_%s_OPAQUE_FIRST))\n" % (u, u, u))
    total = sum(p.opaque_last - p.opaque_first + 1 for p in profiles)
    out.append("\n#define BVN_PROFILE_OPAQUE_COUNT %d\n" % total)
    out.append("#define BVN_UNIT_SLOT_COUNT      %d\n" % slot_count)
    out.append("""
/* The dense-table slot of any opaque unit, or -1. One ternary chain rather than
 * a lookup table so it stays usable from a header, in a constant expression,
 * and from bvni_unit_slot() without a call. */
""")
    out.append("#define BVN_PROFILE_OPAQUE_SLOT(v) ( \\\n")
    for p in profiles:
        u = p.cname.upper()
        out.append("\t((v) >= BVN_PROFILE_%s_OPAQUE_FIRST && "
                   "(v) <= BVN_PROFILE_%s_OPAQUE_LAST) \\\n"
                   "\t\t? BVN_PROFILE_%s_SLOT_BASE + "
                   "((v) - BVN_PROFILE_%s_OPAQUE_FIRST) : \\\n" % (u, u, u, u))
    out.append("\t-1)\n")
    return "".join(out)


def main(argv):
    gendata = argv[1] if len(argv) > 1 else GENDATA
    for p in PROFILES:
        p.doc = load(os.path.join(gendata, p.data))
        check_codes(p)
        check_prefixes(p)

    units, pfx, allpfx, iec = native_registry()
    for p in PROFILES:
        check_targets_parse(p, set(units), allpfx)

    slot_count = assign_opaque_ids(PROFILES)

    os.makedirs(GENDIR, exist_ok=True)
    bvnr_data.write_if_changed(
        os.path.join(REPO, "include", "bovnar_profiles.gen.h"),
        gen_enum(PROFILES, slot_count))
    bvnr_data.write_if_changed(
        os.path.join(GENDIR, "bovnar_profiles_conv.gen.inc"),
        gen_conv_rows(PROFILES))
    bvnr_data.write_if_changed(
        os.path.join(GENDIR, "bovnar_profiles_policy.gen.inc"),
        gen_policy_rows(PROFILES))
    bvnr_data.write_if_changed(
        os.path.join(GENDIR, "bovnar_profiles_str.gen.inc"),
        gen_str_rows(PROFILES))

    summary = []
    for p in PROFILES:
        worst, cap = check_profile_string_bound(p)
        base = os.path.join(GENDIR, "bovnar_profile_%s_" % p.cname)
        # A flat profile has no prefix mechanism, so it gets no prefix table --
        # emitting an empty one would leave a file nothing includes and nothing
        # in CMake's output list accounts for.
        if p.grammar != "flat":
            bvnr_data.write_if_changed(base + "prefix.gen.inc",
                                       gen_prefix_table(p))
        bvnr_data.write_if_changed(base + "atom.gen.inc", gen_atom_table(p))
        bvnr_data.write_if_changed(base + "unsupported.gen.inc",
                                   gen_unsupported_table(p))
        rev, nrev = gen_reverse_table(p, units, pfx, iec)
        bvnr_data.write_if_changed(base + "reverse.gen.inc", rev)
        nop = len(p.list("opaque"))
        summary.append(
            "  %-8s %s  %3d mapped, %2d opaque%s, %2d unsupported, "
            "%2d prefixes, %3d reverse; longest %d/%d"
            % (p.ns, p.grammar, len(p.list("mapped")), nop,
               (" (%d..%d)" % (p.opaque_first, p.opaque_last)) if nop else "",
               len(p.list("unsupported")), len(p.list("prefixes")), nrev,
               worst, cap))

    print("gen_profiles: %d profile(s), %d dense unit slots\n%s"
          % (len(PROFILES), slot_count, "\n".join(summary)))
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv))
