#!/usr/bin/env python3
"""
gen_currencies.py — generate the C currency catalogue from currencies.bvnr.

Reads the data document with the built-in bvnr_data reader and emits:

    build/generated/bovnar_currency_table.gen.inc   the g_currency_table[] rows

The lookup/index/parse functions and the range macros in bovnar_currency.c stay
hand-written — only the catalogue rows are generated. Records are emitted in
ascending .id order, which is the positional order the O(1) index relies on; the
generator validates that the fiat/crypto blocks are contiguous and the extension
ids are exactly 378/379, so the positional ABI contract cannot silently break.

Like the other generators, it reads the document with the built-in bvnr_data
reader, so it needs only Python — no bovnar library.
"""
import os

REPO = os.path.dirname(os.path.abspath(__file__))
GENDATA = os.path.join(REPO, "src", "gendata")
import bvnr_data  # noqa: E402  -- standalone reader; no libbvnr dependency

FIAT_FIRST, FIAT_LAST = 134, 297
CRYPTO_FIRST, CRYPTO_LAST = 298, 347
EXT_FIRST, EXT_LAST = 378, 379

BANNER = ("/* GENERATED by gen_currencies.py from "
          "src/gendata/currencies.bvnr — DO NOT EDIT. */\n")


def bvnr_c_string(s):
    """Currency codes/names are ASCII; emit a plain C literal, escaping only the
    characters C requires. (No UTF-8 in the catalogue, so no \\xNN splitting.)"""
    if not s.isascii():
        raise SystemExit("non-ASCII in currency field %r — extend the emitter"
                         % s)
    return '"' + s.replace("\\", "\\\\").replace('"', '\\"') + '"'


def load(path):
    with open(path, "rb") as f:
        return bvnr_data.load(f.read())["currencies"]


def validate(curr):
    """Enforce the positional ABI contract and field bounds."""
    ids = [c["id"] for c in curr]
    if ids != sorted(ids):
        raise SystemExit("currencies must be in ascending .id order")
    fiat = [c for c in curr if FIAT_FIRST <= c["id"] <= FIAT_LAST]
    crypto = [c for c in curr if CRYPTO_FIRST <= c["id"] <= CRYPTO_LAST]
    ext = [c for c in curr if EXT_FIRST <= c["id"] <= EXT_LAST]
    if len(fiat) + len(crypto) + len(ext) != len(curr):
        raise SystemExit("a currency .id falls outside the known ranges")
    if [c["id"] for c in fiat] != list(range(FIAT_FIRST, FIAT_FIRST + len(fiat))):
        raise SystemExit("fiat ids must be contiguous from %d" % FIAT_FIRST)
    if [c["id"] for c in crypto] != list(
            range(CRYPTO_FIRST, CRYPTO_FIRST + len(crypto))):
        raise SystemExit("crypto ids must be contiguous from %d" % CRYPTO_FIRST)
    if [c["id"] for c in ext] != list(range(EXT_FIRST, EXT_FIRST + len(ext))):
        raise SystemExit("extension ids must be contiguous from %d" % EXT_FIRST)
    seen = set()
    for c in curr:
        code = c["code"]
        if not (3 <= len(code) <= 4 and code.isupper() and code.isalpha()):
            raise SystemExit("bad currency code %r" % code)
        if code in seen:
            raise SystemExit("duplicate currency code %r" % code)
        seen.add(code)
        if len(code.encode()) >= 5:
            raise SystemExit("code %r overflows char[5]" % code)
        if len(c["name"].encode()) >= 48:
            raise SystemExit("name %r overflows char[48]" % c["name"])
        if c["is_crypto"] != (CRYPTO_FIRST <= c["id"] <= CRYPTO_LAST):
            raise SystemExit("%s: is_crypto disagrees with its id range"
                             % code)
        # The numeric fields were unchecked, so a typo in the .bvnr shipped
        # silently as wrong money data: .numeric_code = 8000 for UGX generated a
        # table with 8000 in it and the whole build stayed green, and a value
        # above 65535 truncates into the uint16_t field with nothing but a
        # -Woverflow (off unless BVNR_WERROR). Bound them here, where the input
        # is still readable, rather than hoping a warning is noticed.
        num = c["numeric_code"]
        if not (0 <= num <= 65535):
            raise SystemExit("%s: numeric_code %d does not fit uint16_t"
                             % (code, num))
        if not c["is_crypto"] and num == 0:
            raise SystemExit("%s: fiat currencies need an ISO 4217 numeric code"
                             % code)
        if c["is_crypto"] and num != 0:
            raise SystemExit("%s: crypto assets carry no ISO numeric code, got %d"
                             % (code, num))
        minor = c["minor_unit"]
        # The field is a uint8_t. ISO 4217 tops out at 4 (CLF); crypto goes much
        # further -- 18 for ether-style tokens and 24 for NEAR, whose smallest
        # unit is the yoctoNEAR. 38 leaves room for a wider token without
        # admitting a digit-slip like 250.
        if not (0 <= minor <= 38):
            raise SystemExit("%s: minor_unit %d out of range 0..38"
                             % (code, minor))
        if not c["is_crypto"] and minor > 4:
            raise SystemExit("%s: ISO 4217 minor units go up to 4, got %d"
                             % (code, minor))
    # A numeric code identifies a currency, so a repeat is either a typo or a
    # deliberate succession (XCG inherits ANG's 532). Allow at most one pair.
    numbers = {}
    for c in curr:
        if c["numeric_code"] == 0:
            continue
        numbers.setdefault(c["numeric_code"], []).append(c["code"])
    shared = {n: v for n, v in numbers.items() if len(v) > 1}
    if len(shared) > 1 or any(len(v) > 2 for v in shared.values()):
        raise SystemExit("unexpected duplicate ISO numeric codes: %r" % shared)
    return fiat, crypto, ext


def gen_table(curr):
    # Emit the row counts the table actually has, so bovnar_currency.c can
    # _Static_assert them against the BVN_CURRENCY_* range constants. Without
    # that cross-check, widening a range in the header without adding a row here
    # builds with no warning and exposes the extra slot as a valid currency with
    # an empty code and name.
    out = [BANNER]
    out.append("#define BVNR_CURRENCY_ROWS_FIAT   %d\n"
               % len([c for c in curr if FIAT_FIRST <= c["id"] <= FIAT_LAST]))
    out.append("#define BVNR_CURRENCY_ROWS_CRYPTO %d\n"
               % len([c for c in curr if CRYPTO_FIRST <= c["id"] <= CRYPTO_LAST]))
    out.append("#define BVNR_CURRENCY_ROWS_EXT    %d\n\n"
               % len([c for c in curr if EXT_FIRST <= c["id"] <= EXT_LAST]))
    for c in curr:
        out.append("  { %-7s %4d, %2d, %-7s %s },\n" % (
            bvnr_c_string(c["code"]) + ",",
            c["numeric_code"],
            c["minor_unit"],
            ("true," if c["is_crypto"] else "false,"),
            bvnr_c_string(c["name"]),
        ))
    return "".join(out)


def main():
    path = os.path.join(GENDATA, "currencies.bvnr")
    curr = load(path)
    fiat, crypto, ext = validate(curr)
    gendir = os.environ.get("BVNR_GENERATED_DIR",
                            os.path.join(REPO, "build", "generated"))
    os.makedirs(gendir, exist_ok=True)
    dest = os.path.join(gendir, "bovnar_currency_table.gen.inc")
    with open(dest, "w", encoding="utf-8") as f:
        f.write(gen_table(curr))
    print("generated %d currencies (%d fiat, %d crypto, %d ext) -> %s"
          % (len(curr), len(fiat), len(crypto), len(ext), dest))


if __name__ == "__main__":
    main()
