#!/usr/bin/env python3
"""
gen_ucum.py — generate the C UCUM-profile tables from src/gendata/ucum.bvnr.

Reads the document with the built-in bvnr_data reader (no libbvnr) and emits:

    include/bovnar_ucum.gen.h                enum body: bu_<name> = <id>, for the
                                             UCUM arbitrary units, plus the
                                             FIRST/LAST bracketing macros
    <gendir>/bovnar_ucum_prefix.gen.inc      UCUM prefix spelling -> decade
    <gendir>/bovnar_ucum_atom.gen.inc        atom -> native target / arbitrary id
    <gendir>/bovnar_ucum_unsupported.gen.inc atoms that are known but refused
    <gendir>/bovnar_ucum_reverse.gen.inc     base unit -> the atom to write it as
    <gendir>/bovnar_ucum_conv.gen.inc        si_conv_table rows for the block
    <gendir>/bovnar_ucum_policy.gen.inc      prefix policy for the block
    <gendir>/bovnar_ucum_str.gen.inc         base_unit_str cases for the block

The native target of a mapped atom is stored as the SOURCE TEXT of a native unit
expression, not as a pre-baked value_unit_t: the C side parses it once, lazily,
with the same bvn_parse_unit every document goes through. That keeps this
generator from needing a second, divergent implementation of the unit grammar in
Python -- which is exactly how a generated table starts disagreeing with the
parser it feeds.

The tables are ordered by DESCENDING code byte length, so the C matcher can take
the longest atom that is a suffix of what it is looking at, the same rule the
native bu_table uses.

Usage:
    [BVNR_GENERATED_DIR=dir] python3 gen_ucum.py [path/to/ucum.bvnr]
"""
import os
import re
import sys

REPO = os.path.dirname(os.path.abspath(__file__))
GENDATA = os.path.join(REPO, "src", "gendata")
GENDIR = os.environ.get("BVNR_GENERATED_DIR",
                        os.path.join(REPO, "build", "generated"))
import bvnr_data  # noqa: E402

BANNER = ("/* GENERATED by gen_ucum.py from src/gendata/ucum.bvnr — "
          "DO NOT EDIT. */\n")

# The decades that have an SI prefix. The fold in bovnar_ucum.c can only
# discharge a residual scale into one of these, so a mapping whose target would
# need any other decade is a build error rather than a runtime surprise.
SI_DECADES = {0, 1, 2, 3, 6, 9, 12, 15, 18, 21, 24, 27, 30,
              -1, -2, -3, -6, -9, -12, -15, -18, -21, -24, -27, -30}


def c_string_literal(s):
    """Encode a Python str as one or more adjacent C string literals.

    Byte-for-byte the same rule as gen_units.py: every non-printable/non-ASCII
    byte becomes a \\xNN escape, and a run of escapes is closed before the next
    plain byte so a following hex digit is never absorbed into the escape."""
    chunks = []
    buf = ""
    buf_esc = None
    for b in s.encode("utf-8"):
        printable = 0x20 <= b < 0x7f and b not in (0x22, 0x5c)
        esc = not printable
        if buf and buf_esc != esc:
            chunks.append((buf_esc, buf))
            buf = ""
        buf += ("\\x%02x" % b) if esc else chr(b)
        buf_esc = esc
    if buf:
        chunks.append((buf_esc, buf))
    if not chunks:
        return '""'
    return " ".join('"%s"' % text for _, text in chunks)


def byte_len(s):
    return len(s.encode("utf-8"))


def load(path):
    with open(path, "rb") as f:
        return bvnr_data.load(f.read())


def check_codes(doc):
    """One namespace, no duplicates. An atom that appears in two of the three
    lists would resolve by whichever table the C side happens to search first,
    which is not a decision this data should be making implicitly."""
    seen = {}
    for listname in ("mapped", "arbitrary", "unsupported"):
        for rec in doc.get(listname, []):
            code = rec["code"]
            if code in seen:
                raise SystemExit(
                    "gen_ucum: atom %r appears in both .%s and .%s — an atom "
                    "has exactly one outcome" % (code, seen[code], listname))
            seen[code] = listname
    if not seen:
        raise SystemExit("gen_ucum: no atoms at all — check the input document")
    return seen


def check_prefixes(prefixes):
    seen = set()
    for p in prefixes:
        code = p["code"]
        if code in seen:
            raise SystemExit("gen_ucum: duplicate prefix %r" % code)
        seen.add(code)
        if int(p["decade"]) not in SI_DECADES:
            raise SystemExit(
                "gen_ucum: prefix %r declares decade %d, which has no SI prefix "
                "— the fold could never discharge it"
                % (code, int(p["decade"])))


def check_arbitrary_ids(arb, units_path):
    """The arbitrary block must start exactly one past the last native unit and
    run without gaps.

    The tables sized by BVN_VALUE_BASE_UNIT_COUNT are indexed BY the enum value,
    so a gap is a hole of zeroed rows that reads as a valid unit, and an overlap
    with a native id is two units answering to one number."""
    if not arb:
        return 0, 0
    native_max = 0
    with open(units_path, "rb") as f:
        for u in bvnr_data.load(f.read())["units"]:
            native_max = max(native_max, int(u["id"]))
    cur_path = os.path.join(os.path.dirname(units_path), "currencies.bvnr")
    if os.path.exists(cur_path):
        with open(cur_path, "rb") as f:
            for c in bvnr_data.load(f.read())["currencies"]:
                native_max = max(native_max, int(c["id"]))
    ids = [int(a["id"]) for a in arb]
    expect = native_max + 1
    for i, got in enumerate(ids):
        if got != expect + i:
            raise SystemExit(
                "gen_ucum: arbitrary id %d for %r breaks the run — the block "
                "must start at %d (one past the last native id) and be "
                "contiguous" % (got, arb[i]["code"], expect))
    names = set()
    for a in arb:
        if a["name"] in names:
            raise SystemExit("gen_ucum: duplicate arbitrary name %r" % a["name"])
        names.add(a["name"])
    return ids[0], ids[-1]


def check_targets_parse(mapped):
    """Every .bovnar target must be a unit string the native grammar accepts.

    This is checked here, at build time, rather than at first use: a typo in a
    target would otherwise surface as error_unit_illegal on a UCUM code that is
    perfectly valid, which is the most confusing failure this table can produce.
    The check is textual (the real parse happens in C) but catches the whole
    class of mistakes a hand-edited table makes -- empty targets, stray commas,
    a native alias that does not exist in this build's registry."""
    aliases = set()
    with open(os.path.join(GENDATA, "units.bvnr"), "rb") as f:
        for u in bvnr_data.load(f.read())["units"]:
            aliases.update(u["aliases"])
            aliases.add(u["symbol"])
    pfx = set()
    with open(os.path.join(GENDATA, "prefixes.bvnr"), "rb") as f:
        pdoc = bvnr_data.load(f.read())
        for system in ("si_prefixes", "iec_prefixes"):
            for p in pdoc[system]:
                pfx.update(p["aliases"])
                pfx.add(p["symbol"])
    bad = []
    for m in mapped:
        target = m["bovnar"]
        if not target:
            bad.append("  %-14s empty target" % m["code"])
            continue
        # Split the expression into components the way the native parser does,
        # then check each component's head against the registry.
        for comp in re.split(r"[*/·()]", target):
            comp = comp.strip()
            if not comp:
                continue
            # strip an exponent suffix: "^-1", "^2", or a unicode superscript
            comp = re.sub(r"\^[-+]?\d$", "", comp)
            comp = re.sub(r"[¹²³⁴-⁹⁺⁻]+$",
                          "", comp)
            if "~" in comp:
                head, _, tail = comp.partition("~")
                if head not in pfx:
                    bad.append("  %-14s %r: %r is not a prefix"
                               % (m["code"], target, head))
                comp = tail
            if comp and comp not in aliases:
                bad.append("  %-14s %r: %r is not a unit in this registry"
                           % (m["code"], target, comp))
    if bad:
        raise SystemExit(
            "gen_ucum: these .bovnar targets do not name anything the native "
            "registry has:\n%s" % "\n".join(bad))


def rows_by_length(recs, key="code"):
    """Longest first, then by code, so the C suffix matcher is deterministic."""
    return sorted(recs, key=lambda r: (-byte_len(r[key]), r[key]))


def gen_prefix_table(prefixes):
    out = [BANNER]
    for p in rows_by_length(prefixes):
        out.append("\t{ %-8s %d, %4d },\n"
                   % (c_string_literal(p["code"]) + ",",
                      byte_len(p["code"]), int(p["decade"])))
    return "".join(out)


def gen_atom_table(mapped, arbitrary):
    """One table for both kinds. A mapped atom carries its native target text
    and bu_none; an arbitrary atom carries a NULL target and its own base id.
    Keeping them in one length-sorted table is what makes the longest-suffix
    match correct across both -- two tables would need the matcher to try each
    and compare lengths, which is the same thing done worse."""
    rows = []
    for m in mapped:
        rows.append((m["code"], c_string_literal(m["bovnar"]), "bu_none",
                     "true" if m["metric"] else "false"))
    for a in arbitrary:
        rows.append((a["code"], "NULL", "bu_" + a["name"],
                     "true" if a["metric"] else "false"))
    rows.sort(key=lambda r: (-byte_len(r[0]), r[0]))
    out = [BANNER]
    for code, target, base, metric in rows:
        out.append("\t{ %-16s %2d, %-14s %-18s %s },\n"
                   % (c_string_literal(code) + ",", byte_len(code),
                      target + ",", base + ",", metric))
    return "".join(out)


def gen_unsupported_table(unsupported):
    out = [BANNER]
    for u in rows_by_length(unsupported):
        out.append("\t{ %-24s %2d },  /* %s */\n"
                   % (c_string_literal(u["code"]) + ",",
                      byte_len(u["code"]), u["why"]))
    return "".join(out)


def _registry():
    """(alias -> unit enum name, prefix alias -> decade) for this build."""
    units = {}
    with open(os.path.join(GENDATA, "units.bvnr"), "rb") as f:
        for u in bvnr_data.load(f.read())["units"]:
            for a in list(u["aliases"]) + [u["symbol"]]:
                units.setdefault(a, u["name"])
    pfx = {}
    with open(os.path.join(GENDATA, "prefixes.bvnr"), "rb") as f:
        pdoc = bvnr_data.load(f.read())
        for p in pdoc["si_prefixes"]:            # IEC prefixes are excluded on
            for a in list(p["aliases"]) + [p["symbol"]]:   # purpose: a binary
                pfx.setdefault(a, int(p["exp"]))           # prefix is not a decade
    return units, pfx


# A target that is a single unmodified atom, optionally prefixed. Anything with
# an operator, a group or an exponent describes a compound and has no single
# UCUM atom to be written back as.
_COMPOUND = re.compile(r"[*/·()^¹²³⁴⁵⁶⁷⁸⁹⁺⁻]")


def decompose_target(target, units, pfx):
    """(unit enum name, prefix decade) for a single-atom target, else None."""
    if not target or _COMPOUND.search(target):
        return None
    if "~" in target:
        head, _, tail = target.partition("~")
        if head not in pfx or tail not in units:
            return None
        return units[tail], pfx[head]
    if target not in units:
        return None
    return units[target], 0


def gen_reverse_table(mapped):
    """base unit -> the UCUM atom to write it as, and that atom's own decade.

    bvn_unit_to_ucum needs the inverse of the transliteration, and computing it
    by re-parsing every target at run time was both slow and wrong: it picked
    whichever row the length-sorted parse table happened to reach first, so
    siemens came out as "mho" rather than "S" and the calorie as "cal_th".

    Two rules make the choice deterministic and the result the code a reader
    expects. Among the atoms naming one base, the SHORTEST wins, ties broken
    alphabetically -- which is "S" over "mho", "cal" over "cal_th", "mo" over
    "mo_j", "a" over "a_j", "L" over "l".

    The decade is what lets a base whose UCUM atom is itself prefixed be written
    at all. UCUM's "m[Hg]" is a METRE of mercury, i.e. bovnar's mmHg times 10^3,
    so the row carries +3 and the writer emits the UCUM prefix for
    (wanted decade - 3): plain mmHg comes out as "mm[Hg]". Without this those
    bases had no UCUM form at all, and neither did the hectare, whose atom is
    "ar".
    """
    units, pfx = _registry()
    best = {}
    for m in mapped:
        d = decompose_target(m["bovnar"], units, pfx)
        if d is None:
            continue
        name, decade = d
        code = m["code"]
        key = (byte_len(code), code)
        if name not in best or key < best[name][0]:
            best[name] = (key, code, decade, bool(m["metric"]))
    out = [BANNER]
    for name in sorted(best):
        _key, code, decade, metric = best[name]
        out.append("\t{ bu_%-18s %-16s %2d, %4d, %s },\n"
                   % (name + ",", c_string_literal(code) + ",",
                      byte_len(code), decade, "true" if metric else "false"))
    return "".join(out)


def gen_conv_rows(arbitrary):
    """si_conv_table rows for the arbitrary block.

    They exist so the table stays well-formed -- bvn_verify_conv_table asserts
    that every non-currency slot's .base equals its index, and a zeroed slot
    fails that. The VALUES are never used: bvn_unit_to_si_factor and
    bvn_unit_dimension_vector refuse an arbitrary component outright, which is
    what makes these units incommensurable. Filling in 1.0 and a zero dimension
    vector without that refusal would be the bug -- it would say [IU] is a
    dimensionless quantity worth one, i.e. a plain count."""
    out = [BANNER]
    for a in arbitrary:
        nm = "bu_" + a["name"]
        out.append("\t[%-18s] = { %-18s 1.0, {0, 0, 0, 0, 0, 0, 0}, false, 0.0, "
                   "\"1\", \"1\", \"0\", \"1\", true },\n" % (nm, nm + ","))
    return "".join(out)


def gen_policy_rows(arbitrary):
    """Prefix policy for the arbitrary block, straight from UCUM's metric flag.

    Without these the slots keep the array's zero default, which is
    BVN_PFX_DEFAULT -- "any SI prefix" -- and k[arb'U] would parse although UCUM
    forbids a prefix on a non-metric atom."""
    out = [BANNER]
    for a in arbitrary:
        out.append("\t[bu_%-18s = %s,\n"
                   % (a["name"] + "]",
                      "BVN_PFX_DEFAULT" if a["metric"] else "BVN_PFX_NONE"))
    return "".join(out)


def gen_str_rows(arbitrary):
    """base_unit_str cases. An arbitrary unit's canonical spelling IS its UCUM
    code -- it has no native one -- so the symbol here is what the profile
    writer emits after the "ucum:" prefix."""
    out = [BANNER]
    for a in arbitrary:
        out.append("\tcase bu_%-18s return %s;\n"
                   % (a["name"] + ":", c_string_literal(a["code"])))
    return "".join(out)


def gen_enum(arbitrary, first, last):
    out = [BANNER]
    for a in arbitrary:
        out.append("\tbu_%-16s = %3d,\n" % (a["name"], int(a["id"])))
    out.append("\n")
    out.append("/* The arbitrary block, bracketed for the two-comparison "
               "membership test in\n"
               " * bvni_is_arbitrary(). Contiguity is enforced by gen_ucum.py. "
               "*/\n")
    out.append("#define BVN_UCUM_ARBITRARY_FIRST %d\n" % first)
    out.append("#define BVN_UCUM_ARBITRARY_LAST  %d\n" % last)
    out.append("#define BVN_UCUM_ARBITRARY_COUNT %d\n" % (last - first + 1))
    return "".join(out)


def main(argv):
    path = argv[1] if len(argv) > 1 else os.path.join(GENDATA, "ucum.bvnr")
    doc = load(path)
    mapped = doc.get("mapped", [])
    arbitrary = doc.get("arbitrary", [])
    unsupported = doc.get("unsupported", [])
    prefixes = doc.get("prefixes", [])

    check_codes(doc)
    check_prefixes(prefixes)
    check_targets_parse(mapped)
    first, last = check_arbitrary_ids(
        arbitrary, os.path.join(os.path.dirname(os.path.abspath(path)),
                                "units.bvnr"))

    os.makedirs(GENDIR, exist_ok=True)
    bvnr_data.write_if_changed(
        os.path.join(REPO, "include", "bovnar_ucum.gen.h"),
        gen_enum(arbitrary, first, last))
    bvnr_data.write_if_changed(
        os.path.join(GENDIR, "bovnar_ucum_prefix.gen.inc"),
        gen_prefix_table(prefixes))
    bvnr_data.write_if_changed(
        os.path.join(GENDIR, "bovnar_ucum_atom.gen.inc"),
        gen_atom_table(mapped, arbitrary))
    bvnr_data.write_if_changed(
        os.path.join(GENDIR, "bovnar_ucum_unsupported.gen.inc"),
        gen_unsupported_table(unsupported))
    bvnr_data.write_if_changed(
        os.path.join(GENDIR, "bovnar_ucum_conv.gen.inc"),
        gen_conv_rows(arbitrary))
    bvnr_data.write_if_changed(
        os.path.join(GENDIR, "bovnar_ucum_policy.gen.inc"),
        gen_policy_rows(arbitrary))
    bvnr_data.write_if_changed(
        os.path.join(GENDIR, "bovnar_ucum_str.gen.inc"),
        gen_str_rows(arbitrary))
    bvnr_data.write_if_changed(
        os.path.join(GENDIR, "bovnar_ucum_reverse.gen.inc"),
        gen_reverse_table(mapped))

    units, pfx = _registry()
    nrev = len({decompose_target(m["bovnar"], units, pfx)[0]
                for m in mapped
                if decompose_target(m["bovnar"], units, pfx)})
    print("gen_ucum: %d mapped, %d arbitrary (%d..%d), %d unsupported, "
          "%d prefixes, %d reverse rows"
          % (len(mapped), len(arbitrary), first, last,
             len(unsupported), len(prefixes), nrev))
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv))
