#!/usr/bin/env python3
"""
gen_currencies.py — generate the C currency catalogue from currencies.bvnr.

Reads the data document with the built-in bvnr_data reader and emits:

    build/generated/bovnar_currency_table.gen.inc   the g_currency_table[] rows

The lookup/index/parse functions and the range macros in bovnar_currency.c stay
hand-written — only the catalogue rows are generated. Records are emitted in
ascending .id order, which is the positional order the O(1) index relies on; the
generator validates that the fiat/crypto blocks are contiguous and the extension
ids are exactly 378/379, so the positional ABI contract cannot silently break.

Like the other generators, it reads the document with the built-in bvnr_data
reader, so it needs only Python — no bovnar library.
"""
import os

REPO = os.path.dirname(os.path.abspath(__file__))
GENDATA = os.path.join(REPO, "src", "gendata")
import bvnr_data  # noqa: E402  -- standalone reader; no libbvnr dependency

FIAT_FIRST, FIAT_LAST = 134, 297
CRYPTO_FIRST, CRYPTO_LAST = 298, 347
EXT_FIRST, EXT_LAST = 378, 379

BANNER = ("/* GENERATED by gen_currencies.py from "
          "src/gendata/currencies.bvnr — DO NOT EDIT. */\n")


def bvnr_c_string(s):
    """Currency codes/names are ASCII; emit a plain C literal, escaping only the
    characters C requires. (No UTF-8 in the catalogue, so no \\xNN splitting.)"""
    if not s.isascii():
        raise SystemExit("non-ASCII in currency field %r — extend the emitter"
                         % s)
    return '"' + s.replace("\\", "\\\\").replace('"', '\\"') + '"'


def load(path):
    with open(path, "rb") as f:
        return bvnr_data.load(f.read())["currencies"]


def validate(curr):
    """Enforce the positional ABI contract and field bounds."""
    ids = [c["id"] for c in curr]
    if ids != sorted(ids):
        raise SystemExit("currencies must be in ascending .id order")
    fiat = [c for c in curr if FIAT_FIRST <= c["id"] <= FIAT_LAST]
    crypto = [c for c in curr if CRYPTO_FIRST <= c["id"] <= CRYPTO_LAST]
    ext = [c for c in curr if EXT_FIRST <= c["id"] <= EXT_LAST]
    if len(fiat) + len(crypto) + len(ext) != len(curr):
        raise SystemExit("a currency .id falls outside the known ranges")
    if [c["id"] for c in fiat] != list(range(FIAT_FIRST, FIAT_FIRST + len(fiat))):
        raise SystemExit("fiat ids must be contiguous from %d" % FIAT_FIRST)
    if [c["id"] for c in crypto] != list(
            range(CRYPTO_FIRST, CRYPTO_FIRST + len(crypto))):
        raise SystemExit("crypto ids must be contiguous from %d" % CRYPTO_FIRST)
    if [c["id"] for c in ext] != list(range(EXT_FIRST, EXT_FIRST + len(ext))):
        raise SystemExit("extension ids must be contiguous from %d" % EXT_FIRST)
    seen = set()
    for c in curr:
        code = c["code"]
        if not (3 <= len(code) <= 4 and code.isupper() and code.isalpha()):
            raise SystemExit("bad currency code %r" % code)
        if code in seen:
            raise SystemExit("duplicate currency code %r" % code)
        seen.add(code)
        if len(code.encode()) >= 5:
            raise SystemExit("code %r overflows char[5]" % code)
        if len(c["name"].encode()) >= 48:
            raise SystemExit("name %r overflows char[48]" % c["name"])
        if c["is_crypto"] != (CRYPTO_FIRST <= c["id"] <= CRYPTO_LAST):
            raise SystemExit("%s: is_crypto disagrees with its id range"
                             % code)
    return fiat, crypto, ext


def gen_table(curr):
    out = [BANNER]
    for c in curr:
        out.append("  { %-7s %4d, %2d, %-7s %s },\n" % (
            bvnr_c_string(c["code"]) + ",",
            c["numeric_code"],
            c["minor_unit"],
            ("true," if c["is_crypto"] else "false,"),
            bvnr_c_string(c["name"]),
        ))
    return "".join(out)


def main():
    path = os.path.join(GENDATA, "currencies.bvnr")
    curr = load(path)
    fiat, crypto, ext = validate(curr)
    gendir = os.environ.get("BVNR_GENERATED_DIR",
                            os.path.join(REPO, "build", "generated"))
    os.makedirs(gendir, exist_ok=True)
    dest = os.path.join(gendir, "bovnar_currency_table.gen.inc")
    with open(dest, "w", encoding="utf-8") as f:
        f.write(gen_table(curr))
    print("generated %d currencies (%d fiat, %d crypto, %d ext) -> %s"
          % (len(curr), len(fiat), len(crypto), len(ext), dest))


if __name__ == "__main__":
    main()
