#!/usr/bin/env python3
"""
gen_units.py — generate the C unit tables from src/gendata/units.bvnr.

Reads the document with the built-in bvnr_data reader (no libbvnr) and emits:

    include/bovnar_units.gen.h               enum body: bu_<name> = <id>,
    <gendir>/bovnar_si_conv_table.gen.inc    si_conv_table rows
    <gendir>/bovnar_base_unit_str.gen.inc    base_unit_str() switch cases
    <gendir>/bovnar_bu_table.gen.inc         bu_table rows (aliases, byte lengths)
    <gendir>/bovnar_bu_index.gen.inc         bu_first_for_len / bu_max_len
    <gendir>/bovnar_prefix_policy.gen.inc    per-unit prefix-policy entries

The public *.gen.h enum header goes to include/ (committed). The *.gen.inc
snippets are build artifacts: <gendir> is $BVNR_GENERATED_DIR (set by CMake,
default build/generated). A host-side step — needs only Python 3.

Usage:
    [BVNR_GENERATED_DIR=dir] python3 gen_units.py [path/to/units.bvnr]
"""
import sys
import os

REPO = os.path.dirname(os.path.abspath(__file__))   # this script lives at repo root
GENDATA = os.path.join(REPO, "src", "gendata")       # the *.bvnr source of truth
# Generated .inc snippets go here (a build dir, not committed); overridable so
# CMake can point at $<BINARY_DIR>/generated. The public *.gen.h enum headers
# stay in include/.
GENDIR = os.environ.get("BVNR_GENERATED_DIR",
                        os.path.join(REPO, "build", "generated"))
import bvnr_data  # noqa: E402  -- standalone reader; no libbvnr dependency

# SI base dimensions, in the canonical order of the dims[] vector the C tables
# use. The data document names them (e.g. .dims = {.length = 1; .time = -2;})
# and omits the zeros; the generator expands to the full ordered vector.
DIM_NAMES = ["length", "mass", "time", "current",
             "temperature", "amount", "luminosity"]
DIM_INDEX = {name: i for i, name in enumerate(DIM_NAMES)}


def dims_to_vector(dims, unitname):
    """Accept a named struct {.length=1; .time=-2;} (zeros omitted) or a bare
    7-element list, and return the ordered [len, mass, time, ...] vector."""
    vec = [0] * len(DIM_NAMES)
    if isinstance(dims, list):
        if len(dims) != len(DIM_NAMES):
            raise SystemExit("%s: dims list must have %d entries"
                             % (unitname, len(DIM_NAMES)))
        return list(dims)
    for name, val in dims.items():
        if name not in DIM_INDEX:
            raise SystemExit("%s: unknown dimension %r (expected one of %s)"
                             % (unitname, name, ", ".join(DIM_NAMES)))
        vec[DIM_INDEX[name]] = val
    return vec


# prefix policy symbol -> generated C enumerator
POLICY = {
    "default": "BVN_PFX_DEFAULT",
    "info":    "BVN_PFX_INFO",
    "german":  "BVN_PFX_GERMAN",
    "ratio":   "BVN_PFX_RATIO",
    "none":    "BVN_PFX_NONE",
}

BANNER = ("/* GENERATED by gen_units.py from src/gendata/units.bvnr — "
          "DO NOT EDIT. */\n")


def c_string_literal(s):
    """Encode a Python str as one or more adjacent C string literals.

    Every non-printable / non-ASCII byte becomes a \\xNN escape; a run of
    escapes is closed before the next plain byte so that a following hex digit
    (or a letter like the "C" in "°C") is never absorbed into the escape.
    Matches the hand-written style in bovnar_utils.c, e.g.  "\\xc2\\xb0" "C".
    """
    chunks = []          # list of (is_escape, text)
    buf = ""
    buf_esc = None
    for b in s.encode("utf-8"):
        printable = 0x20 <= b < 0x7f and b not in (0x22, 0x5c)  # not " or \
        esc = not printable
        if buf and buf_esc != esc:
            chunks.append((buf_esc, buf))
            buf = ""
        buf += ("\\x%02x" % b) if esc else chr(b)
        buf_esc = esc
    if buf:
        chunks.append((buf_esc, buf))
    if not chunks:
        return '""'
    return " ".join('"%s"' % text for _, text in chunks)


def c_double_literal(x):
    """Shortest decimal that round-trips to the same IEEE-754 double."""
    r = repr(float(x))
    # repr() already yields '.0'/'e' forms; guarantee it reads as a double.
    if "." not in r and "e" not in r and "E" not in r and "inf" not in r:
        r += ".0"
    return r


def byte_len(s):
    return len(s.encode("utf-8"))


def load_units(path):
    with open(path, "rb") as f:
        doc = bvnr_data.load(f.read())
    units = doc["units"]
    # Validate the stable-id contract up front: unique, positive, no dups.
    seen = {}
    for u in units:
        i = u["id"]
        if i in seen:
            raise SystemExit("duplicate id %d (%s and %s)"
                             % (i, seen[i], u["name"]))
        seen[i] = u["name"]
    return units


def gen_enum(units):
    out = [BANNER]
    for u in units:
        out.append("\tbu_%-12s = %3d,\n" % (u["name"], u["id"]))
    return "".join(out)


# A decimal carrying this many significant digits is the repr of a double, not a
# deliberately written exact value — i.e. it is a ROUNDED approximation of the
# unit's true factor. Recovering a "exact" rational from it would bake that
# rounding error into a conversion the library advertises as lossless, so such a
# unit must state the truth explicitly (see check_exactness below).
ROUNDED_DECIMAL_SIGDIGITS = 16


def _sig_digits(lit):
    from decimal import Decimal
    return len(Decimal(lit).normalize().as_tuple().digits)


def check_exactness(units):
    """Refuse to generate a conversion table that silently claims a rounded
    double is an exact rational.

    The table's whole purpose is lossless conversion, so every factor/offset must
    be one of three things, stated in the source rather than inferred:

      * a short exact decimal        — `.factor = 0.0254;` (inch, exact by
                                       definition), recovered exactly below;
      * a non-terminating rational   — `.factor_num`/`.factor_den` (e.g. °F's
                                       slope 5/9), which no decimal can express;
      * genuinely irrational         — `.exact = false` (π-based units), rejected
                                       at conversion time.

    A 16+ digit decimal with none of those markers means somebody pasted a double
    repr and the true value was lost. That is exactly how °R (5/9) once shipped a
    wrong "exact" answer while °F, hand-overridden, correctly refused."""
    bad = []
    for u in units:
        if not bool(u.get("exact", True)):
            continue                      # irrational: never claimed exact
        for key in ("factor", "offset"):
            if u.get(key + "_num") is not None and u.get(key + "_den") is not None:
                continue                  # truth stated explicitly
            lit = c_double_literal(u[key])
            if _sig_digits(lit) >= ROUNDED_DECIMAL_SIGDIGITS:
                bad.append("  %-16s .%s = %s  (%d significant digits)"
                           % (u["name"], key, lit, _sig_digits(lit)))
    if bad:
        raise SystemExit(
            "gen_units: these units declare a %d+ digit decimal — the repr of a "
            "double, i.e. a rounded value — but claim an exact rational:\n%s\n\n"
            "Give each one either .%s_num/.%s_den with the true rational, or "
            ".exact = false if the true value is irrational."
            % (ROUNDED_DECIMAL_SIGDIGITS, "\n".join(bad), "<factor|offset>",
               "<factor|offset>"))


def exact_rational(u, key):
    """Return the exact (numerator, denominator) rational for a unit's `factor`
    or `offset`, reduced to lowest terms.

    An explicit .<key>_num / .<key>_den override in the source wins — use it for
    a factor whose true value is a NON-terminating rational (e.g. fahrenheit's
    slope 5/9, offset 45967/180), which the stored decimal only approximates.
    Otherwise the rational is recovered exactly from the declared decimal
    (Decimal keeps every written digit, incl. exponent form), so a conversion
    introduces no error beyond the library's own declared factor. Units whose
    factor is genuinely irrational (π-based angles) carry .exact = false and are
    reported inexact at conversion time regardless of what this returns.

    check_exactness has already rejected the dangerous middle case — a rounded
    double repr presented as an exact decimal — so the fallback below is only
    ever reached for a value the source really does state exactly."""
    from fractions import Fraction
    from decimal import Decimal
    n = u.get(key + "_num")
    d = u.get(key + "_den")
    if n is not None and d is not None:
        return Fraction(int(n), int(d))
    return Fraction(Decimal(c_double_literal(u[key])))


def gen_conv_table(units):
    check_exactness(units)
    out = [BANNER]
    for u in units:
        nm = "bu_" + u["name"]
        dims = ", ".join("%2d" % d for d in dims_to_vector(u["dims"], u["name"]))
        fr = exact_rational(u, "factor")
        of = exact_rational(u, "offset")
        exact = bool(u.get("exact", True))
        out.append(
            "\t[%-14s] = { %-14s %-22s {%s}, %-6s %-14s "
            "\"%d\", \"%d\", \"%d\", \"%d\", %s },\n" % (
                nm, nm + ",",
                c_double_literal(u["factor"]) + ",",
                dims,
                ("true," if u["affine"] else "false,"),
                c_double_literal(u["offset"]) + ",",
                fr.numerator, fr.denominator, of.numerator, of.denominator,
                ("true" if exact else "false"),
            ))
    return "".join(out)


def gen_base_unit_str(units):
    out = [BANNER]
    for u in units:
        out.append("\tcase bu_%-12s return %s;\n"
                   % (u["name"] + ":", c_string_literal(u["symbol"])))
    return "".join(out)


BU_LEN_INDEX_SIZE = 32  # must match BU_LEN_INDEX_SIZE in bovnar_utils.c


def parse_rows(units):
    """The (spelling, base, id) parse rows, ordered by DESCENDING byte length
    (the suffix matcher requires longest-first; see bovnar_utils.c). Each
    spelling is exactly an alias from the data file — the canonical symbol is
    NOT auto-added, so the table reproduces the hand-written bu_table verbatim.
    """
    rows = []
    for u in units:
        base = "bu_" + u["name"]
        for sp in u["aliases"]:
            rows.append((sp, base, u["id"]))
    rows.sort(key=lambda r: (-byte_len(r[0]), r[2], r[0]))
    return rows


def gen_parse_table(rows):
    out = [BANNER]
    for sp, base, _ in rows:
        lit = c_string_literal(sp)
        out.append("\t{ %-22s %2d, %s },\n" % (lit + ",", byte_len(sp), base))
    return "".join(out)


def gen_bu_index(rows):
    """bu_first_for_len[L] = number of spellings strictly longer than L bytes
    (rows are length-sorted, so that is the index of the first entry of length
    <= L); bu_max_len = the longest spelling. Recomputed by the C self-check
    test, which asserts it equals these literals — so they must stay in sync."""
    lens = [byte_len(sp) for sp, _, _ in rows]
    max_len = max(lens) if lens else 0
    if max_len >= BU_LEN_INDEX_SIZE:
        raise SystemExit("bu_max_len %d >= BU_LEN_INDEX_SIZE %d — widen the "
                         "index in bovnar_utils.c" % (max_len, BU_LEN_INDEX_SIZE))
    first = [sum(1 for x in lens if x > L) for L in range(BU_LEN_INDEX_SIZE)]
    out = [BANNER]
    out.append("static const uint16_t bu_first_for_len[BU_LEN_INDEX_SIZE] = {\n")
    for i in range(0, BU_LEN_INDEX_SIZE, 8):
        out.append("\t" + " ".join("%4d," % v for v in first[i:i + 8]) + "\n")
    out.append("};\n")
    out.append("static const uint32_t bu_max_len = %du;\n" % max_len)
    return "".join(out)


def gen_prefix_policy(units):
    out = [BANNER]
    for u in units:
        pol = u["prefix"]
        if pol not in POLICY:
            raise SystemExit("unknown prefix policy %r for %s"
                             % (pol, u["name"]))
        out.append("\t[bu_%-12s = %s,\n"
                   % (u["name"] + "]", POLICY[pol]))
    return "".join(out)


def main():
    path = sys.argv[1] if len(sys.argv) > 1 else os.path.join(GENDATA, "units.bvnr")
    units = load_units(path)

    rows = parse_rows(units)
    # WIRED fragments are written into the source tree where they are #include'd
    # (and where amalgamate.py resolves them by basename). The prefix policy stays
    # a preview in out/ — bvn_prefix_unit_valid keeps its range checks for now.
    inc = os.path.join(REPO, "include")
    utl = GENDIR
    os.makedirs(utl, exist_ok=True)
    artifacts = {
        os.path.join(inc, "bovnar_units.gen.h"):           gen_enum(units),
        os.path.join(utl, "bovnar_si_conv_table.gen.inc"): gen_conv_table(units),
        os.path.join(utl, "bovnar_base_unit_str.gen.inc"): gen_base_unit_str(units),
        os.path.join(utl, "bovnar_bu_table.gen.inc"):      gen_parse_table(rows),
        os.path.join(utl, "bovnar_bu_index.gen.inc"):      gen_bu_index(rows),
        os.path.join(utl, "bovnar_prefix_policy.gen.inc"): gen_prefix_policy(units),
    }
    for dest, text in artifacts.items():
        with open(dest, "w", encoding="utf-8") as f:
            f.write(text)

    print("generated %d units (%d parse rows)" % (len(units), len(rows)))
    print("  wired: bovnar_units.gen.h, bovnar_si_conv_table.gen.inc,")
    print("         bovnar_base_unit_str.gen.inc, bovnar_bu_table.gen.inc,")
    print("         bovnar_bu_index.gen.inc, bovnar_prefix_policy.gen.inc")


if __name__ == "__main__":
    main()
