# SPDX-License-Identifier: MIT
#
# bovnar -> pint unit bridge table.
#
# The first version was generated by a tool; it is HAND-MAINTAINED now, and the
# tool is gone. Add a unit by adding its row and, if pint has no definition for
# it or pint's differs, its definition above. The tests are what verify the
# result: TestUnitTableIntegrity re-derives every unit's dimension and magnitude
# from bovnar and asserts pint reproduces both, and
# TestPintAgreesWithBovnarOnWhatConverts asserts pint refuses every conversion
# bovnar refuses, so an entry that is wrong or missing fails there rather than
# shipping quietly.
#
# Verified against pint 0.25.3:
#   every non-currency base unit reproduces bovnar's dimension AND magnitude
#   exactly (incl. the custom definitions + 6 affine temperature scales).
#   Units carrying a bovnar QUANTITY KIND (bit, byte, dB, Np, pH, the five
#   turbidity scales, PSU, and the angle family) get their own pint dimension
#   instead of pint's native, so pint refuses what bovnar refuses — see
#   KIND_DIMENSIONS. What survives that is listed in SEMANTIC_CAVEATS.
#
# 216 currencies (fiat + crypto + precious metals) have no pint dimension, so each
# is registered as its OWN independent dimension [currency_<CODE>] with the ISO/
# crypto code as the reference unit. Consequences (all verified):
#   * cross-currency .to() raises pint.DimensionalityError — never a silent 1:1
#     conversion (a single shared [currency] dimension WOULD silently convert,
#     e.g. 100 USD -> 100 EUR, so that encoding is deliberately rejected);
#   * same-currency arithmetic works (3 USD + 2 USD = 5 USD);
#   * is_currency_unit() detects them via the [currency_ dimension-name prefix.
# Cross-rate conversion, if ever wanted, belongs in an explicit pint Context.
#
# Keyed on the bovnar BaseUnit *integer code* (stable, mirrors the C enum), NOT
# on the serialized symbol: bovnar symbols collide with pint prefix+unit parses
# (e.g. bovnar "b"=bit vs pint "b"=barn, "R"=roentgen vs pint gas constant).
"""bovnar <-> pint unit translation tables and registry builder."""

from __future__ import annotations

import math


# --- custom physical-unit definitions to register on a pint UnitRegistry ------
# Derived from bovnar's own SI dimension vector + conversion factor, so each
# reproduces bovnar's magnitude exactly (and sidesteps pint's CGS-Gaussian
# fractional dimensions for gauss/maxwell/oersted).
BOVNAR_PINT_DEFINITIONS: list[str] = [
    # pint defines fathom/rod/chain/furlong/league/acre from its SURVEY foot
    # (1200/3937 m), while bovnar uses the international foot -- a silent 2 ppm
    # magnitude error (4 ppm for acre, being an area). pint's foot, mile, yard
    # and inch are already international and agree exactly, so only these six
    # need their own definition.
    'bvnr_fathom = 1.8288 * meter',
    'bvnr_rod = 5.0292 * meter',
    'bvnr_chain = 20.1168 * meter',
    'bvnr_furlong = 201.168 * meter',
    'bvnr_league = 4828.032 * meter',
    'bvnr_acre = 4046.8564224 * meter**2',
    'bvnr_therm = 105480400.0 * meter**2 * kilogram * second**-2',
    'bvnr_rpm = 0.016666666666666666 * second**-1',
    'bvnr_cable = 185.2 * meter',
    'bvnr_delisle = -0.6666666666666666 * kelvin; offset: 373.15',
    'bvnr_doppelzentner = 100.0 * kilogram',
    'bvnr_gauss = 0.0001 * kilogram * second**-2 * ampere**-1',
    'bvnr_german_mile = 7420.44 * meter',
    # gradian (gon): pint's native `gradian` alias is absent in some pint
    # versions, so define it from bovnar's factor (pi/200 rad) for stability.
    'bvnr_klafter = 1.883118 * meter',
    'bvnr_lot = 0.015625 * kilogram',
    'bvnr_maxwell = 1e-08 * meter**2 * kilogram * second**-2 * ampere**-1',
    'bvnr_morgen = 2553.21604938528 * meter**2',
    'bvnr_newton_temp = 3.0303030303030303 * kelvin; offset: 273.15',
    'bvnr_oersted = 79.57747154594767 * meter**-1 * ampere',
    'bvnr_per_cent_mille = 1e-05',
    'bvnr_per_myriad = 0.0001',
    'bvnr_pfund = 0.5 * kilogram',
    # Water hardness: amount concentration of alkaline-earth ions. pint has no
    # hardness units at all, so all six come from bovnar's own factors.
    'bvnr_german_hardness = 0.17832623000517145 * mole * meter**-3',
    'bvnr_english_hardness = 0.1424151981625826 * mole * meter**-3',
    'bvnr_french_hardness = 0.09991407389644906 * mole * meter**-3',
    'bvnr_russian_hardness = 0.024951344877488894 * mole * meter**-3',
    'bvnr_american_hardness = 0.009991407389644906 * mole * meter**-3',
    'bvnr_val = 0.5 * mole',
    'bvnr_grains_per_gallon = 0.17103352162411276 * mole * meter**-3',
    'bvnr_conductivity_factor = 0.01 * siemens * meter**-1',
    'bvnr_ppb = 1e-09',
    'bvnr_pptr = 1e-12',
    'bvnr_ppq = 1e-15',
    'bvnr_printers_point = 0.0003514598 * meter',
    'bvnr_printers_pica = 0.0042175176 * meter',
    'bvnr_horsepower_electric = 746.0 * watt',
    'bvnr_horsepower_boiler = 9809.5 * watt',
    'bvnr_abvolt = 1e-08 * volt',
    'bvnr_assay_ton = 0.029166666666666667 * kilogram',
    'bvnr_bushel_uk = 0.03636872 * meter**3',
    'bvnr_clo = 0.155 * kelvin * meter**2 * watt**-1',
    'bvnr_debye = 3.335640951981521e-30 * coulomb * meter',
    'bvnr_prussian_elle = 0.666937625 * meter',
    'bvnr_prussian_fuss = 0.313853 * meter',
    'bvnr_prussian_line = 0.002179534722222222 * meter',
    'bvnr_prussian_rute = 3.766236 * meter',
    'bvnr_prussian_zoll = 0.026154416666666666 * meter',
    'bvnr_quintal = 100.0 * kilogram',
    # Réaumur: pint's `degree_Reaumur` definition differs across versions
    # (some use a 4/5 scale, giving 100 degRe -> 353.15 K instead of 398.15 K),
    # so pin it to bovnar's factor (5/4) + offset (273.15 K).
    'bvnr_reaumur = 1.25 * kelvin; offset: 273.15',
    'bvnr_romer = 1.9047619047619047 * kelvin; offset: 258.8642857142857',
    'bvnr_scheffel = 0.054961 * meter**3',
    'bvnr_var = 1.0 * meter**2 * kilogram * second**-3',
    'bvnr_zentner = 50.0 * kilogram',
    # Units the profiles needed; each states bovnar's own exact factor rather
    # than borrowing a pint definition that may follow another convention.
    'bvnr_meter_water = 9806.65 * pascal',
    'bvnr_calorie_it = 4.1868 * joule',
    'bvnr_btu_th = 1054.3502644888889 * joule',
    'bvnr_troy_pound = 0.3732417216 * kilogram',
    'bvnr_apothecary_dram = 0.0038879346 * kilogram',
    'bvnr_long_hundredweight = 50.80234544 * kilogram',
    # The survey, typographic, dry-volume and forestry units. Each states
    # bovnar's own exact factor: pint's survey lengths come from its SURVEY
    # foot too, but its dry volumes and typographic units either differ or
    # are absent, so all of them are defined here rather than half aliased.
    'bvnr_survey_inch = 0.0254000508001016 * meter**1',
    'bvnr_survey_yard = 0.91440182880365761 * meter**1',
    'bvnr_survey_fathom = 1.8288036576073152 * meter**1',
    'bvnr_survey_rod = 5.0292100584201167 * meter**1',
    'bvnr_survey_chain = 20.116840233680467 * meter**1',
    'bvnr_survey_link = 0.20116840233680466 * meter**1',
    'bvnr_survey_furlong = 201.16840233680466 * meter**1',
    'bvnr_survey_mile = 1609.3472186944373 * meter**1',
    'bvnr_survey_acre = 4046.8726098742518 * meter**2',
    'bvnr_point = 0.00035277777777777776 * meter**1',
    'bvnr_pica = 0.0042333333333333337 * meter**1',
    'bvnr_line = 0.0021166666666666669 * meter**1',
    'bvnr_dry_gallon = 0.00440488377086 * meter**3',
    'bvnr_dry_quart = 0.001101220942715 * meter**3',
    'bvnr_dry_pint = 0.0005506104713575 * meter**3',
    'bvnr_board_foot = 0.0023597372160000002 * meter**3',
    'bvnr_cord = 3.6245563637760001 * meter**3',
    'bvnr_survey_acre_foot = 1233.4892384681489 * meter**3',
    'bvnr_darcy = 9.8692326671601282e-13 * meter**2',
    'bvnr_therm_ec = 105505585.26199999 * meter**2 * kilogram * second**-2',
    'bvnr_refrigeration_ton = 3516.8528420666667 * meter**2 * kilogram * second**-3',
    'bvnr_dobson = 0.0004462 * mole * meter**-2',
    'bvnr_shake = 1e-08 * second**1',
]


# --- bovnar BaseUnit code -> pint unit token ---------------------------------
BASE_UNIT_TO_PINT: dict[int, str] = {
    # Direct 1:1 — pint native name, dimension AND magnitude verified equal
    100000: 'bvnr_bit',                     # BIT
    100002: 'second',                       # SECOND
    100003: 'meter',                        # METER
    100004: 'gram',                         # GRAM
    100005: 'ampere',                       # AMPERE
    100006: 'kelvin',                       # KELVIN
    100007: 'mole',                         # MOL
    100008: 'candela',                      # CANDELA
    100009: 'hertz',                        # HERTZ
    100010: 'newton',                       # NEWTON
    100011: 'pascal',                       # PASCAL
    100012: 'joule',                        # JOULE
    100013: 'watt',                         # WATT
    100014: 'volt',                         # VOLT
    100015: 'ohm',                          # OHM
    100016: 'farad',                        # FARAD
    100017: 'coulomb',                      # COULOMB
    100018: 'siemens',                      # SIEMENS
    100019: 'weber',                        # WEBER
    100020: 'tesla',                        # TESLA
    100021: 'henry',                        # HENRY
    100022: 'bvnr_lumen',                   # LUMEN
    100023: 'bvnr_lux',                     # LUX
    100024: 'becquerel',                    # BECQUEREL
    100025: 'gray',                         # GRAY
    100026: 'sievert',                      # SIEVERT
    100027: 'katal',                        # KATAL
    100028: 'liter',                        # LITER
    100029: 'minute',                       # MINUTE
    100030: 'hour',                         # HOUR
    100031: 'day',                          # DAY
    100032: 'bvnr_degree',                  # DEGREE
    100034: 'bvnr_radian',                  # RADIAN
    100035: 'bvnr_steradian',               # STERADIAN
    100036: 'metric_ton',                   # TONNE
    100037: 'bar',                          # BAR
    100038: 'electron_volt',                # ELECTRONVOLT
    100039: 'dalton',                       # DALTON
    100040: 'astronomical_unit',            # ASTRONOMICAL_UNIT
    100041: 'hectare',                      # HECTARE
    100042: 'week',                         # WEEK
    100043: 'year',                         # YEAR
    100044: 'inch',                         # INCH
    100045: 'foot',                         # FOOT
    100046: 'yard',                         # YARD
    100047: 'mile',                         # MILE
    100048: 'nautical_mile',                # NAUTICAL_MILE
    100049: 'angstrom',                     # ANGSTROM
    100050: 'light_year',                   # LIGHT_YEAR
    100051: 'parsec',                       # PARSEC
    100052: 'bvnr_furlong',                      # FURLONG
    100053: 'bvnr_fathom',                       # FATHOM
    100054: 'pound',                        # POUND
    100055: 'ounce',                        # OUNCE
    100056: 'grain',                        # GRAIN
    100057: 'stone',                        # STONE
    100058: 'short_ton',                    # SHORT_TON
    100059: 'long_ton',                     # LONG_TON
    100060: 'troy_ounce',                   # TROY_OUNCE
    100061: 'carat',                        # CARAT
    100063: 'atmosphere',                   # ATMOSPHERE
    100064: 'millimeter_Hg',                # MMHG
    100065: 'torr',                         # TORR
    100066: 'psi',                          # PSI
    100067: 'calorie',                      # CALORIE
    100068: 'british_thermal_unit',         # BTU
    100069: 'erg',                          # ERG
    100071: 'horsepower',                   # HORSEPOWER
    100072: 'force_pound',                  # POUND_FORCE
    100073: 'dyne',                         # DYNE
    100074: 'kip',                          # KIP
    100075: 'knot',                         # KNOT
    100076: 'gallon',                       # GALLON
    100077: 'imperial_gallon',              # GALLON_UK
    100078: 'quart',                        # QUART
    100079: 'pint',                         # PINT
    100080: 'cup',                          # CUP
    100081: 'fluid_ounce',                  # FLUID_OUNCE
    100082: 'tablespoon',                   # TABLESPOON
    100083: 'teaspoon',                     # TEASPOON
    100084: 'oil_barrel',                   # BARREL
    100085: 'bvnr_acre',                         # ACRE
    100086: 'barn',                         # BARN
    100087: 'bvnr_arcminute',               # ARCMINUTE
    100088: 'bvnr_arcsecond',               # ARCSECOND
    100089: 'bvnr_gradian',                 # GRAD
    100090: 'poise',                        # POISE
    100091: 'stokes',                       # STOKES
    100095: 'stilb',                        # STILB
    100097: 'galileo',                      # GALILEO
    100098: 'curie',                        # CURIE
    100099: 'roentgen',                     # ROENTGEN
    100100: 'rem',                          # REM
    100103: 'degree_Rankine',               # RANKINE
    100104: 'slug',                         # SLUG
    100105: 'thou',                         # THOU
    100106: 'imperial_pint',                # PINT_UK
    100107: 'imperial_fluid_ounce',         # FLUID_OUNCE_UK
    100108: 'imperial_quart',               # QUART_UK
    100110: 'volt_ampere',                  # VOLT_AMPERE
    100111: 'force_kilogram',               # KILOGRAM_FORCE
    100112: 'inch_Hg',                      # INCH_HG
    100114: 'foot_pound',                   # FOOT_POUND
    100115: 'dram',                         # DRAM
    100116: 'pennyweight',                  # PENNYWEIGHT
    100117: 'bvnr_chain',                        # CHAIN
    100118: 'bvnr_rod',                          # ROD
    100119: 'gill',                         # GILL
    100120: 'imperial_gill',                # GILL_UK
    100121: 'standard_gravity',             # STANDARD_GRAVITY
    100122: 'metric_horsepower',            # METRIC_HORSEPOWER
    100123: 'bvnr_revolution',              # REVOLUTION
    100124: 'month',                        # MONTH
    100125: 'fortnight',                    # FORTNIGHT
    100126: 'technical_atmosphere',         # ATMOSPHERE_TECHNICAL
    100127: 'tex',                          # TEX
    100128: 'denier',                       # DENIER
    100129: 'fluid_dram',                   # FLUID_DRAM
    100130: 'minim',                        # MINIM
    100131: 'peck',                         # PECK
    100132: 'bushel',                       # BUSHEL
    100146: 'survey_foot',                  # SURVEY_FOOT
    100147: 'bvnr_league',                       # LEAGUE
    100149: 'hand',                         # HAND
    100151: 'scruple',                      # SCRUPLE
    100152: 'baud',                         # BAUD
    100157: 'percent',                      # PERCENT
    100158: 'permille',                     # PER_MILLE
    100161: 'ppm',                          # PPM
    100164: 'mile_per_hour',                # MILE_PER_HOUR
    100165: 'kilometer_per_hour',           # KILOMETER_PER_HOUR

    # Affine temperature scales mapped to pint native offset units
    100033: 'degC',                         # CELSIUS
    100062: 'degF',                         # FAHRENHEIT
    100155: 'bvnr_reaumur',                 # REAUMUR

    # Affine temperature scales defined from bovnar factor+offset (absent in pint)
    100153: 'bvnr_delisle',                 # DELISLE
    100154: 'bvnr_newton_temp',             # NEWTON_TEMP
    100156: 'bvnr_romer',                   # ROMER

    # Defined from bovnar dimension+factor (absent in pint, or pint name collides)
    100092: 'bvnr_gauss',                   # GAUSS
    100093: 'bvnr_maxwell',                 # MAXWELL
    100094: 'bvnr_oersted',                 # OERSTED
    100096: 'bvnr_phot',                    # PHOT
    100109: 'bvnr_var',                     # VAR
    100133: 'bvnr_pfund',                   # PFUND
    100134: 'bvnr_zentner',                 # ZENTNER
    100135: 'bvnr_doppelzentner',           # DOPPELZENTNER
    100136: 'bvnr_lot',                     # LOT
    100137: 'bvnr_prussian_line',           # PRUSSIAN_LINE
    100138: 'bvnr_prussian_zoll',           # PRUSSIAN_ZOLL
    100139: 'bvnr_prussian_fuss',           # PRUSSIAN_FUSS
    100140: 'bvnr_prussian_elle',           # PRUSSIAN_ELLE
    100141: 'bvnr_prussian_rute',           # PRUSSIAN_RUTE
    100142: 'bvnr_klafter',                 # KLAFTER
    100143: 'bvnr_german_mile',             # GERMAN_MILE
    100144: 'bvnr_morgen',                  # MORGEN
    100145: 'bvnr_scheffel',                # SCHEFFEL
    100148: 'bvnr_cable',                   # CABLE
    100150: 'bvnr_quintal',                 # QUINTAL
    100159: 'bvnr_per_myriad',              # PER_MYRIAD
    100160: 'bvnr_per_cent_mille',          # PER_CENT_MILLE
    100162: 'bvnr_ppb',                     # PPB
    100163: 'bvnr_ph_scale',                # PH_SCALE
    100166: 'bvnr_german_hardness',         # GERMAN_HARDNESS
    100167: 'bvnr_english_hardness',        # ENGLISH_HARDNESS
    100168: 'bvnr_french_hardness',         # FRENCH_HARDNESS
    100169: 'bvnr_russian_hardness',        # RUSSIAN_HARDNESS
    100170: 'bvnr_american_hardness',       # AMERICAN_HARDNESS
    100171: 'bvnr_val',                     # VAL
    100172: 'bvnr_grains_per_gallon',       # GRAINS_PER_GALLON
    100173: 'bvnr_ntu',                     # TURBIDITY_NTU
    100174: 'bvnr_fnu',                     # TURBIDITY_FNU
    100175: 'bvnr_psu',                     # PRACTICAL_SALINITY
    100176: 'bvnr_conductivity_factor',     # CONDUCTIVITY_FACTOR
    100177: 'bvnr_ftu',                     # TURBIDITY_FTU
    100178: 'bvnr_fau',                     # TURBIDITY_FAU
    100179: 'bvnr_jtu',                     # TURBIDITY_JTU

    # Defined to match bovnar magnitude exactly (pint native uses a different convention)
    100070: 'bvnr_therm',                   # THERM
    100113: 'bvnr_rpm',                     # RPM

    # Quantity kinds: their own pint dimension (or, for the angle family, the
    # shared [angle] reference) so that pint refuses what bovnar refuses.
    # See KIND_DIMENSIONS above.
    100001: 'bvnr_byte',                    # BYTE
    100101: 'bvnr_neper',                   # NEPER
    100102: 'bvnr_decibel',                 # DECIBEL

    # The six temperature INTERVALS. They carry bovnar's temperature-interval
    # kind, so they get a dimension of their own here for the same reason the
    # turbidity scales do: pint's kelvin would convert ΔK straight into K, and
    # a rise of 25 degrees is 25 K while 25 °C is 298.15 K.
    100180: 'bvnr_delta_kelvin',            # DELTA_KELVIN (also Δ°C)
    100181: 'bvnr_delta_fahrenheit',        # DELTA_FAHRENHEIT (also Δ°Ra)
    100182: 'bvnr_delta_delisle',           # DELTA_DELISLE
    100183: 'bvnr_delta_newton_temp',       # DELTA_NEWTON_TEMP
    100184: 'bvnr_delta_reaumur',           # DELTA_REAUMUR
    100185: 'bvnr_delta_romer',             # DELTA_ROMER

    # The units the unit profiles needed.
    100186: 'bvnr_meter_water',             # METER_WATER
    100187: 'bvnr_calorie_it',              # CALORIE_IT
    100188: 'bvnr_btu_th',                  # BTU_TH
    100189: 'bvnr_troy_pound',              # TROY_POUND
    100190: 'bvnr_apothecary_dram',         # APOTHECARY_DRAM
    100191: 'bvnr_long_hundredweight',      # LONG_HUNDREDWEIGHT

    # The survey, typographic, dry-volume and forestry units.
    100192: 'bvnr_survey_inch',              # SURVEY_INCH
    100193: 'bvnr_survey_yard',              # SURVEY_YARD
    100194: 'bvnr_survey_fathom',            # SURVEY_FATHOM
    100195: 'bvnr_survey_rod',               # SURVEY_ROD
    100196: 'bvnr_survey_chain',             # SURVEY_CHAIN
    100197: 'bvnr_survey_link',              # SURVEY_LINK
    100198: 'bvnr_survey_furlong',           # SURVEY_FURLONG
    100199: 'bvnr_survey_mile',              # SURVEY_MILE
    100200: 'bvnr_survey_acre',              # SURVEY_ACRE
    100201: 'bvnr_point',                    # POINT
    100202: 'bvnr_pica',                     # PICA
    100203: 'bvnr_line',                     # LINE
    100204: 'bvnr_dry_gallon',               # DRY_GALLON
    100205: 'bvnr_dry_quart',                # DRY_QUART
    100206: 'bvnr_dry_pint',                 # DRY_PINT
    100207: 'bvnr_board_foot',               # BOARD_FOOT
    100208: 'bvnr_cord',                     # CORD
    100209: 'bvnr_survey_acre_foot',         # SURVEY_ACRE_FOOT
    100210: 'bvnr_darcy',                    # DARCY
    100211: 'bvnr_therm_ec',                 # THERM_EC
    100212: 'bvnr_refrigeration_ton',        # REFRIGERATION_TON
    100213: 'bvnr_dobson',                   # DOBSON
    100214: 'bvnr_shake',                    # SHAKE
    100215: 'bvnr_pptr',                     # PPT
    100216: 'bvnr_ppq',                      # PPQ
    100217: 'bvnr_printers_point',           # PRINTERS_POINT
    100218: 'bvnr_printers_pica',            # PRINTERS_PICA
    100219: 'bvnr_horsepower_electric',      # HORSEPOWER_ELECTRIC
    100220: 'bvnr_horsepower_boiler',        # HORSEPOWER_BOILER
    100221: 'bvnr_abvolt',                   # ABVOLT
    100222: 'bvnr_assay_ton',                # ASSAY_TON
    100223: 'bvnr_bushel_uk',                # BUSHEL_UK
    100224: 'bvnr_clo',                      # CLO
    100225: 'bvnr_debye',                    # DEBYE

}


# --- quantity kinds: units bovnar refuses to interconvert -------------------
# bovnar tracks "quantity kinds" for units that carry NO SI dimension yet are
# not interchangeable with a plain number or with each other — bit vs byte, an
# angle vs a count, dB vs Np vs pH, and one kind per turbidity method. pint has
# no such concept: to it they are all dimensionless, so it would convert an NTU
# into an FNU or a pH into a percentage, exactly the answer bovnar exists to
# refuse.
#
# The fix is the one the currency table already uses below: give each kind its
# own pint DIMENSION. pint then enforces bovnar's rule natively —
# DimensionalityError instead of a silent number — and conversions WITHIN a kind
# keep working (m~NTU -> NTU, ° -> rad, sr -> rad²), because that is what a
# shared dimension means.
#
# The cost, and it is a real one: these units no longer speak to pint's natives.
# A bovnar-derived byte will not convert to pint's `megabyte`, nor a bovnar
# radian to pint's `degree`. Pass isolate_kinds=False to build_registry() to get
# the old aliasing back, and with it pint's permissiveness.
#
# dB and Np deliberately do NOT use pint's logarithmic units: bovnar models them
# as linear tags (a value labelled dB, not a log-arithmetic type), and mapping
# them onto pint's log units would import semantics bovnar does not have.
KIND_DIMENSIONS: dict[str, str] = {
    'bvnr_bit':         'information_bit',
    'bvnr_byte':        'information_byte',
    'bvnr_decibel':     'log_decibel',
    'bvnr_neper':       'log_neper',
    'bvnr_ph_scale':    'ph_scale',
    'bvnr_ntu':         'turbidity_ntu',
    'bvnr_fnu':         'turbidity_fnu',
    'bvnr_ftu':         'turbidity_ftu',
    'bvnr_fau':         'turbidity_fau',
    'bvnr_jtu':         'turbidity_jtu',
    'bvnr_psu':         'practical_salinity',
    'bvnr_radian':      'angle',
    'bvnr_delta_kelvin': 'temperature_interval',
}

# The angle kind is SHARED: degree -> radian is a conversion people legitimately
# want, and steradian really is radian², so these are defined from the reference
# rather than as dimensions of their own.
# The temperature-interval kind is SHARED across the six scales, exactly as the
# angle kind is: Δ°F -> ΔK is a conversion people legitimately want (a 9-degree
# Fahrenheit rise IS a 5-kelvin rise), and only the offset is missing, because
# an interval has none. Δ°C shares bvnr_delta_kelvin and Δ°Ra shares
# bvnr_delta_fahrenheit; the Celsius degree IS the kelvin and the Rankine degree
# IS the Fahrenheit degree, so those are aliases and not units.
_INTERVAL_DERIVED: list[str] = [
    'bvnr_delta_fahrenheit = %.17g * bvnr_delta_kelvin' % (5.0 / 9.0),
    'bvnr_delta_delisle = %.17g * bvnr_delta_kelvin' % (-2.0 / 3.0),
    'bvnr_delta_newton_temp = %.17g * bvnr_delta_kelvin' % (100.0 / 33.0),
    'bvnr_delta_reaumur = 1.25 * bvnr_delta_kelvin',
    'bvnr_delta_romer = %.17g * bvnr_delta_kelvin' % (40.0 / 21.0),
]

_ANGLE_DERIVED: list[str] = [
    'bvnr_degree = %.17g * bvnr_radian' % (math.pi / 180.0),
    'bvnr_gradian = %.17g * bvnr_radian' % (math.pi / 200.0),
    'bvnr_revolution = %.17g * bvnr_radian' % (2.0 * math.pi),
    'bvnr_arcminute = %.17g * bvnr_radian' % (math.pi / 10800.0),
    'bvnr_arcsecond = %.17g * bvnr_radian' % (math.pi / 648000.0),
    'bvnr_steradian = bvnr_radian ** 2',
    # The photometric units built on the steradian carry it here too, because
    # bovnar's kind table gives them the steradian's weight: a lumen IS
    # candela·steradian and a lux IS lumen/m². Defined from pint's `candela`
    # rather than from pint's own `lumen`/`lux`, whose SI dimensionality is bare
    # candela — that is what let pint convert lm to cd and lx to sb at factor 1
    # while bovnar refused the same conversions written as cd·sr and cd·sr/m².
    # `candela` (luminous intensity) and pint's native `stilb` (cd/cm²,
    # luminance) stay steradian-free, which is exactly what separates them from
    # luminous flux and illuminance.
    'bvnr_lumen = candela * bvnr_steradian',
    'bvnr_lux = bvnr_lumen * meter**-2',
    'bvnr_phot = 10000.0 * bvnr_lux',
]

# What isolate_kinds=False falls back to: pint's native where one exists, plain
# dimensionless where none does. This is bovnar's pre-isolation behaviour, kept
# for callers who need to interoperate with pint units from other code.
_KIND_NATIVE_FALLBACK: list[str] = [
    'bvnr_bit = bit',
    'bvnr_byte = byte',
    'bvnr_decibel = decibel',
    'bvnr_neper = neper',
    'bvnr_radian = radian',
    'bvnr_degree = degree',
    'bvnr_gradian = %.17g * radian' % (math.pi / 200.0),
    'bvnr_revolution = revolution',
    'bvnr_arcminute = arcminute',
    'bvnr_arcsecond = arcsecond',
    'bvnr_steradian = steradian',
    'bvnr_lumen = lumen',
    'bvnr_lux = lux',
    'bvnr_phot = 10000.0 * lux',
    'bvnr_ph_scale = 1.0',
    'bvnr_ntu = 1.0',
    'bvnr_fnu = 1.0',
    'bvnr_ftu = 1.0',
    'bvnr_fau = 1.0',
    'bvnr_jtu = 1.0',
    'bvnr_psu = 1.0',
    'bvnr_delta_kelvin = kelvin',
    'bvnr_delta_fahrenheit = %.17g * kelvin' % (5.0 / 9.0),
    'bvnr_delta_delisle = %.17g * kelvin' % (-2.0 / 3.0),
    'bvnr_delta_newton_temp = %.17g * kelvin' % (100.0 / 33.0),
    'bvnr_delta_reaumur = 1.25 * kelvin',
    'bvnr_delta_romer = %.17g * kelvin' % (40.0 / 21.0),
]

# --- semantic caveats: parse/label OK, but value semantics differ ------------
SEMANTIC_CAVEATS: dict[str, str] = {
    'DECIBEL': 'isolated as its own pint dimension, so the conversions bovnar refuses are refused there too. What remains is arithmetic: bovnar models dB as a linear tag, so pint will add two of them and the sum is not what a decibel means (20 dB is a ratio of 100, not twice 10 dB).',
    'NEPER': 'as DECIBEL: the label and the refusals survive, the logarithmic arithmetic does not.',
    'PH_SCALE': 'as DECIBEL. pH 7 is not "7 of" anything and pH 6 is ten times the concentration of pH 7, so summing or averaging pH values is meaningless in either library.',
    'VAL': 'bovnar val is the equivalent AS USED IN WATER ANALYSIS (divalent ions): 1 val = 0.5 mol. For a monovalent species an equivalent is 1 mol, which neither library can infer from the unit alone.',
}


# --- currencies: bovnar BaseUnit code -> ISO/crypto reference-unit token ------
# Each token is BOTH the pint unit name and the basis of its private dimension
# [currency_<token>] (see CURRENCY_DEFINITIONS / build_registry).
CURRENCY_TOKENS: dict[int, str] = {
    900000: 'AED',
    900001: 'AFN',
    900002: 'ALL',
    900003: 'AMD',
    900004: 'ANG',
    900005: 'AOA',
    900006: 'ARS',
    900007: 'AUD',
    900008: 'AWG',
    900009: 'AZN',
    900010: 'BAM',
    900011: 'BBD',
    900012: 'BDT',
    900013: 'BGN',
    900014: 'BHD',
    900015: 'BIF',
    900016: 'BMD',
    900017: 'BND',
    900018: 'BOB',
    900019: 'BRL',
    900020: 'BSD',
    900021: 'BTN',
    900022: 'BWP',
    900023: 'BYN',
    900024: 'BZD',
    900025: 'CAD',
    900026: 'CDF',
    900027: 'CHF',
    900028: 'CLF',
    900029: 'CLP',
    900030: 'CNY',
    900031: 'COP',
    900032: 'CRC',
    900033: 'CUP',
    900034: 'CVE',
    900035: 'CZK',
    900036: 'DJF',
    900037: 'DKK',
    900038: 'DOP',
    900039: 'DZD',
    900040: 'EGP',
    900041: 'ERN',
    900042: 'ETB',
    900043: 'EUR',
    900044: 'FJD',
    900045: 'FKP',
    900046: 'GBP',
    900047: 'GEL',
    900048: 'GHS',
    900049: 'GIP',
    900050: 'GMD',
    900051: 'GNF',
    900052: 'GTQ',
    900053: 'GYD',
    900054: 'HKD',
    900055: 'HNL',
    900056: 'HRK',
    900057: 'HTG',
    900058: 'HUF',
    900059: 'IDR',
    900060: 'ILS',
    900061: 'INR',
    900062: 'IQD',
    900063: 'IRR',
    900064: 'ISK',
    900065: 'JMD',
    900066: 'JOD',
    900067: 'JPY',
    900068: 'KES',
    900069: 'KGS',
    900070: 'KHR',
    900071: 'KMF',
    900072: 'KPW',
    900073: 'KRW',
    900074: 'KWD',
    900075: 'KYD',
    900076: 'KZT',
    900077: 'LAK',
    900078: 'LBP',
    900079: 'LKR',
    900080: 'LRD',
    900081: 'LSL',
    900082: 'LYD',
    900083: 'MAD',
    900084: 'MDL',
    900085: 'MGA',
    900086: 'MKD',
    900087: 'MMK',
    900088: 'MNT',
    900089: 'MOP',
    900090: 'MRU',
    900091: 'MUR',
    900092: 'MVR',
    900093: 'MWK',
    900094: 'MXN',
    900095: 'MYR',
    900096: 'MZN',
    900097: 'NAD',
    900098: 'NGN',
    900099: 'NIO',
    900100: 'NOK',
    900101: 'NPR',
    900102: 'NZD',
    900103: 'OMR',
    900104: 'PAB',
    900105: 'PEN',
    900106: 'PGK',
    900107: 'PHP',
    900108: 'PKR',
    900109: 'PLN',
    900110: 'PYG',
    900111: 'QAR',
    900112: 'RON',
    900113: 'RSD',
    900114: 'RUB',
    900115: 'RWF',
    900116: 'SAR',
    900117: 'SBD',
    900118: 'SCR',
    900119: 'SDG',
    900120: 'SEK',
    900121: 'SGD',
    900122: 'SHP',
    900123: 'SLE',
    900124: 'SLL',
    900125: 'SOS',
    900127: 'SSP',
    900126: 'SRD',
    900128: 'STN',
    900129: 'SVC',
    900130: 'SYP',
    900131: 'SZL',
    900132: 'THB',
    900133: 'TJS',
    900134: 'TMT',
    900135: 'TND',
    900136: 'TOP',
    900137: 'TRY',
    900138: 'TTD',
    900139: 'TWD',
    900140: 'TZS',
    900141: 'UAH',
    900142: 'UGX',
    900143: 'USD',
    900144: 'UYU',
    900145: 'UZS',
    900146: 'VES',
    900147: 'VND',
    900148: 'VUV',
    900149: 'WST',
    900150: 'XAF',
    900151: 'XAG',
    900152: 'XAU',
    900153: 'XCD',
    900155: 'XDR',
    900156: 'XOF',
    900157: 'XPD',
    900158: 'XPF',
    900159: 'XPT',
    900160: 'XTS',
    900161: 'YER',
    900162: 'ZAR',
    900163: 'ZMW',
    900165: 'ZWL',
    900166: 'BTC',
    900167: 'ETH',
    900168: 'SOL',
    900169: 'XRP',
    900170: 'BNB',
    900171: 'ADA',
    900172: 'LTC',
    900173: 'DOT',
    900174: 'XMR',
    900175: 'ETC',
    900176: 'BCH',
    900177: 'XLM',
    900178: 'FIL',
    900179: 'ICP',
    900180: 'TRX',
    900181: 'EOS',
    900182: 'VET',
    900183: 'NEO',
    900184: 'ZEC',
    900185: 'UNI',
    900186: 'ARB',
    900187: 'SUI',
    900188: 'TON',
    900189: 'INJ',
    900190: 'SEI',
    900191: 'APT',
    900192: 'TAO',
    900193: 'WIF',
    900194: 'DOGE',
    900195: 'LINK',
    900196: 'USDT',
    900197: 'USDC',
    900198: 'AVAX',
    900199: 'ATOM',
    900200: 'POL',
    900201: 'NEAR',
    900202: 'ALGO',
    900203: 'HBAR',
    900204: 'AAVE',
    900205: 'MKR',
    900206: 'DAI',
    900207: 'STX',
    900208: 'GRT',
    900209: 'LDO',
    900210: 'BONK',
    900211: 'PEPE',
    900212: 'SHIB',
    900213: 'JUP',
    900214: 'PYTH',
    900215: 'RUNE',
    900164: 'ZWG',
    900154: 'XCG',
}

# One independent pint dimension per currency => members are non-convertible.
CURRENCY_DEFINITIONS: list[str] = [
    'AED = [currency_AED]',
    'AFN = [currency_AFN]',
    'ALL = [currency_ALL]',
    'AMD = [currency_AMD]',
    'ANG = [currency_ANG]',
    'AOA = [currency_AOA]',
    'ARS = [currency_ARS]',
    'AUD = [currency_AUD]',
    'AWG = [currency_AWG]',
    'AZN = [currency_AZN]',
    'BAM = [currency_BAM]',
    'BBD = [currency_BBD]',
    'BDT = [currency_BDT]',
    'BGN = [currency_BGN]',
    'BHD = [currency_BHD]',
    'BIF = [currency_BIF]',
    'BMD = [currency_BMD]',
    'BND = [currency_BND]',
    'BOB = [currency_BOB]',
    'BRL = [currency_BRL]',
    'BSD = [currency_BSD]',
    'BTN = [currency_BTN]',
    'BWP = [currency_BWP]',
    'BYN = [currency_BYN]',
    'BZD = [currency_BZD]',
    'CAD = [currency_CAD]',
    'CDF = [currency_CDF]',
    'CHF = [currency_CHF]',
    'CLF = [currency_CLF]',
    'CLP = [currency_CLP]',
    'CNY = [currency_CNY]',
    'COP = [currency_COP]',
    'CRC = [currency_CRC]',
    'CUP = [currency_CUP]',
    'CVE = [currency_CVE]',
    'CZK = [currency_CZK]',
    'DJF = [currency_DJF]',
    'DKK = [currency_DKK]',
    'DOP = [currency_DOP]',
    'DZD = [currency_DZD]',
    'EGP = [currency_EGP]',
    'ERN = [currency_ERN]',
    'ETB = [currency_ETB]',
    'EUR = [currency_EUR]',
    'FJD = [currency_FJD]',
    'FKP = [currency_FKP]',
    'GBP = [currency_GBP]',
    'GEL = [currency_GEL]',
    'GHS = [currency_GHS]',
    'GIP = [currency_GIP]',
    'GMD = [currency_GMD]',
    'GNF = [currency_GNF]',
    'GTQ = [currency_GTQ]',
    'GYD = [currency_GYD]',
    'HKD = [currency_HKD]',
    'HNL = [currency_HNL]',
    'HRK = [currency_HRK]',
    'HTG = [currency_HTG]',
    'HUF = [currency_HUF]',
    'IDR = [currency_IDR]',
    'ILS = [currency_ILS]',
    'INR = [currency_INR]',
    'IQD = [currency_IQD]',
    'IRR = [currency_IRR]',
    'ISK = [currency_ISK]',
    'JMD = [currency_JMD]',
    'JOD = [currency_JOD]',
    'JPY = [currency_JPY]',
    'KES = [currency_KES]',
    'KGS = [currency_KGS]',
    'KHR = [currency_KHR]',
    'KMF = [currency_KMF]',
    'KPW = [currency_KPW]',
    'KRW = [currency_KRW]',
    'KWD = [currency_KWD]',
    'KYD = [currency_KYD]',
    'KZT = [currency_KZT]',
    'LAK = [currency_LAK]',
    'LBP = [currency_LBP]',
    'LKR = [currency_LKR]',
    'LRD = [currency_LRD]',
    'LSL = [currency_LSL]',
    'LYD = [currency_LYD]',
    'MAD = [currency_MAD]',
    'MDL = [currency_MDL]',
    'MGA = [currency_MGA]',
    'MKD = [currency_MKD]',
    'MMK = [currency_MMK]',
    'MNT = [currency_MNT]',
    'MOP = [currency_MOP]',
    'MRU = [currency_MRU]',
    'MUR = [currency_MUR]',
    'MVR = [currency_MVR]',
    'MWK = [currency_MWK]',
    'MXN = [currency_MXN]',
    'MYR = [currency_MYR]',
    'MZN = [currency_MZN]',
    'NAD = [currency_NAD]',
    'NGN = [currency_NGN]',
    'NIO = [currency_NIO]',
    'NOK = [currency_NOK]',
    'NPR = [currency_NPR]',
    'NZD = [currency_NZD]',
    'OMR = [currency_OMR]',
    'PAB = [currency_PAB]',
    'PEN = [currency_PEN]',
    'PGK = [currency_PGK]',
    'PHP = [currency_PHP]',
    'PKR = [currency_PKR]',
    'PLN = [currency_PLN]',
    'PYG = [currency_PYG]',
    'QAR = [currency_QAR]',
    'RON = [currency_RON]',
    'RSD = [currency_RSD]',
    'RUB = [currency_RUB]',
    'RWF = [currency_RWF]',
    'SAR = [currency_SAR]',
    'SBD = [currency_SBD]',
    'SCR = [currency_SCR]',
    'SDG = [currency_SDG]',
    'SEK = [currency_SEK]',
    'SGD = [currency_SGD]',
    'SHP = [currency_SHP]',
    'SLE = [currency_SLE]',
    'SLL = [currency_SLL]',
    'SOS = [currency_SOS]',
    'SSP = [currency_SSP]',
    'SRD = [currency_SRD]',
    'STN = [currency_STN]',
    'SVC = [currency_SVC]',
    'SYP = [currency_SYP]',
    'SZL = [currency_SZL]',
    'THB = [currency_THB]',
    'TJS = [currency_TJS]',
    'TMT = [currency_TMT]',
    'TND = [currency_TND]',
    'TOP = [currency_TOP]',
    'TRY = [currency_TRY]',
    'TTD = [currency_TTD]',
    'TWD = [currency_TWD]',
    'TZS = [currency_TZS]',
    'UAH = [currency_UAH]',
    'UGX = [currency_UGX]',
    'USD = [currency_USD]',
    'UYU = [currency_UYU]',
    'UZS = [currency_UZS]',
    'VES = [currency_VES]',
    'VND = [currency_VND]',
    'VUV = [currency_VUV]',
    'WST = [currency_WST]',
    'XAF = [currency_XAF]',
    'XAG = [currency_XAG]',
    'XAU = [currency_XAU]',
    'XCD = [currency_XCD]',
    'XDR = [currency_XDR]',
    'XOF = [currency_XOF]',
    'XPD = [currency_XPD]',
    'XPF = [currency_XPF]',
    'XPT = [currency_XPT]',
    'XTS = [currency_XTS]',
    'YER = [currency_YER]',
    'ZAR = [currency_ZAR]',
    'ZMW = [currency_ZMW]',
    'ZWL = [currency_ZWL]',
    'BTC = [currency_BTC]',
    'ETH = [currency_ETH]',
    'SOL = [currency_SOL]',
    'XRP = [currency_XRP]',
    'BNB = [currency_BNB]',
    'ADA = [currency_ADA]',
    'LTC = [currency_LTC]',
    'DOT = [currency_DOT]',
    'XMR = [currency_XMR]',
    'ETC = [currency_ETC]',
    'BCH = [currency_BCH]',
    'XLM = [currency_XLM]',
    'FIL = [currency_FIL]',
    'ICP = [currency_ICP]',
    'TRX = [currency_TRX]',
    'EOS = [currency_EOS]',
    'VET = [currency_VET]',
    'NEO = [currency_NEO]',
    'ZEC = [currency_ZEC]',
    'UNI = [currency_UNI]',
    'ARB = [currency_ARB]',
    'SUI = [currency_SUI]',
    'TON = [currency_TON]',
    'INJ = [currency_INJ]',
    'SEI = [currency_SEI]',
    'APT = [currency_APT]',
    'TAO = [currency_TAO]',
    'WIF = [currency_WIF]',
    'DOGE = [currency_DOGE]',
    'LINK = [currency_LINK]',
    'USDT = [currency_USDT]',
    'USDC = [currency_USDC]',
    'AVAX = [currency_AVAX]',
    'ATOM = [currency_ATOM]',
    'POL = [currency_POL]',
    'NEAR = [currency_NEAR]',
    'ALGO = [currency_ALGO]',
    'HBAR = [currency_HBAR]',
    'AAVE = [currency_AAVE]',
    'MKR = [currency_MKR]',
    'DAI = [currency_DAI]',
    'STX = [currency_STX]',
    'GRT = [currency_GRT]',
    'LDO = [currency_LDO]',
    'BONK = [currency_BONK]',
    'PEPE = [currency_PEPE]',
    'SHIB = [currency_SHIB]',
    'JUP = [currency_JUP]',
    'PYTH = [currency_PYTH]',
    'RUNE = [currency_RUNE]',
    # Appended fiat (enum 378-379)
    'ZWG = [currency_ZWG]',
    'XCG = [currency_XCG]',
]


def is_currency_unit(unit) -> bool:
    """True if *unit* (a pint Unit/Quantity) is a bovnar currency.

    Detected via the ``[currency_`` dimension-name prefix, so it holds for any
    power/product that involves a currency (e.g. USD/year).
    """
    return any(str(k).startswith('[currency_') for k in unit.dimensionality)


def build_registry(reg=None, *, with_currencies: bool = True,
                   isolate_kinds: bool = True):
    """Return a pint UnitRegistry with bovnar's custom units registered.

    Pass an existing registry to extend it, or None to create a fresh one.
    Set with_currencies=False to skip the 216 currency dimensions (e.g. when
    the caller prefers to reject currency-typed data in the pint path).

    isolate_kinds (default True) gives every bovnar quantity kind its own pint
    dimension, so pint refuses exactly the conversions bovnar refuses: an NTU
    will not become an FNU, a byte will not become 8 bits, an angle will not
    become a plain number. Conversions *within* a kind keep working. Set it to
    False to alias those units onto pint's natives instead — a bovnar byte then
    converts to pint's `megabyte`, and pint also allows the conversions bovnar
    calls unsound. That trade is the caller's to make; the default is fidelity.
    """
    import pint
    if reg is None:
        reg = pint.UnitRegistry()
    for d in BOVNAR_PINT_DEFINITIONS:
        reg.define(d)
    if isolate_kinds:
        for name, dim in KIND_DIMENSIONS.items():
            reg.define('%s = [%s]' % (name, dim))
        for d in _ANGLE_DERIVED:
            reg.define(d)
        for d in _INTERVAL_DERIVED:
            reg.define(d)
    else:
        for d in _KIND_NATIVE_FALLBACK:
            reg.define(d)
    if with_currencies:
        for d in CURRENCY_DEFINITIONS:
            reg.define(d)
    return reg


def is_kind_scale(unit) -> bool:
    """True if *unit* carries one of bovnar's isolated quantity kinds.

    Only meaningful for a registry built with isolate_kinds=True (the default);
    with the natives aliased back in there is nothing to detect.
    """
    dims = getattr(unit, 'dimensionality', unit)
    wanted = set(KIND_DIMENSIONS.values())
    return any(str(name).strip('[]') in wanted for name in dims)
