# SPDX-License-Identifier: MIT
#
# bovnar -> pint unit bridge table.
#
# The first version was generated by a tool; it is HAND-MAINTAINED now, and the
# tool is gone. Add a unit by adding its row and, if pint has no definition for
# it or pint's differs, its definition above. The tests are what verify the
# result: TestUnitTableIntegrity re-derives every unit's dimension and magnitude
# from bovnar and asserts pint reproduces both, and
# TestPintAgreesWithBovnarOnWhatConverts asserts pint refuses every conversion
# bovnar refuses, so an entry that is wrong or missing fails there rather than
# shipping quietly.
#
# Verified against pint 0.25.3:
#   every non-currency base unit reproduces bovnar's dimension AND magnitude
#   exactly (incl. the custom definitions + 6 affine temperature scales).
#   Units carrying a bovnar QUANTITY KIND (bit, byte, dB, Np, pH, the five
#   turbidity scales, PSU, and the angle family) get their own pint dimension
#   instead of pint's native, so pint refuses what bovnar refuses — see
#   KIND_DIMENSIONS. What survives that is listed in SEMANTIC_CAVEATS.
#
# 216 currencies (fiat + crypto + precious metals) have no pint dimension, so each
# is registered as its OWN independent dimension [currency_<CODE>] with the ISO/
# crypto code as the reference unit. Consequences (all verified):
#   * cross-currency .to() raises pint.DimensionalityError — never a silent 1:1
#     conversion (a single shared [currency] dimension WOULD silently convert,
#     e.g. 100 USD -> 100 EUR, so that encoding is deliberately rejected);
#   * same-currency arithmetic works (3 USD + 2 USD = 5 USD);
#   * is_currency_unit() detects them via the [currency_ dimension-name prefix.
# Cross-rate conversion, if ever wanted, belongs in an explicit pint Context.
#
# Keyed on the bovnar BaseUnit *integer code* (stable, mirrors the C enum), NOT
# on the serialized symbol: bovnar symbols collide with pint prefix+unit parses
# (e.g. bovnar "b"=bit vs pint "b"=barn, "R"=roentgen vs pint gas constant).
"""bovnar <-> pint unit translation tables and registry builder."""

from __future__ import annotations

import math


# --- custom physical-unit definitions to register on a pint UnitRegistry ------
# Derived from bovnar's own SI dimension vector + conversion factor, so each
# reproduces bovnar's magnitude exactly (and sidesteps pint's CGS-Gaussian
# fractional dimensions for gauss/maxwell/oersted).
BOVNAR_PINT_DEFINITIONS: list[str] = [
    # pint defines fathom/rod/chain/furlong/league/acre from its SURVEY foot
    # (1200/3937 m), while bovnar uses the international foot -- a silent 2 ppm
    # magnitude error (4 ppm for acre, being an area). pint's foot, mile, yard
    # and inch are already international and agree exactly, so only these six
    # need their own definition.
    'bvnr_fathom = 1.8288 * meter',
    'bvnr_rod = 5.0292 * meter',
    'bvnr_chain = 20.1168 * meter',
    'bvnr_furlong = 201.168 * meter',
    'bvnr_league = 4828.032 * meter',
    'bvnr_acre = 4046.8564224 * meter**2',
    'bvnr_therm = 105480400.0 * meter**2 * kilogram * second**-2',
    'bvnr_rpm = 0.016666666666666666 * second**-1',
    'bvnr_cable = 185.2 * meter',
    'bvnr_delisle = -0.6666666666666666 * kelvin; offset: 373.15',
    'bvnr_doppelzentner = 100.0 * kilogram',
    'bvnr_gauss = 0.0001 * kilogram * second**-2 * ampere**-1',
    'bvnr_german_mile = 7420.44 * meter',
    # gradian (gon): pint's native `gradian` alias is absent in some pint
    # versions, so define it from bovnar's factor (pi/200 rad) for stability.
    'bvnr_klafter = 1.88312 * meter',
    'bvnr_lot = 0.015625 * kilogram',
    'bvnr_maxwell = 1e-08 * meter**2 * kilogram * second**-2 * ampere**-1',
    'bvnr_morgen = 2553.22 * meter**2',
    'bvnr_newton_temp = 3.0303030303030303 * kelvin; offset: 273.15',
    'bvnr_oersted = 79.57747154594767 * meter**-1 * ampere',
    'bvnr_per_cent_mille = 1e-05',
    'bvnr_per_myriad = 0.0001',
    'bvnr_pfund = 0.5 * kilogram',
    # Water hardness: amount concentration of alkaline-earth ions. pint has no
    # hardness units at all, so all six come from bovnar's own factors.
    'bvnr_german_hardness = 0.17832623000517145 * mole * meter**-3',
    'bvnr_english_hardness = 0.1424151981625826 * mole * meter**-3',
    'bvnr_french_hardness = 0.09991407389644906 * mole * meter**-3',
    'bvnr_russian_hardness = 0.024951344877488894 * mole * meter**-3',
    'bvnr_american_hardness = 0.009991407389644906 * mole * meter**-3',
    'bvnr_val = 0.5 * mole',
    'bvnr_grains_per_gallon = 0.17103352162411276 * mole * meter**-3',
    'bvnr_conductivity_factor = 0.01 * siemens * meter**-1',
    'bvnr_phot = 10000.0 * meter**-2 * candela',
    'bvnr_ppb = 1e-09',
    'bvnr_prussian_elle = 0.666937625 * meter',
    'bvnr_prussian_fuss = 0.313853 * meter',
    'bvnr_prussian_line = 0.002179534722222222 * meter',
    'bvnr_prussian_rute = 3.76624 * meter',
    'bvnr_prussian_zoll = 0.026154416666666666 * meter',
    'bvnr_quintal = 100.0 * kilogram',
    # Réaumur: pint's `degree_Reaumur` definition differs across versions
    # (some use a 4/5 scale, giving 100 degRe -> 353.15 K instead of 398.15 K),
    # so pin it to bovnar's factor (5/4) + offset (273.15 K).
    'bvnr_reaumur = 1.25 * kelvin; offset: 273.15',
    'bvnr_romer = 1.9047619047619047 * kelvin; offset: 258.8642857142857',
    'bvnr_scheffel = 0.054961 * meter**3',
    'bvnr_var = 1.0 * meter**2 * kilogram * second**-3',
    'bvnr_zentner = 50.0 * kilogram',
]


# --- bovnar BaseUnit code -> pint unit token ---------------------------------
BASE_UNIT_TO_PINT: dict[int, str] = {
    # Direct 1:1 — pint native name, dimension AND magnitude verified equal
      1: 'bvnr_bit',                     # BIT
      3: 'second',                       # SECOND
      4: 'meter',                        # METER
      5: 'gram',                         # GRAM
      6: 'ampere',                       # AMPERE
      7: 'kelvin',                       # KELVIN
      8: 'mole',                         # MOL
      9: 'candela',                      # CANDELA
     10: 'hertz',                        # HERTZ
     11: 'newton',                       # NEWTON
     12: 'pascal',                       # PASCAL
     13: 'joule',                        # JOULE
     14: 'watt',                         # WATT
     15: 'volt',                         # VOLT
     16: 'ohm',                          # OHM
     17: 'farad',                        # FARAD
     18: 'coulomb',                      # COULOMB
     19: 'siemens',                      # SIEMENS
     20: 'weber',                        # WEBER
     21: 'tesla',                        # TESLA
     22: 'henry',                        # HENRY
     23: 'lumen',                        # LUMEN
     24: 'lux',                          # LUX
     25: 'becquerel',                    # BECQUEREL
     26: 'gray',                         # GRAY
     27: 'sievert',                      # SIEVERT
     28: 'katal',                        # KATAL
     29: 'liter',                        # LITER
     30: 'minute',                       # MINUTE
     31: 'hour',                         # HOUR
     32: 'day',                          # DAY
     33: 'bvnr_degree',                  # DEGREE
     35: 'bvnr_radian',                  # RADIAN
     36: 'bvnr_steradian',               # STERADIAN
     37: 'metric_ton',                   # TONNE
     38: 'bar',                          # BAR
     39: 'electron_volt',                # ELECTRONVOLT
     40: 'dalton',                       # DALTON
     41: 'astronomical_unit',            # ASTRONOMICAL_UNIT
     42: 'hectare',                      # HECTARE
     43: 'week',                         # WEEK
     44: 'year',                         # YEAR
     45: 'inch',                         # INCH
     46: 'foot',                         # FOOT
     47: 'yard',                         # YARD
     48: 'mile',                         # MILE
     49: 'nautical_mile',                # NAUTICAL_MILE
     50: 'angstrom',                     # ANGSTROM
     51: 'light_year',                   # LIGHT_YEAR
     52: 'parsec',                       # PARSEC
     53: 'bvnr_furlong',                      # FURLONG
     54: 'bvnr_fathom',                       # FATHOM
     55: 'pound',                        # POUND
     56: 'ounce',                        # OUNCE
     57: 'grain',                        # GRAIN
     58: 'stone',                        # STONE
     59: 'short_ton',                    # SHORT_TON
     60: 'long_ton',                     # LONG_TON
     61: 'troy_ounce',                   # TROY_OUNCE
     62: 'carat',                        # CARAT
     64: 'atmosphere',                   # ATMOSPHERE
     65: 'millimeter_Hg',                # MMHG
     66: 'torr',                         # TORR
     67: 'psi',                          # PSI
     68: 'calorie',                      # CALORIE
     69: 'british_thermal_unit',         # BTU
     70: 'erg',                          # ERG
     72: 'horsepower',                   # HORSEPOWER
     73: 'force_pound',                  # POUND_FORCE
     74: 'dyne',                         # DYNE
     75: 'kip',                          # KIP
     76: 'knot',                         # KNOT
     77: 'gallon',                       # GALLON
     78: 'imperial_gallon',              # GALLON_UK
     79: 'quart',                        # QUART
     80: 'pint',                         # PINT
     81: 'cup',                          # CUP
     82: 'fluid_ounce',                  # FLUID_OUNCE
     83: 'tablespoon',                   # TABLESPOON
     84: 'teaspoon',                     # TEASPOON
     85: 'oil_barrel',                   # BARREL
     86: 'bvnr_acre',                         # ACRE
     87: 'barn',                         # BARN
     88: 'bvnr_arcminute',               # ARCMINUTE
     89: 'bvnr_arcsecond',               # ARCSECOND
     90: 'bvnr_gradian',                 # GRAD
     91: 'poise',                        # POISE
     92: 'stokes',                       # STOKES
     96: 'stilb',                        # STILB
     98: 'galileo',                      # GALILEO
     99: 'curie',                        # CURIE
    100: 'roentgen',                     # ROENTGEN
    101: 'rem',                          # REM
    104: 'degree_Rankine',               # RANKINE
    105: 'slug',                         # SLUG
    106: 'thou',                         # THOU
    107: 'imperial_pint',                # PINT_UK
    108: 'imperial_fluid_ounce',         # FLUID_OUNCE_UK
    109: 'imperial_quart',               # QUART_UK
    111: 'volt_ampere',                  # VOLT_AMPERE
    112: 'force_kilogram',               # KILOGRAM_FORCE
    113: 'inch_Hg',                      # INCH_HG
    115: 'foot_pound',                   # FOOT_POUND
    116: 'dram',                         # DRAM
    117: 'pennyweight',                  # PENNYWEIGHT
    118: 'bvnr_chain',                        # CHAIN
    119: 'bvnr_rod',                          # ROD
    120: 'gill',                         # GILL
    121: 'imperial_gill',                # GILL_UK
    122: 'standard_gravity',             # STANDARD_GRAVITY
    123: 'metric_horsepower',            # METRIC_HORSEPOWER
    124: 'bvnr_revolution',              # REVOLUTION
    125: 'month',                        # MONTH
    126: 'fortnight',                    # FORTNIGHT
    127: 'technical_atmosphere',         # ATMOSPHERE_TECHNICAL
    128: 'tex',                          # TEX
    129: 'denier',                       # DENIER
    130: 'fluid_dram',                   # FLUID_DRAM
    131: 'minim',                        # MINIM
    132: 'peck',                         # PECK
    133: 'bushel',                       # BUSHEL
    361: 'survey_foot',                  # SURVEY_FOOT
    362: 'bvnr_league',                       # LEAGUE
    364: 'hand',                         # HAND
    366: 'scruple',                      # SCRUPLE
    367: 'baud',                         # BAUD
    372: 'percent',                      # PERCENT
    373: 'permille',                     # PER_MILLE
    376: 'ppm',                          # PPM
    381: 'mile_per_hour',                # MILE_PER_HOUR
    382: 'kilometer_per_hour',           # KILOMETER_PER_HOUR

    # Affine temperature scales mapped to pint native offset units
     34: 'degC',                         # CELSIUS
     63: 'degF',                         # FAHRENHEIT
    370: 'bvnr_reaumur',                 # REAUMUR

    # Affine temperature scales defined from bovnar factor+offset (absent in pint)
    368: 'bvnr_delisle',                 # DELISLE
    369: 'bvnr_newton_temp',             # NEWTON_TEMP
    371: 'bvnr_romer',                   # ROMER

    # Defined from bovnar dimension+factor (absent in pint, or pint name collides)
     93: 'bvnr_gauss',                   # GAUSS
     94: 'bvnr_maxwell',                 # MAXWELL
     95: 'bvnr_oersted',                 # OERSTED
     97: 'bvnr_phot',                    # PHOT
    110: 'bvnr_var',                     # VAR
    348: 'bvnr_pfund',                   # PFUND
    349: 'bvnr_zentner',                 # ZENTNER
    350: 'bvnr_doppelzentner',           # DOPPELZENTNER
    351: 'bvnr_lot',                     # LOT
    352: 'bvnr_prussian_line',           # PRUSSIAN_LINE
    353: 'bvnr_prussian_zoll',           # PRUSSIAN_ZOLL
    354: 'bvnr_prussian_fuss',           # PRUSSIAN_FUSS
    355: 'bvnr_prussian_elle',           # PRUSSIAN_ELLE
    356: 'bvnr_prussian_rute',           # PRUSSIAN_RUTE
    357: 'bvnr_klafter',                 # KLAFTER
    358: 'bvnr_german_mile',             # GERMAN_MILE
    359: 'bvnr_morgen',                  # MORGEN
    360: 'bvnr_scheffel',                # SCHEFFEL
    363: 'bvnr_cable',                   # CABLE
    365: 'bvnr_quintal',                 # QUINTAL
    374: 'bvnr_per_myriad',              # PER_MYRIAD
    375: 'bvnr_per_cent_mille',          # PER_CENT_MILLE
    377: 'bvnr_ppb',                     # PPB
    380: 'bvnr_ph_scale',                # PH_SCALE
    383: 'bvnr_german_hardness',         # GERMAN_HARDNESS
    384: 'bvnr_english_hardness',        # ENGLISH_HARDNESS
    385: 'bvnr_french_hardness',         # FRENCH_HARDNESS
    386: 'bvnr_russian_hardness',        # RUSSIAN_HARDNESS
    387: 'bvnr_american_hardness',       # AMERICAN_HARDNESS
    388: 'bvnr_val',                     # VAL
    389: 'bvnr_grains_per_gallon',       # GRAINS_PER_GALLON
    390: 'bvnr_ntu',                     # TURBIDITY_NTU
    391: 'bvnr_fnu',                     # TURBIDITY_FNU
    392: 'bvnr_psu',                     # PRACTICAL_SALINITY
    393: 'bvnr_conductivity_factor',     # CONDUCTIVITY_FACTOR
    394: 'bvnr_ftu',                     # TURBIDITY_FTU
    395: 'bvnr_fau',                     # TURBIDITY_FAU
    396: 'bvnr_jtu',                     # TURBIDITY_JTU

    # Defined to match bovnar magnitude exactly (pint native uses a different convention)
     71: 'bvnr_therm',                   # THERM
    114: 'bvnr_rpm',                     # RPM

    # Quantity kinds: their own pint dimension (or, for the angle family, the
    # shared [angle] reference) so that pint refuses what bovnar refuses.
    # See KIND_DIMENSIONS above.
      2: 'bvnr_byte',                    # BYTE
    102: 'bvnr_neper',                   # NEPER
    103: 'bvnr_decibel',                 # DECIBEL

}


# --- quantity kinds: units bovnar refuses to interconvert -------------------
# bovnar tracks "quantity kinds" for units that carry NO SI dimension yet are
# not interchangeable with a plain number or with each other — bit vs byte, an
# angle vs a count, dB vs Np vs pH, and one kind per turbidity method. pint has
# no such concept: to it they are all dimensionless, so it would convert an NTU
# into an FNU or a pH into a percentage, exactly the answer bovnar exists to
# refuse.
#
# The fix is the one the currency table already uses below: give each kind its
# own pint DIMENSION. pint then enforces bovnar's rule natively —
# DimensionalityError instead of a silent number — and conversions WITHIN a kind
# keep working (m~NTU -> NTU, ° -> rad, sr -> rad²), because that is what a
# shared dimension means.
#
# The cost, and it is a real one: these units no longer speak to pint's natives.
# A bovnar-derived byte will not convert to pint's `megabyte`, nor a bovnar
# radian to pint's `degree`. Pass isolate_kinds=False to build_registry() to get
# the old aliasing back, and with it pint's permissiveness.
#
# dB and Np deliberately do NOT use pint's logarithmic units: bovnar models them
# as linear tags (a value labelled dB, not a log-arithmetic type), and mapping
# them onto pint's log units would import semantics bovnar does not have.
KIND_DIMENSIONS: dict[str, str] = {
    'bvnr_bit':         'information_bit',
    'bvnr_byte':        'information_byte',
    'bvnr_decibel':     'log_decibel',
    'bvnr_neper':       'log_neper',
    'bvnr_ph_scale':    'ph_scale',
    'bvnr_ntu':         'turbidity_ntu',
    'bvnr_fnu':         'turbidity_fnu',
    'bvnr_ftu':         'turbidity_ftu',
    'bvnr_fau':         'turbidity_fau',
    'bvnr_jtu':         'turbidity_jtu',
    'bvnr_psu':         'practical_salinity',
    'bvnr_radian':      'angle',
}

# The angle kind is SHARED: degree -> radian is a conversion people legitimately
# want, and steradian really is radian², so these are defined from the reference
# rather than as dimensions of their own.
_ANGLE_DERIVED: list[str] = [
    'bvnr_degree = %.17g * bvnr_radian' % (math.pi / 180.0),
    'bvnr_gradian = %.17g * bvnr_radian' % (math.pi / 200.0),
    'bvnr_revolution = %.17g * bvnr_radian' % (2.0 * math.pi),
    'bvnr_arcminute = %.17g * bvnr_radian' % (math.pi / 10800.0),
    'bvnr_arcsecond = %.17g * bvnr_radian' % (math.pi / 648000.0),
    'bvnr_steradian = bvnr_radian ** 2',
]

# What isolate_kinds=False falls back to: pint's native where one exists, plain
# dimensionless where none does. This is bovnar's pre-isolation behaviour, kept
# for callers who need to interoperate with pint units from other code.
_KIND_NATIVE_FALLBACK: list[str] = [
    'bvnr_bit = bit',
    'bvnr_byte = byte',
    'bvnr_decibel = decibel',
    'bvnr_neper = neper',
    'bvnr_radian = radian',
    'bvnr_degree = degree',
    'bvnr_gradian = %.17g * radian' % (math.pi / 200.0),
    'bvnr_revolution = revolution',
    'bvnr_arcminute = arcminute',
    'bvnr_arcsecond = arcsecond',
    'bvnr_steradian = steradian',
    'bvnr_ph_scale = 1.0',
    'bvnr_ntu = 1.0',
    'bvnr_fnu = 1.0',
    'bvnr_ftu = 1.0',
    'bvnr_fau = 1.0',
    'bvnr_jtu = 1.0',
    'bvnr_psu = 1.0',
]

# --- semantic caveats: parse/label OK, but value semantics differ ------------
SEMANTIC_CAVEATS: dict[str, str] = {
    'DECIBEL': 'isolated as its own pint dimension, so the conversions bovnar refuses are refused there too. What remains is arithmetic: bovnar models dB as a linear tag, so pint will add two of them and the sum is not what a decibel means (20 dB is a ratio of 100, not twice 10 dB).',
    'NEPER': 'as DECIBEL: the label and the refusals survive, the logarithmic arithmetic does not.',
    'PH_SCALE': 'as DECIBEL. pH 7 is not "7 of" anything and pH 6 is ten times the concentration of pH 7, so summing or averaging pH values is meaningless in either library.',
    'VAL': 'bovnar val is the equivalent AS USED IN WATER ANALYSIS (divalent ions): 1 val = 0.5 mol. For a monovalent species an equivalent is 1 mol, which neither library can infer from the unit alone.',
}


# --- currencies: bovnar BaseUnit code -> ISO/crypto reference-unit token ------
# Each token is BOTH the pint unit name and the basis of its private dimension
# [currency_<token>] (see CURRENCY_DEFINITIONS / build_registry).
CURRENCY_TOKENS: dict[int, str] = {
    134: 'AED',
    135: 'AFN',
    136: 'ALL',
    137: 'AMD',
    138: 'ANG',
    139: 'AOA',
    140: 'ARS',
    141: 'AUD',
    142: 'AWG',
    143: 'AZN',
    144: 'BAM',
    145: 'BBD',
    146: 'BDT',
    147: 'BGN',
    148: 'BHD',
    149: 'BIF',
    150: 'BMD',
    151: 'BND',
    152: 'BOB',
    153: 'BRL',
    154: 'BSD',
    155: 'BTN',
    156: 'BWP',
    157: 'BYN',
    158: 'BZD',
    159: 'CAD',
    160: 'CDF',
    161: 'CHF',
    162: 'CLF',
    163: 'CLP',
    164: 'CNY',
    165: 'COP',
    166: 'CRC',
    167: 'CUP',
    168: 'CVE',
    169: 'CZK',
    170: 'DJF',
    171: 'DKK',
    172: 'DOP',
    173: 'DZD',
    174: 'EGP',
    175: 'ERN',
    176: 'ETB',
    177: 'EUR',
    178: 'FJD',
    179: 'FKP',
    180: 'GBP',
    181: 'GEL',
    182: 'GHS',
    183: 'GIP',
    184: 'GMD',
    185: 'GNF',
    186: 'GTQ',
    187: 'GYD',
    188: 'HKD',
    189: 'HNL',
    190: 'HRK',
    191: 'HTG',
    192: 'HUF',
    193: 'IDR',
    194: 'ILS',
    195: 'INR',
    196: 'IQD',
    197: 'IRR',
    198: 'ISK',
    199: 'JMD',
    200: 'JOD',
    201: 'JPY',
    202: 'KES',
    203: 'KGS',
    204: 'KHR',
    205: 'KMF',
    206: 'KPW',
    207: 'KRW',
    208: 'KWD',
    209: 'KYD',
    210: 'KZT',
    211: 'LAK',
    212: 'LBP',
    213: 'LKR',
    214: 'LRD',
    215: 'LSL',
    216: 'LYD',
    217: 'MAD',
    218: 'MDL',
    219: 'MGA',
    220: 'MKD',
    221: 'MMK',
    222: 'MNT',
    223: 'MOP',
    224: 'MRU',
    225: 'MUR',
    226: 'MVR',
    227: 'MWK',
    228: 'MXN',
    229: 'MYR',
    230: 'MZN',
    231: 'NAD',
    232: 'NGN',
    233: 'NIO',
    234: 'NOK',
    235: 'NPR',
    236: 'NZD',
    237: 'OMR',
    238: 'PAB',
    239: 'PEN',
    240: 'PGK',
    241: 'PHP',
    242: 'PKR',
    243: 'PLN',
    244: 'PYG',
    245: 'QAR',
    246: 'RON',
    247: 'RSD',
    248: 'RUB',
    249: 'RWF',
    250: 'SAR',
    251: 'SBD',
    252: 'SCR',
    253: 'SDG',
    254: 'SEK',
    255: 'SGD',
    256: 'SHP',
    257: 'SLE',
    258: 'SLL',
    259: 'SOS',
    260: 'SSP',
    261: 'SRD',
    262: 'STN',
    263: 'SVC',
    264: 'SYP',
    265: 'SZL',
    266: 'THB',
    267: 'TJS',
    268: 'TMT',
    269: 'TND',
    270: 'TOP',
    271: 'TRY',
    272: 'TTD',
    273: 'TWD',
    274: 'TZS',
    275: 'UAH',
    276: 'UGX',
    277: 'USD',
    278: 'UYU',
    279: 'UZS',
    280: 'VES',
    281: 'VND',
    282: 'VUV',
    283: 'WST',
    284: 'XAF',
    285: 'XAG',
    286: 'XAU',
    287: 'XCD',
    288: 'XDR',
    289: 'XOF',
    290: 'XPD',
    291: 'XPF',
    292: 'XPT',
    293: 'XTS',
    294: 'YER',
    295: 'ZAR',
    296: 'ZMW',
    297: 'ZWL',
    298: 'BTC',
    299: 'ETH',
    300: 'SOL',
    301: 'XRP',
    302: 'BNB',
    303: 'ADA',
    304: 'LTC',
    305: 'DOT',
    306: 'XMR',
    307: 'ETC',
    308: 'BCH',
    309: 'XLM',
    310: 'FIL',
    311: 'ICP',
    312: 'TRX',
    313: 'EOS',
    314: 'VET',
    315: 'NEO',
    316: 'ZEC',
    317: 'UNI',
    318: 'ARB',
    319: 'SUI',
    320: 'TON',
    321: 'INJ',
    322: 'SEI',
    323: 'APT',
    324: 'TAO',
    325: 'WIF',
    326: 'DOGE',
    327: 'LINK',
    328: 'USDT',
    329: 'USDC',
    330: 'AVAX',
    331: 'ATOM',
    332: 'POL',
    333: 'NEAR',
    334: 'ALGO',
    335: 'HBAR',
    336: 'AAVE',
    337: 'MKR',
    338: 'DAI',
    339: 'STX',
    340: 'GRT',
    341: 'LDO',
    342: 'BONK',
    343: 'PEPE',
    344: 'SHIB',
    345: 'JUP',
    346: 'PYTH',
    347: 'RUNE',
    378: 'ZWG',
    379: 'XCG',
}

# One independent pint dimension per currency => members are non-convertible.
CURRENCY_DEFINITIONS: list[str] = [
    'AED = [currency_AED]',
    'AFN = [currency_AFN]',
    'ALL = [currency_ALL]',
    'AMD = [currency_AMD]',
    'ANG = [currency_ANG]',
    'AOA = [currency_AOA]',
    'ARS = [currency_ARS]',
    'AUD = [currency_AUD]',
    'AWG = [currency_AWG]',
    'AZN = [currency_AZN]',
    'BAM = [currency_BAM]',
    'BBD = [currency_BBD]',
    'BDT = [currency_BDT]',
    'BGN = [currency_BGN]',
    'BHD = [currency_BHD]',
    'BIF = [currency_BIF]',
    'BMD = [currency_BMD]',
    'BND = [currency_BND]',
    'BOB = [currency_BOB]',
    'BRL = [currency_BRL]',
    'BSD = [currency_BSD]',
    'BTN = [currency_BTN]',
    'BWP = [currency_BWP]',
    'BYN = [currency_BYN]',
    'BZD = [currency_BZD]',
    'CAD = [currency_CAD]',
    'CDF = [currency_CDF]',
    'CHF = [currency_CHF]',
    'CLF = [currency_CLF]',
    'CLP = [currency_CLP]',
    'CNY = [currency_CNY]',
    'COP = [currency_COP]',
    'CRC = [currency_CRC]',
    'CUP = [currency_CUP]',
    'CVE = [currency_CVE]',
    'CZK = [currency_CZK]',
    'DJF = [currency_DJF]',
    'DKK = [currency_DKK]',
    'DOP = [currency_DOP]',
    'DZD = [currency_DZD]',
    'EGP = [currency_EGP]',
    'ERN = [currency_ERN]',
    'ETB = [currency_ETB]',
    'EUR = [currency_EUR]',
    'FJD = [currency_FJD]',
    'FKP = [currency_FKP]',
    'GBP = [currency_GBP]',
    'GEL = [currency_GEL]',
    'GHS = [currency_GHS]',
    'GIP = [currency_GIP]',
    'GMD = [currency_GMD]',
    'GNF = [currency_GNF]',
    'GTQ = [currency_GTQ]',
    'GYD = [currency_GYD]',
    'HKD = [currency_HKD]',
    'HNL = [currency_HNL]',
    'HRK = [currency_HRK]',
    'HTG = [currency_HTG]',
    'HUF = [currency_HUF]',
    'IDR = [currency_IDR]',
    'ILS = [currency_ILS]',
    'INR = [currency_INR]',
    'IQD = [currency_IQD]',
    'IRR = [currency_IRR]',
    'ISK = [currency_ISK]',
    'JMD = [currency_JMD]',
    'JOD = [currency_JOD]',
    'JPY = [currency_JPY]',
    'KES = [currency_KES]',
    'KGS = [currency_KGS]',
    'KHR = [currency_KHR]',
    'KMF = [currency_KMF]',
    'KPW = [currency_KPW]',
    'KRW = [currency_KRW]',
    'KWD = [currency_KWD]',
    'KYD = [currency_KYD]',
    'KZT = [currency_KZT]',
    'LAK = [currency_LAK]',
    'LBP = [currency_LBP]',
    'LKR = [currency_LKR]',
    'LRD = [currency_LRD]',
    'LSL = [currency_LSL]',
    'LYD = [currency_LYD]',
    'MAD = [currency_MAD]',
    'MDL = [currency_MDL]',
    'MGA = [currency_MGA]',
    'MKD = [currency_MKD]',
    'MMK = [currency_MMK]',
    'MNT = [currency_MNT]',
    'MOP = [currency_MOP]',
    'MRU = [currency_MRU]',
    'MUR = [currency_MUR]',
    'MVR = [currency_MVR]',
    'MWK = [currency_MWK]',
    'MXN = [currency_MXN]',
    'MYR = [currency_MYR]',
    'MZN = [currency_MZN]',
    'NAD = [currency_NAD]',
    'NGN = [currency_NGN]',
    'NIO = [currency_NIO]',
    'NOK = [currency_NOK]',
    'NPR = [currency_NPR]',
    'NZD = [currency_NZD]',
    'OMR = [currency_OMR]',
    'PAB = [currency_PAB]',
    'PEN = [currency_PEN]',
    'PGK = [currency_PGK]',
    'PHP = [currency_PHP]',
    'PKR = [currency_PKR]',
    'PLN = [currency_PLN]',
    'PYG = [currency_PYG]',
    'QAR = [currency_QAR]',
    'RON = [currency_RON]',
    'RSD = [currency_RSD]',
    'RUB = [currency_RUB]',
    'RWF = [currency_RWF]',
    'SAR = [currency_SAR]',
    'SBD = [currency_SBD]',
    'SCR = [currency_SCR]',
    'SDG = [currency_SDG]',
    'SEK = [currency_SEK]',
    'SGD = [currency_SGD]',
    'SHP = [currency_SHP]',
    'SLE = [currency_SLE]',
    'SLL = [currency_SLL]',
    'SOS = [currency_SOS]',
    'SSP = [currency_SSP]',
    'SRD = [currency_SRD]',
    'STN = [currency_STN]',
    'SVC = [currency_SVC]',
    'SYP = [currency_SYP]',
    'SZL = [currency_SZL]',
    'THB = [currency_THB]',
    'TJS = [currency_TJS]',
    'TMT = [currency_TMT]',
    'TND = [currency_TND]',
    'TOP = [currency_TOP]',
    'TRY = [currency_TRY]',
    'TTD = [currency_TTD]',
    'TWD = [currency_TWD]',
    'TZS = [currency_TZS]',
    'UAH = [currency_UAH]',
    'UGX = [currency_UGX]',
    'USD = [currency_USD]',
    'UYU = [currency_UYU]',
    'UZS = [currency_UZS]',
    'VES = [currency_VES]',
    'VND = [currency_VND]',
    'VUV = [currency_VUV]',
    'WST = [currency_WST]',
    'XAF = [currency_XAF]',
    'XAG = [currency_XAG]',
    'XAU = [currency_XAU]',
    'XCD = [currency_XCD]',
    'XDR = [currency_XDR]',
    'XOF = [currency_XOF]',
    'XPD = [currency_XPD]',
    'XPF = [currency_XPF]',
    'XPT = [currency_XPT]',
    'XTS = [currency_XTS]',
    'YER = [currency_YER]',
    'ZAR = [currency_ZAR]',
    'ZMW = [currency_ZMW]',
    'ZWL = [currency_ZWL]',
    'BTC = [currency_BTC]',
    'ETH = [currency_ETH]',
    'SOL = [currency_SOL]',
    'XRP = [currency_XRP]',
    'BNB = [currency_BNB]',
    'ADA = [currency_ADA]',
    'LTC = [currency_LTC]',
    'DOT = [currency_DOT]',
    'XMR = [currency_XMR]',
    'ETC = [currency_ETC]',
    'BCH = [currency_BCH]',
    'XLM = [currency_XLM]',
    'FIL = [currency_FIL]',
    'ICP = [currency_ICP]',
    'TRX = [currency_TRX]',
    'EOS = [currency_EOS]',
    'VET = [currency_VET]',
    'NEO = [currency_NEO]',
    'ZEC = [currency_ZEC]',
    'UNI = [currency_UNI]',
    'ARB = [currency_ARB]',
    'SUI = [currency_SUI]',
    'TON = [currency_TON]',
    'INJ = [currency_INJ]',
    'SEI = [currency_SEI]',
    'APT = [currency_APT]',
    'TAO = [currency_TAO]',
    'WIF = [currency_WIF]',
    'DOGE = [currency_DOGE]',
    'LINK = [currency_LINK]',
    'USDT = [currency_USDT]',
    'USDC = [currency_USDC]',
    'AVAX = [currency_AVAX]',
    'ATOM = [currency_ATOM]',
    'POL = [currency_POL]',
    'NEAR = [currency_NEAR]',
    'ALGO = [currency_ALGO]',
    'HBAR = [currency_HBAR]',
    'AAVE = [currency_AAVE]',
    'MKR = [currency_MKR]',
    'DAI = [currency_DAI]',
    'STX = [currency_STX]',
    'GRT = [currency_GRT]',
    'LDO = [currency_LDO]',
    'BONK = [currency_BONK]',
    'PEPE = [currency_PEPE]',
    'SHIB = [currency_SHIB]',
    'JUP = [currency_JUP]',
    'PYTH = [currency_PYTH]',
    'RUNE = [currency_RUNE]',
    # Appended fiat (enum 378-379)
    'ZWG = [currency_ZWG]',
    'XCG = [currency_XCG]',
]


def is_currency_unit(unit) -> bool:
    """True if *unit* (a pint Unit/Quantity) is a bovnar currency.

    Detected via the ``[currency_`` dimension-name prefix, so it holds for any
    power/product that involves a currency (e.g. USD/year).
    """
    return any(str(k).startswith('[currency_') for k in unit.dimensionality)


def build_registry(reg=None, *, with_currencies: bool = True,
                   isolate_kinds: bool = True):
    """Return a pint UnitRegistry with bovnar's custom units registered.

    Pass an existing registry to extend it, or None to create a fresh one.
    Set with_currencies=False to skip the 216 currency dimensions (e.g. when
    the caller prefers to reject currency-typed data in the pint path).

    isolate_kinds (default True) gives every bovnar quantity kind its own pint
    dimension, so pint refuses exactly the conversions bovnar refuses: an NTU
    will not become an FNU, a byte will not become 8 bits, an angle will not
    become a plain number. Conversions *within* a kind keep working. Set it to
    False to alias those units onto pint's natives instead — a bovnar byte then
    converts to pint's `megabyte`, and pint also allows the conversions bovnar
    calls unsound. That trade is the caller's to make; the default is fidelity.
    """
    import pint
    if reg is None:
        reg = pint.UnitRegistry()
    for d in BOVNAR_PINT_DEFINITIONS:
        reg.define(d)
    if isolate_kinds:
        for name, dim in KIND_DIMENSIONS.items():
            reg.define('%s = [%s]' % (name, dim))
        for d in _ANGLE_DERIVED:
            reg.define(d)
    else:
        for d in _KIND_NATIVE_FALLBACK:
            reg.define(d)
    if with_currencies:
        for d in CURRENCY_DEFINITIONS:
            reg.define(d)
    return reg


def is_kind_scale(unit) -> bool:
    """True if *unit* carries one of bovnar's isolated quantity kinds.

    Only meaningful for a registry built with isolate_kinds=True (the default);
    with the natives aliased back in there is nothing to detect.
    """
    dims = getattr(unit, 'dimensionality', unit)
    wanted = set(KIND_DIMENSIONS.values())
    return any(str(name).strip('[]') in wanted for name in dims)
