from enum import IntEnum


class Event(IntEnum):

    STREAM_START                        = 0
    ASSIGNMENT_START                    = 1
    OCTET_STREAM_START                  = 2
    OCTET_STREAM_END                    = 3
    STRUCT_START                        = 4
    STRUCT_END                          = 5
    ARRAY_ROW_START                     = 6
    ARRAY_ROW_END                       = 7
    ARRAY_DIM_START                     = 8
    DATA                                = 9
    TYPE_ANNOTATION_START               = 10
    TYPE_ANNOTATION_END                 = 11
    TYPE_ANNOTATION_TYPE_FAMILY         = 12
    TYPE_ANNOTATION_TYPE_FAMILY_PARAM   = 13
    STREAM_END                          = 14


class ValueTypeFamily(IntEnum):

    PLAIN       = 0
    UTF8        = 1
    SINT        = 2
    UINT        = 3
    FLOAT       = 4
    FLOAT_FIX   = 5
    FLOAT_DEC   = 6
    ILLEGAL     = 7


class PrefixSystem(IntEnum):

    SI          = 0
    IEC         = 1
    _SENTINEL   = 2


class SIPrefix(IntEnum):

    NONE    = 0
    QUECTO  = 1
    RONTO   = 2
    YOCTO   = 3
    ZEPTO   = 4
    ATTO    = 5
    FEMTO   = 6
    PICO    = 7
    NANO    = 8
    MICRO   = 9
    MILLI   = 10
    CENTI   = 11
    DECI    = 12
    DECA    = 13
    HECTO   = 14
    KILO    = 15
    MEGA    = 16
    GIGA    = 17
    TERA    = 18
    PETA    = 19
    EXA     = 20
    ZETTA   = 21
    YOTTA   = 22
    RONNA   = 23
    QUETTA  = 24
    _SENTINEL = 25


class IECPrefix(IntEnum):

    NONE    = 0
    KIBI    = 1
    MEBI    = 2
    GIBI    = 3
    TEBI    = 4
    PEBI    = 5
    EXBI    = 6
    ZEBI    = 7
    YOBI    = 8
    ROBI    = 9
    QUEBI   = 10
    _SENTINEL = 11


class BaseUnit(IntEnum):

    # Physical units (0-133)

    NONE                = 0
    BIT                 = 1
    BYTE                = 2
    SECOND              = 3
    METER               = 4
    GRAM                = 5
    AMPERE              = 6
    KELVIN              = 7
    MOL                 = 8
    CANDELA             = 9
    HERTZ               = 10
    NEWTON              = 11
    PASCAL              = 12
    JOULE               = 13
    WATT                = 14
    VOLT                = 15
    OHM                 = 16
    FARAD               = 17
    COULOMB             = 18
    SIEMENS             = 19
    WEBER               = 20
    TESLA               = 21
    HENRY               = 22
    LUMEN               = 23
    LUX                 = 24
    BECQUEREL           = 25
    GRAY                = 26
    SIEVERT             = 27
    KATAL               = 28
    LITER               = 29
    MINUTE              = 30
    HOUR                = 31
    DAY                 = 32
    DEGREE              = 33
    CELSIUS             = 34
    RADIAN              = 35
    STERADIAN           = 36
    TONNE               = 37
    BAR                 = 38
    ELECTRONVOLT        = 39
    DALTON              = 40
    ASTRONOMICAL_UNIT   = 41
    HECTARE             = 42
    WEEK                = 43
    YEAR                = 44
    INCH                = 45
    FOOT                = 46
    YARD                = 47
    MILE                = 48
    NAUTICAL_MILE       = 49
    ANGSTROM            = 50
    LIGHT_YEAR          = 51
    PARSEC              = 52
    FURLONG             = 53
    FATHOM              = 54
    POUND               = 55
    OUNCE               = 56
    GRAIN               = 57
    STONE               = 58
    SHORT_TON           = 59
    LONG_TON            = 60
    TROY_OUNCE          = 61
    CARAT               = 62
    FAHRENHEIT          = 63
    ATMOSPHERE          = 64
    MMHG                = 65
    TORR                = 66
    PSI                 = 67
    CALORIE             = 68
    BTU                 = 69
    ERG                 = 70
    THERM               = 71
    HORSEPOWER          = 72
    POUND_FORCE         = 73
    DYNE                = 74
    KIP                 = 75
    KNOT                = 76
    GALLON              = 77
    GALLON_UK           = 78
    QUART               = 79
    PINT                = 80
    CUP                 = 81
    FLUID_OUNCE         = 82
    TABLESPOON          = 83
    TEASPOON            = 84
    BARREL              = 85
    ACRE                = 86
    BARN                = 87
    ARCMINUTE           = 88
    ARCSECOND           = 89
    GRAD                = 90
    POISE               = 91
    STOKES              = 92
    GAUSS               = 93
    MAXWELL             = 94
    OERSTED             = 95
    STILB               = 96
    PHOT                = 97
    GALILEO             = 98
    CURIE               = 99
    ROENTGEN            = 100
    REM                 = 101
    NEPER               = 102
    DECIBEL             = 103
    RANKINE             = 104
    SLUG                = 105
    THOU                = 106
    PINT_UK             = 107
    FLUID_OUNCE_UK      = 108
    QUART_UK            = 109
    VAR                 = 110
    VOLT_AMPERE         = 111
    KILOGRAM_FORCE      = 112
    INCH_HG             = 113
    RPM                 = 114
    FOOT_POUND          = 115
    DRAM                = 116
    PENNYWEIGHT         = 117
    CHAIN               = 118
    ROD                 = 119
    GILL                = 120
    GILL_UK             = 121
    STANDARD_GRAVITY    = 122
    METRIC_HORSEPOWER   = 123
    REVOLUTION          = 124
    MONTH               = 125
    FORTNIGHT           = 126
    ATMOSPHERE_TECHNICAL = 127
    TEX                 = 128
    DENIER              = 129
    FLUID_DRAM          = 130
    MINIM               = 131
    PECK                = 132
    BUSHEL              = 133

    # ISO 4217 fiat currencies (134-297)

    AED = 134   # UAE Dirham              - minor unit: 2
    AFN = 135   # Afghan Afghani          - minor unit: 2
    ALL = 136   # Albanian Lek            - minor unit: 2
    AMD = 137   # Armenian Dram           - minor unit: 2
    ANG = 138   # NL Antillean Guilder    - minor unit: 2
    AOA = 139   # Angolan Kwanza          - minor unit: 2
    ARS = 140   # Argentine Peso          - minor unit: 2
    AUD = 141   # Australian Dollar       - minor unit: 2
    AWG = 142   # Aruban Florin           - minor unit: 2
    AZN = 143   # Azerbaijani Manat       - minor unit: 2
    BAM = 144   # BH Convertible Mark     - minor unit: 2
    BBD = 145   # Barbados Dollar         - minor unit: 2
    BDT = 146   # Bangladeshi Taka        - minor unit: 2
    BGN = 147   # Bulgarian Lev           - minor unit: 2
    BHD = 148   # Bahraini Dinar          - minor unit: 3
    BIF = 149   # Burundian Franc         - minor unit: 0
    BMD = 150   # Bermudian Dollar        - minor unit: 2
    BND = 151   # Brunei Dollar           - minor unit: 2
    BOB = 152   # Boliviano               - minor unit: 2
    BRL = 153   # Brazilian Real          - minor unit: 2
    BSD = 154   # Bahamian Dollar         - minor unit: 2
    BTN = 155   # Bhutanese Ngultrum      - minor unit: 2
    BWP = 156   # Botswana Pula           - minor unit: 2
    BYN = 157   # Belarusian Ruble        - minor unit: 2
    BZD = 158   # Belize Dollar           - minor unit: 2
    CAD = 159   # Canadian Dollar         - minor unit: 2
    CDF = 160   # Congolese Franc         - minor unit: 2
    CHF = 161   # Swiss Franc             - minor unit: 2
    CLF = 162   # Unidad de Fomento       - minor unit: 4
    CLP = 163   # Chilean Peso            - minor unit: 0
    CNY = 164   # Chinese Yuan            - minor unit: 2
    COP = 165   # Colombian Peso          - minor unit: 2
    CRC = 166   # Costa Rican Colon       - minor unit: 2
    CUP_ = 167  # Cuban Peso              - minor unit: 2  (CUP_ avoids collision with physical CUP=81)
    CVE = 168   # Cape Verdean Escudo     - minor unit: 2
    CZK = 169   # Czech Koruna            - minor unit: 2
    DJF = 170   # Djiboutian Franc        - minor unit: 0
    DKK = 171   # Danish Krone            - minor unit: 2
    DOP = 172   # Dominican Peso          - minor unit: 2
    DZD = 173   # Algerian Dinar          - minor unit: 2
    EGP = 174   # Egyptian Pound          - minor unit: 2
    ERN = 175   # Eritrean Nakfa          - minor unit: 2
    ETB = 176   # Ethiopian Birr          - minor unit: 2
    EUR = 177   # Euro                    - minor unit: 2
    FJD = 178   # Fijian Dollar           - minor unit: 2
    FKP = 179   # Falkland Islands Pound  - minor unit: 2
    GBP = 180   # Pound Sterling          - minor unit: 2
    GEL = 181   # Georgian Lari           - minor unit: 2
    GHS = 182   # Ghanaian Cedi           - minor unit: 2
    GIP = 183   # Gibraltar Pound         - minor unit: 2
    GMD = 184   # Gambian Dalasi          - minor unit: 2
    GNF = 185   # Guinean Franc           - minor unit: 0
    GTQ = 186   # Guatemalan Quetzal      - minor unit: 2
    GYD = 187   # Guyanese Dollar         - minor unit: 2
    HKD = 188   # Hong Kong Dollar        - minor unit: 2
    HNL = 189   # Honduran Lempira        - minor unit: 2
    HRK = 190   # Croatian Kuna           - minor unit: 2
    HTG = 191   # Haitian Gourde          - minor unit: 2
    HUF = 192   # Hungarian Forint        - minor unit: 2
    IDR = 193   # Indonesian Rupiah       - minor unit: 2
    ILS = 194   # Israeli New Shekel      - minor unit: 2
    INR = 195   # Indian Rupee            - minor unit: 2
    IQD = 196   # Iraqi Dinar             - minor unit: 3
    IRR = 197   # Iranian Rial            - minor unit: 2
    ISK = 198   # Icelandic Krona         - minor unit: 0
    JMD = 199   # Jamaican Dollar         - minor unit: 2
    JOD = 200   # Jordanian Dinar         - minor unit: 3
    JPY = 201   # Japanese Yen            - minor unit: 0
    KES = 202   # Kenyan Shilling         - minor unit: 2
    KGS = 203   # Kyrgystani Som          - minor unit: 2
    KHR = 204   # Cambodian Riel          - minor unit: 2
    KMF = 205   # Comorian Franc          - minor unit: 0
    KPW = 206   # North Korean Won        - minor unit: 2
    KRW = 207   # South Korean Won        - minor unit: 0
    KWD = 208   # Kuwaiti Dinar           - minor unit: 3
    KYD = 209   # Cayman Islands Dollar   - minor unit: 2
    KZT = 210   # Kazakhstani Tenge       - minor unit: 2
    LAK = 211   # Laotian Kip             - minor unit: 2
    LBP = 212   # Lebanese Pound          - minor unit: 2
    LKR = 213   # Sri Lankan Rupee        - minor unit: 2
    LRD = 214   # Liberian Dollar         - minor unit: 2
    LSL = 215   # Lesotho Loti            - minor unit: 2
    LYD = 216   # Libyan Dinar            - minor unit: 3
    MAD = 217   # Moroccan Dirham         - minor unit: 2
    MDL = 218   # Moldovan Leu            - minor unit: 2
    MGA = 219   # Malagasy Ariary         - minor unit: 2
    MKD = 220   # Macedonian Denar        - minor unit: 2
    MMK = 221   # Myanmar Kyat            - minor unit: 2
    MNT = 222   # Mongolian Togrog        - minor unit: 2
    MOP = 223   # Macanese Pataca         - minor unit: 2
    MRU = 224   # Mauritanian Ouguiya     - minor unit: 2
    MUR = 225   # Mauritian Rupee         - minor unit: 2
    MVR = 226   # Maldivian Rufiyaa       - minor unit: 2
    MWK = 227   # Malawian Kwacha         - minor unit: 2
    MXN = 228   # Mexican Peso            - minor unit: 2
    MYR = 229   # Malaysian Ringgit       - minor unit: 2
    MZN = 230   # Mozambican Metical      - minor unit: 2
    NAD = 231   # Namibian Dollar         - minor unit: 2
    NGN = 232   # Nigerian Naira          - minor unit: 2
    NIO = 233   # Nicaraguan Cordoba      - minor unit: 2
    NOK = 234   # Norwegian Krone         - minor unit: 2
    NPR = 235   # Nepalese Rupee          - minor unit: 2
    NZD = 236   # New Zealand Dollar      - minor unit: 2
    OMR = 237   # Omani Rial              - minor unit: 3
    PAB = 238   # Panamanian Balboa       - minor unit: 2
    PEN = 239   # Peruvian Sol            - minor unit: 2
    PGK = 240   # Papua New Guinean Kina  - minor unit: 2
    PHP = 241   # Philippine Peso         - minor unit: 2
    PKR = 242   # Pakistani Rupee         - minor unit: 2
    PLN = 243   # Polish Zloty            - minor unit: 2
    PYG = 244   # Paraguayan Guarani      - minor unit: 0
    QAR = 245   # Qatari Riyal            - minor unit: 2
    RON = 246   # Romanian Leu            - minor unit: 2
    RSD = 247   # Serbian Dinar           - minor unit: 2
    RUB = 248   # Russian Ruble           - minor unit: 2
    RWF = 249   # Rwandan Franc           - minor unit: 0
    SAR = 250   # Saudi Riyal             - minor unit: 2
    SBD = 251   # Solomon Islands Dollar  - minor unit: 2
    SCR = 252   # Seychellois Rupee       - minor unit: 2
    SDG = 253   # Sudanese Pound          - minor unit: 2
    SEK = 254   # Swedish Krona           - minor unit: 2
    SGD = 255   # Singapore Dollar        - minor unit: 2
    SHP = 256   # Saint Helena Pound      - minor unit: 2
    SLE = 257   # Sierra Leonean Leone    - minor unit: 2
    SLL = 258   # Sierra Leonean Leone (old) - minor unit: 2
    SOS = 259   # Somali Shilling         - minor unit: 2
    SSP = 260   # South Sudanese Pound    - minor unit: 2
    SRD = 261   # Surinamese Dollar       - minor unit: 2
    STN = 262   # Sao Tome Dobra          - minor unit: 2
    SVC = 263   # Salvadoran Colon        - minor unit: 2
    SYP = 264   # Syrian Pound            - minor unit: 2
    SZL = 265   # Swazi Lilangeni         - minor unit: 2
    THB = 266   # Thai Baht               - minor unit: 2
    TJS = 267   # Tajikistani Somoni      - minor unit: 2
    TMT = 268   # Turkmenistan Manat      - minor unit: 2
    TND = 269   # Tunisian Dinar          - minor unit: 3
    TOP = 270   # Tongan Pa'anga          - minor unit: 2
    TRY = 271   # Turkish Lira            - minor unit: 2
    TTD = 272   # Trinidad/Tobago Dollar  - minor unit: 2
    TWD = 273   # New Taiwan Dollar       - minor unit: 2
    TZS = 274   # Tanzanian Shilling      - minor unit: 2
    UAH = 275   # Ukrainian Hryvnia       - minor unit: 2
    UGX = 276   # Ugandan Shilling        - minor unit: 0
    USD = 277   # US Dollar               - minor unit: 2
    UYU = 278   # Uruguayan Peso          - minor unit: 2
    UZS = 279   # Uzbekistani Som         - minor unit: 2
    VES = 280   # Venezuelan Bolivar      - minor unit: 2
    VND = 281   # Vietnamese Dong         - minor unit: 0
    VUV = 282   # Vanuatu Vatu            - minor unit: 0
    WST = 283   # Samoan Tala             - minor unit: 2
    XAF = 284   # CFA Franc BEAC          - minor unit: 0
    XAG = 285   # Silver                  - minor unit: 0
    XAU = 286   # Gold                    - minor unit: 0
    XCD = 287   # East Caribbean Dollar   - minor unit: 2
    XDR = 288   # Special Drawing Rights  - minor unit: 0
    XOF = 289   # CFA Franc BCEAO         - minor unit: 0
    XPD = 290   # Palladium               - minor unit: 0
    XPF = 291   # CFP Franc               - minor unit: 0
    XPT = 292   # Platinum                - minor unit: 0
    XTS = 293   # Test                    - minor unit: 0
    YER = 294   # Yemeni Rial             - minor unit: 2
    ZAR = 295   # South African Rand      - minor unit: 2
    ZMW = 296   # Zambian Kwacha          - minor unit: 2
    ZWL = 297   # Zimbabwean Dollar       - minor unit: 2

    # Cryptocurrencies (298-347)
    # minor_unit = on-chain canonical decimal places.
    # numeric_code = 0 (not ISO 4217).

    BTC  = 298  # Bitcoin             - minor unit: 8  (satoshi)
    ETH  = 299  # Ethereum            - minor unit: 18 (wei)
    SOL  = 300  # Solana              - minor unit: 9  (lamport)
    XRP  = 301  # XRP                 - minor unit: 6  (drop)
    BNB  = 302  # BNB                 - minor unit: 18
    ADA  = 303  # Cardano             - minor unit: 6  (lovelace)
    LTC  = 304  # Litecoin            - minor unit: 8  (litoshi)
    DOT  = 305  # Polkadot            - minor unit: 10 (planck)
    XMR  = 306  # Monero              - minor unit: 12 (piconero)
    ETC  = 307  # Ethereum Classic    - minor unit: 18
    BCH  = 308  # Bitcoin Cash        - minor unit: 8
    XLM  = 309  # Stellar             - minor unit: 7  (stroop)
    FIL  = 310  # Filecoin            - minor unit: 18
    ICP  = 311  # Internet Computer   - minor unit: 8
    TRX  = 312  # TRON                - minor unit: 6
    EOS  = 313  # EOS                 - minor unit: 4
    VET  = 314  # VeChain             - minor unit: 18
    NEO  = 315  # Neo                 - minor unit: 8
    ZEC  = 316  # Zcash               - minor unit: 8
    UNI  = 317  # Uniswap             - minor unit: 18
    ARB  = 318  # Arbitrum            - minor unit: 18
    SUI  = 319  # Sui                 - minor unit: 9
    TON  = 320  # Toncoin             - minor unit: 9
    INJ  = 321  # Injective           - minor unit: 18
    SEI  = 322  # Sei                 - minor unit: 6
    APT  = 323  # Aptos               - minor unit: 8
    TAO  = 324  # Bittensor           - minor unit: 9
    WIF  = 325  # dogwifhat           - minor unit: 6
    DOGE = 326  # Dogecoin            - minor unit: 8  (koinu)
    LINK = 327  # Chainlink           - minor unit: 18
    USDT = 328  # Tether              - minor unit: 6
    USDC = 329  # USD Coin            - minor unit: 6
    AVAX = 330  # Avalanche           - minor unit: 18
    ATOM = 331  # Cosmos              - minor unit: 6
    POL  = 332  # Polygon             - minor unit: 18
    NEAR = 333  # NEAR Protocol       - minor unit: 24
    ALGO = 334  # Algorand            - minor unit: 6
    HBAR = 335  # Hedera              - minor unit: 8
    AAVE = 336  # Aave                - minor unit: 18
    MKR  = 337  # Maker               - minor unit: 18
    DAI  = 338  # Dai                 - minor unit: 18
    STX  = 339  # Stacks              - minor unit: 6
    GRT  = 340  # The Graph           - minor unit: 18
    LDO  = 341  # Lido DAO            - minor unit: 18
    BONK = 342  # Bonk                - minor unit: 5
    PEPE = 343  # Pepe                - minor unit: 18
    SHIB = 344  # Shiba Inu           - minor unit: 18
    JUP  = 345  # Jupiter             - minor unit: 6
    PYTH = 346  # Pyth Network        - minor unit: 6
    RUNE = 347  # THORChain           - minor unit: 8

    # Historical/German units (348-360)

    PFUND              = 348
    ZENTNER            = 349
    DOPPELZENTNER      = 350
    LOT                = 351
    PRUSSIAN_LINE      = 352
    PRUSSIAN_ZOLL      = 353
    PRUSSIAN_FUSS      = 354
    PRUSSIAN_ELLE      = 355
    PRUSSIAN_RUTE      = 356
    KLAFTER            = 357
    GERMAN_MILE        = 358
    MORGEN             = 359
    SCHEFFEL           = 360

    # Additional physical units (361-367)

    SURVEY_FOOT        = 361
    LEAGUE             = 362
    CABLE              = 363
    HAND               = 364
    QUINTAL            = 365
    SCRUPLE            = 366
    BAUD               = 367

    _SENTINEL = 368


# Currency-range sentinels (mirrors C #defines)

CURRENCY_FIAT_FIRST   = BaseUnit.AED
CURRENCY_FIAT_LAST    = BaseUnit.ZWL
CURRENCY_CRYPTO_FIRST = BaseUnit.BTC
CURRENCY_CRYPTO_LAST  = BaseUnit.RUNE


class Exponent(IntEnum):

    INVALID     =  0
    LINEAR      =  1
    SQUARE      =  2
    CUBIC       =  3
    QUARTIC     =  4
    QUINTIC     =  5
    SEXTIC      =  6
    SEPTIC      =  7
    OCTIC       =  8
    NONIC       =  9
    NEG_LINEAR  = -1
    NEG_SQUARE  = -2
    NEG_CUBIC   = -3
    NEG_QUARTIC = -4
    NEG_QUINTIC = -5
    NEG_SEXTIC  = -6
    NEG_SEPTIC  = -7
    NEG_OCTIC   = -8
    NEG_NONIC   = -9


class ErrorCode(IntEnum):

    NONE                        = 0
    UNKNOWN_TOKEN_TYPE          = 1
    ARRAY_ROW_SIZE_MISMATCH     = 2
    IDENTIFIER_TOO_LONG         = 3
    EMPTY_IDENTIFIER            = 4
    STRUCT_NESTING_TOO_HIGH     = 5
    ARRAY_NESTING_TOO_HIGH      = 6
    ILLEGAL_STRUCT_CLOSE        = 7
    STRING_TOO_LONG             = 8
    ILLEGAL_ESCAPE_SEQUENCE     = 9
    NUMBER_TOO_LONG             = 10
    SYMBOL_TOO_LONG             = 11
    REFERENCE_TOO_LONG          = 12
    READ_COMPLETE_CHUNK_FAILED  = 13
    OCTET_STREAM_OUT_OF_SYNC    = 14
    UNEXPECTED_INPUT_BYTE       = 15
    TEXT_DATA_TOO_LONG          = 16
    READING_FROM_SOURCE_FD      = 17
    GOT_INCOMPLETE_BVNR_STREAM  = 18
    INVALID_UTF8_BYTE           = 19
    INVALID_BYTE_ORDER_MARK     = 20
    TYPE_TOO_LONG               = 21
    UNIT_TOO_LONG               = 22
    EXPECTED_STRING_IN_ARRAY    = 23
    EXPECTED_NUMBER_IN_ARRAY    = 24
    ILLEGAL_VALUE_TYPE          = 25
    SCANNER_CALLBACK_FAILED     = 26
    FILE_TOO_LONG               = 27
    INVALID_ARGUMENT            = 28
    TOO_MANY_ARRAY_ITEMS        = 29
    WRITING_TO_SINK             = 30
    SINK_BUFFER_EXHAUSTED       = 31
    UNIT_ILLEGAL                = 32
    BASE_REQUIRES_STRING_LITERAL = 33
    TYPE_VALUE_MISMATCH         = 34
    VALUE_OUT_OF_RANGE          = 35
    DIGIT_NOT_IN_BASE           = 36
    RECOVERED                   = 37
    UNIT_MISMATCH               = 38
