/* GENERATED by gen_currencies.py from src/gendata/currencies.bvnr — DO NOT EDIT. */

/* The currency block of the base-unit id space: one contiguous run,
 * ascending, from BVN_CURRENCY_FIRST. A currency's catalogue index is
 * its id minus BVN_CURRENCY_FIRST — see bvn_currency_index(). Whether
 * a currency is crypto is a COLUMN of the catalogue, not a sub-range
 * of the ids, so appending one of either kind renumbers nothing. */
#define BVN_CURRENCY_FIRST      900000
#define BVN_CURRENCY_LAST       900215
#define BVN_CURRENCY_COUNT      216
#define BVNR_CURRENCY_ROWS      216
