/* GENERATED by gen_ucum.py from src/gendata/ucum.bvnr — DO NOT EDIT. */
	bu_ucum_iu          = 397,
	bu_ucum_iu_i        = 398,
	bu_ucum_arb_u       = 399,
	bu_ucum_usp_u       = 400,
	bu_ucum_gpl_u       = 401,
	bu_ucum_mpl_u       = 402,
	bu_ucum_apl_u       = 403,
	bu_ucum_beth_u      = 404,
	bu_ucum_anti_xa_u   = 405,
	bu_ucum_todd_u      = 406,
	bu_ucum_dye_u       = 407,
	bu_ucum_smgy_u      = 408,
	bu_ucum_bdsk_u      = 409,
	bu_ucum_ka_u        = 410,
	bu_ucum_knk_u       = 411,
	bu_ucum_mclg_u      = 412,
	bu_ucum_tb_u        = 413,
	bu_ucum_ccid_50     = 414,
	bu_ucum_tcid_50     = 415,
	bu_ucum_eid_50      = 416,
	bu_ucum_pfu         = 417,
	bu_ucum_ffu         = 418,
	bu_ucum_cfu         = 419,
	bu_ucum_bau         = 420,
	bu_ucum_au_allerg   = 421,
	bu_ucum_amb_a_1_u   = 422,
	bu_ucum_pnu         = 423,
	bu_ucum_lf          = 424,
	bu_ucum_d_ag_u      = 425,
	bu_ucum_feu         = 426,
	bu_ucum_elu         = 427,
	bu_ucum_eu          = 428,

/* The arbitrary block, bracketed for the two-comparison membership test in
 * bvni_is_arbitrary(). Contiguity is enforced by gen_ucum.py. */
#define BVN_UCUM_ARBITRARY_FIRST 397
#define BVN_UCUM_ARBITRARY_LAST  428
#define BVN_UCUM_ARBITRARY_COUNT 32
