/* GENERATED by gen_profiles.py from src/gendata/the profile data files — DO NOT EDIT. */
	/* ucum */
	bu_ucum_iu          = 397,
	bu_ucum_iu_i        = 398,
	bu_ucum_arb_u       = 399,
	bu_ucum_usp_u       = 400,
	bu_ucum_gpl_u       = 401,
	bu_ucum_mpl_u       = 402,
	bu_ucum_apl_u       = 403,
	bu_ucum_beth_u      = 404,
	bu_ucum_anti_xa_u   = 405,
	bu_ucum_todd_u      = 406,
	bu_ucum_dye_u       = 407,
	bu_ucum_smgy_u      = 408,
	bu_ucum_bdsk_u      = 409,
	bu_ucum_ka_u        = 410,
	bu_ucum_knk_u       = 411,
	bu_ucum_mclg_u      = 412,
	bu_ucum_tb_u        = 413,
	bu_ucum_ccid_50     = 414,
	bu_ucum_tcid_50     = 415,
	bu_ucum_eid_50      = 416,
	bu_ucum_pfu         = 417,
	bu_ucum_ffu         = 418,
	bu_ucum_cfu         = 419,
	bu_ucum_bau         = 420,
	bu_ucum_au_allerg   = 421,
	bu_ucum_amb_a_1_u   = 422,
	bu_ucum_pnu         = 423,
	bu_ucum_lf          = 424,
	bu_ucum_d_ag_u      = 425,
	bu_ucum_feu         = 426,
	bu_ucum_elu         = 427,
	bu_ucum_eu          = 428,
	bu_ucum_hp_x        = 429,
	bu_ucum_hp_c        = 430,
	bu_ucum_hp_m        = 431,
	bu_ucum_hp_q        = 432,
	bu_ucum_kp_x        = 433,
	bu_ucum_kp_c        = 434,
	bu_ucum_kp_m        = 435,
	bu_ucum_kp_q        = 436,
	bu_ucum_ir          = 437,
	/* unece */
	bu_unece_one        = 438,
	bu_unece_piece      = 439,
	bu_unece_article    = 440,
	bu_unece_pair       = 441,
	bu_unece_set        = 442,
	bu_unece_bag        = 443,
	bu_unece_barrel     = 444,
	bu_unece_bottle     = 445,
	bu_unece_box        = 446,
	bu_unece_bunch      = 447,
	bu_unece_can        = 448,
	bu_unece_carton     = 449,
	bu_unece_case       = 450,
	bu_unece_container  = 451,
	bu_unece_crate      = 452,
	bu_unece_drum       = 453,
	bu_unece_package    = 454,
	bu_unece_packet     = 455,
	bu_unece_pallet     = 456,
	bu_unece_reel       = 457,
	bu_unece_roll       = 458,
	bu_unece_sack       = 459,
	bu_unece_sheet      = 460,
	bu_unece_tube       = 461,
	bu_unece_vial       = 462,

/* The opaque block: profile-only base units with no native
 * spelling and no dimension. Bracketed for the two-comparison
 * membership test in bvni_is_opaque(). Contiguity across every
 * profile is enforced by gen_profiles.py. */
#define BVN_PROFILE_OPAQUE_FIRST 397
#define BVN_PROFILE_OPAQUE_LAST  462
#define BVN_PROFILE_OPAQUE_COUNT 66

/* Per-profile sub-ranges, so the writer can name the
 * namespace that owns an opaque unit. FIRST > LAST means the
 * profile contributes none. */
#define BVN_PROFILE_UCUM_OPAQUE_FIRST 397
#define BVN_PROFILE_UCUM_OPAQUE_LAST  437
#define BVN_PROFILE_UNECE_OPAQUE_FIRST 438
#define BVN_PROFILE_UNECE_OPAQUE_LAST  462
#define BVN_PROFILE_QUDT_OPAQUE_FIRST 463
#define BVN_PROFILE_QUDT_OPAQUE_LAST  462
#define BVN_PROFILE_QUDT_QK_OPAQUE_FIRST 463
#define BVN_PROFILE_QUDT_QK_OPAQUE_LAST  462
#define BVN_PROFILE_UDUNITS_OPAQUE_FIRST 463
#define BVN_PROFILE_UDUNITS_OPAQUE_LAST  462
