# Is web/bovnar_wasm.js still a faithful copy of its source, wasm/index.mjs?
#
# build_wasm.sh GENERATES web/bovnar_wasm.js from wasm/index.mjs, rewriting only
# the core import to a cache-busted URL. Editing the generated copy looks like it
# works -- the site picks the change up immediately -- and is then silently
# reverted by the next build. That happened once already: a batch of OOM-handling
# fixes lived only in the copy and would have vanished without a trace.
#
# Normalise the one intended difference and require the rest to match exactly.
if(NOT EXISTS "${SRC}")
    message(FATAL_ERROR "wrapper source missing: ${SRC}")
endif()
if(NOT EXISTS "${COPY}")
    message(FATAL_ERROR "generated wrapper missing: ${COPY} -- run wasm/build_wasm.sh")
endif()

file(READ "${SRC}"  _src)
file(READ "${COPY}" _copy)
# The generated copy imports './bovnar_wasm_core.js?v=<hash>'; the source imports
# './bovnar.mjs'. Everything else must be identical.
string(REGEX REPLACE "'\\./bovnar_wasm_core\\.js\\?v=[0-9a-f]+'" "'./bovnar.mjs'" _copy_norm "${_copy}")

if(NOT _src STREQUAL _copy_norm)
    message(FATAL_ERROR
        "web/bovnar_wasm.js has diverged from its source wasm/index.mjs.\n"
        "That file is GENERATED by wasm/build_wasm.sh -- an edit made directly to "
        "it will be silently reverted by the next build. Move the change into "
        "wasm/index.mjs and re-run wasm/build_wasm.sh.")
endif()
message(STATUS "WASM wrapper copy is in sync with wasm/index.mjs")
